// SPDX-License-Identifier: MIT
//
// Auto-generated by scripts/gen_gen3_data.py -- DO NOT EDIT BY HAND.
//
// Gen 2/3-mechanics battle data (Special split, Dark/Steel, modern type chart
// and move typings). Physical/special is still decided by TYPE (Gen 4 made it
// per-move). Source: Pokemon Showdown data (MIT), Smogon University.
// Pokemon and all related marks are trademarks of Nintendo / Game Freak /
// Creatures -- this file contains only mechanical/statistical data.
//
#pragma once
#include <stdint.h>


#include "showdown_gen1_moves.h"  // reuse Gen1MoveData + EFF_* enum

// All Gen 1-3 moves (national ids 1..354), typed & powered to modern
// (Gen 2/3+) values from Pokemon Showdown. Ids 1-165 keep the engine
// EFF_* effect + effect chance the Gen-1 saves rely on; the Gen 2/3
// additions (166-354) are damage-only (EFF_NONE) for now -- status
// effects can be layered in later. Category is derived from the type.
static constexpr Gen1MoveData GEN3_MOVES[] = {
    {   1, "Pound",  0,  40, 100, 35,  0, EFF_NONE,   0 },  // pound
    {   2, "Karate Chop",  1,  50, 100, 25,  0, EFF_NONE,   0 },  // karatechop
    {   3, "Double Slap",  0,  15,  85, 10,  0, EFF_MULTI_HIT,   0 },  // doubleslap
    {   4, "Comet Punch",  0,  18,  85, 15,  0, EFF_MULTI_HIT,   0 },  // cometpunch
    {   5, "Mega Punch",  0,  80,  85, 20,  0, EFF_NONE,   0 },  // megapunch
    {   6, "Pay Day",  0,  40, 100, 20,  0, EFF_PAY_DAY,   0 },  // payday
    {   7, "Fire Punch",  9,  75, 100, 15,  0, EFF_STATUS_BRN,  10 },  // firepunch
    {   8, "Ice Punch", 14,  75, 100, 15,  0, EFF_STATUS_FRZ,  10 },  // icepunch
    {   9, "Thunder Punch", 12,  75, 100, 15,  0, EFF_STATUS_PAR,  10 },  // thunderpunch
    {  10, "Scratch",  0,  40, 100, 35,  0, EFF_NONE,   0 },  // scratch
    {  11, "Vise Grip",  0,  55, 100, 30,  0, EFF_NONE,   0 },  // visegrip
    {  12, "Guillotine",  0,   0,  30,  5,  0, EFF_OHKO,   0 },  // guillotine
    {  13, "Razor Wind",  0,  80, 100, 10,  0, EFF_CHARGE_TURN,   0 },  // razorwind
    {  14, "Swords Dance",  0,   0,   0, 20,  0, EFF_BOOST_ATK,   0 },  // swordsdance
    {  15, "Cut",  0,  50,  95, 30,  0, EFF_NONE,   0 },  // cut
    {  16, "Gust",  2,  40, 100, 35,  0, EFF_NONE,   0 },  // gust
    {  17, "Wing Attack",  2,  60, 100, 35,  0, EFF_NONE,   0 },  // wingattack
    {  18, "Whirlwind",  0,   0,   0, 20, -6, EFF_NONE,   0 },  // whirlwind
    {  19, "Fly",  2,  90,  95, 15,  0, EFF_CHARGE_TURN,   0 },  // fly
    {  20, "Bind",  0,  15,  85, 20,  0, EFF_TRAPPING,   0 },  // bind
    {  21, "Slam",  0,  80,  75, 20,  0, EFF_NONE,   0 },  // slam
    {  22, "Vine Whip", 11,  45, 100, 25,  0, EFF_NONE,   0 },  // vinewhip
    {  23, "Stomp",  0,  65, 100, 20,  0, EFF_FLINCH,  30 },  // stomp
    {  24, "Double Kick",  1,  30, 100, 30,  0, EFF_DOUBLE_HIT,   0 },  // doublekick
    {  25, "Mega Kick",  0, 120,  75,  5,  0, EFF_NONE,   0 },  // megakick
    {  26, "Jump Kick",  1, 100,  95, 10,  0, EFF_NONE,   0 },  // jumpkick
    {  27, "Rolling Kick",  1,  60,  85, 15,  0, EFF_FLINCH,  30 },  // rollingkick
    {  28, "Sand Attack",  4,   0, 100, 15,  0, EFF_DROP_ACC,   0 },  // sandattack
    {  29, "Headbutt",  0,  70, 100, 15,  0, EFF_FLINCH,  30 },  // headbutt
    {  30, "Horn Attack",  0,  65, 100, 25,  0, EFF_NONE,   0 },  // hornattack
    {  31, "Fury Attack",  0,  15,  85, 20,  0, EFF_MULTI_HIT,   0 },  // furyattack
    {  32, "Horn Drill",  0,   0,  30,  5,  0, EFF_OHKO,   0 },  // horndrill
    {  33, "Tackle",  0,  40, 100, 35,  0, EFF_NONE,   0 },  // tackle
    {  34, "Body Slam",  0,  85, 100, 15,  0, EFF_STATUS_PAR,  30 },  // bodyslam
    {  35, "Wrap",  0,  15,  90, 20,  0, EFF_TRAPPING,   0 },  // wrap
    {  36, "Take Down",  0,  90,  85, 20,  0, EFF_RECOIL,   0 },  // takedown
    {  37, "Thrash",  0, 120, 100, 10,  0, EFF_THRASH,   0 },  // thrash
    {  38, "Double-Edge",  0, 120, 100, 15,  0, EFF_RECOIL,   0 },  // doubleedge
    {  39, "Tail Whip",  0,   0, 100, 30,  0, EFF_DROP_DEF,   0 },  // tailwhip
    {  40, "Poison Sting",  3,  15, 100, 35,  0, EFF_STATUS_PSN,  30 },  // poisonsting
    {  41, "Twineedle",  7,  25, 100, 20,  0, EFF_NONE,  20 },  // twineedle
    {  42, "Pin Missile",  7,  25,  95, 20,  0, EFF_MULTI_HIT,   0 },  // pinmissile
    {  43, "Leer",  0,   0, 100, 30,  0, EFF_DROP_DEF,   0 },  // leer
    {  44, "Bite", 16,  60, 100, 25,  0, EFF_FLINCH,  30 },  // bite
    {  45, "Growl",  0,   0, 100, 40,  0, EFF_DROP_ATK,   0 },  // growl
    {  46, "Roar",  0,   0,   0, 20, -6, EFF_NONE,   0 },  // roar
    {  47, "Sing",  0,   0,  55, 15,  0, EFF_STATUS_SLP,   0 },  // sing
    {  48, "Supersonic",  0,   0,  55, 20,  0, EFF_STATUS_CONFUSE,   0 },  // supersonic
    {  49, "Sonic Boom",  0,   0,  90, 20,  0, EFF_FIXED_DMG,   0 },  // sonicboom
    {  50, "Disable",  0,   0, 100, 20,  0, EFF_DISABLE,   0 },  // disable
    {  51, "Acid",  3,  40, 100, 30,  0, EFF_NONE,  10 },  // acid
    {  52, "Ember",  9,  40, 100, 25,  0, EFF_STATUS_BRN,  10 },  // ember
    {  53, "Flamethrower",  9,  90, 100, 15,  0, EFF_STATUS_BRN,  10 },  // flamethrower
    {  54, "Mist", 14,   0,   0, 30,  0, EFF_MIST,   0 },  // mist
    {  55, "Water Gun", 10,  40, 100, 25,  0, EFF_NONE,   0 },  // watergun
    {  56, "Hydro Pump", 10, 110,  80,  5,  0, EFF_NONE,   0 },  // hydropump
    {  57, "Surf", 10,  90, 100, 15,  0, EFF_NONE,   0 },  // surf
    {  58, "Ice Beam", 14,  90, 100, 10,  0, EFF_STATUS_FRZ,  10 },  // icebeam
    {  59, "Blizzard", 14, 110,  70,  5,  0, EFF_STATUS_FRZ,  10 },  // blizzard
    {  60, "Psybeam", 13,  65, 100, 20,  0, EFF_STATUS_CONFUSE,  10 },  // psybeam
    {  61, "Bubble Beam", 10,  65, 100, 20,  0, EFF_NONE,  10 },  // bubblebeam
    {  62, "Aurora Beam", 14,  65, 100, 20,  0, EFF_NONE,  10 },  // aurorabeam
    {  63, "Hyper Beam",  0, 150,  90,  5,  0, EFF_HYPER_BEAM,   0 },  // hyperbeam
    {  64, "Peck",  2,  35, 100, 35,  0, EFF_NONE,   0 },  // peck
    {  65, "Drill Peck",  2,  80, 100, 20,  0, EFF_NONE,   0 },  // drillpeck
    {  66, "Submission",  1,  80,  80, 20,  0, EFF_RECOIL,   0 },  // submission
    {  67, "Low Kick",  1,   0, 100, 20,  0, EFF_FLINCH,   0 },  // lowkick
    {  68, "Counter",  1,   0, 100, 20, -5, EFF_COUNTER,   0 },  // counter
    {  69, "Seismic Toss",  1,   0, 100, 20,  0, EFF_LEVEL_DMG,   0 },  // seismictoss
    {  70, "Strength",  0,  80, 100, 15,  0, EFF_NONE,   0 },  // strength
    {  71, "Absorb", 11,  20, 100, 25,  0, EFF_DRAIN_HP,   0 },  // absorb
    {  72, "Mega Drain", 11,  40, 100, 15,  0, EFF_DRAIN_HP,   0 },  // megadrain
    {  73, "Leech Seed", 11,   0,  90, 10,  0, EFF_DRAIN_HP,   0 },  // leechseed
    {  74, "Growth",  0,   0,   0, 20,  0, EFF_BOOST_SPC,   0 },  // growth
    {  75, "Razor Leaf", 11,  55,  95, 25,  0, EFF_NONE,   0 },  // razorleaf
    {  76, "Solar Beam", 11, 120, 100, 10,  0, EFF_CHARGE_TURN,   0 },  // solarbeam
    {  77, "Poison Powder",  3,   0,  75, 35,  0, EFF_STATUS_PSN,   0 },  // poisonpowder
    {  78, "Stun Spore", 11,   0,  75, 30,  0, EFF_STATUS_PAR,   0 },  // stunspore
    {  79, "Sleep Powder", 11,   0,  75, 15,  0, EFF_STATUS_SLP,   0 },  // sleeppowder
    {  80, "Petal Dance", 11, 120, 100, 10,  0, EFF_THRASH,   0 },  // petaldance
    {  81, "String Shot",  7,   0,  95, 40,  0, EFF_DROP_SPD,   0 },  // stringshot
    {  82, "Dragon Rage", 15,   0, 100, 10,  0, EFF_FIXED_DMG,   0 },  // dragonrage
    {  83, "Fire Spin",  9,  35,  85, 15,  0, EFF_TRAPPING,   0 },  // firespin
    {  84, "Thunder Shock", 12,  40, 100, 30,  0, EFF_STATUS_PAR,  10 },  // thundershock
    {  85, "Thunderbolt", 12,  90, 100, 15,  0, EFF_STATUS_PAR,  10 },  // thunderbolt
    {  86, "Thunder Wave", 12,   0,  90, 20,  0, EFF_STATUS_PAR,   0 },  // thunderwave
    {  87, "Thunder", 12, 110,  70, 10,  0, EFF_STATUS_PAR,  30 },  // thunder
    {  88, "Rock Throw",  5,  50,  90, 15,  0, EFF_NONE,   0 },  // rockthrow
    {  89, "Earthquake",  4, 100, 100, 10,  0, EFF_NONE,   0 },  // earthquake
    {  90, "Fissure",  4,   0,  30,  5,  0, EFF_OHKO,   0 },  // fissure
    {  91, "Dig",  4,  80, 100, 10,  0, EFF_CHARGE_TURN,   0 },  // dig
    {  92, "Toxic",  3,   0,  90, 10,  0, EFF_STATUS_PSN,   0 },  // toxic
    {  93, "Confusion", 13,  50, 100, 25,  0, EFF_STATUS_CONFUSE,  10 },  // confusion
    {  94, "Psychic", 13,  90, 100, 10,  0, EFF_NONE,  10 },  // psychic
    {  95, "Hypnosis", 13,   0,  60, 20,  0, EFF_STATUS_SLP,   0 },  // hypnosis
    {  96, "Meditate", 13,   0,   0, 40,  0, EFF_BOOST_ATK,   0 },  // meditate
    {  97, "Agility", 13,   0,   0, 30,  0, EFF_BOOST_SPD,   0 },  // agility
    {  98, "Quick Attack",  0,  40, 100, 30,  1, EFF_NONE,   0 },  // quickattack
    {  99, "Rage",  0,  20, 100, 20,  0, EFF_RAGE,   0 },  // rage
    { 100, "Teleport", 13,   0,   0, 20, -6, EFF_NONE,   0 },  // teleport
    { 101, "Night Shade",  8,   0, 100, 15,  0, EFF_LEVEL_DMG,   0 },  // nightshade
    { 102, "Mimic",  0,   0,   0, 10,  0, EFF_MIMIC,   0 },  // mimic
    { 103, "Screech",  0,   0,  85, 40,  0, EFF_DROP_DEF,   0 },  // screech
    { 104, "Double Team",  0,   0,   0, 15,  0, EFF_BOOST_EVA,   0 },  // doubleteam
    { 105, "Recover",  0,   0,   0,  5,  0, EFF_HEAL_HALF,   0 },  // recover
    { 106, "Harden",  0,   0,   0, 30,  0, EFF_BOOST_DEF,   0 },  // harden
    { 107, "Minimize",  0,   0,   0, 10,  0, EFF_BOOST_EVA,   0 },  // minimize
    { 108, "Smokescreen",  0,   0, 100, 20,  0, EFF_DROP_ACC,   0 },  // smokescreen
    { 109, "Confuse Ray",  8,   0, 100, 10,  0, EFF_STATUS_CONFUSE,   0 },  // confuseray
    { 110, "Withdraw", 10,   0,   0, 40,  0, EFF_BOOST_DEF,   0 },  // withdraw
    { 111, "Defense Curl",  0,   0,   0, 40,  0, EFF_BOOST_DEF,   0 },  // defensecurl
    { 112, "Barrier", 13,   0,   0, 20,  0, EFF_BOOST_DEF,   0 },  // barrier
    { 113, "Light Screen", 13,   0,   0, 30,  0, EFF_LIGHT_SCREEN,   0 },  // lightscreen
    { 114, "Haze", 14,   0,   0, 30,  0, EFF_HAZE,   0 },  // haze
    { 115, "Reflect", 13,   0,   0, 20,  0, EFF_REFLECT,   0 },  // reflect
    { 116, "Focus Energy",  0,   0,   0, 30,  0, EFF_FOCUS_ENERGY,   0 },  // focusenergy
    { 117, "Bide",  0,   0,   0, 10,  1, EFF_BIDE,   0 },  // bide
    { 118, "Metronome",  0,   0,   0, 10,  0, EFF_METRONOME,   0 },  // metronome
    { 119, "Mirror Move",  2,   0,   0, 20,  0, EFF_NONE,   0 },  // mirrormove
    { 120, "Self-Destruct",  0, 200, 100,  5,  0, EFF_EXPLODE,   0 },  // selfdestruct
    { 121, "Egg Bomb",  0, 100,  75, 10,  0, EFF_NONE,   0 },  // eggbomb
    { 122, "Lick",  8,  30, 100, 30,  0, EFF_STATUS_PAR,  30 },  // lick
    { 123, "Smog",  3,  30,  70, 20,  0, EFF_STATUS_PSN,  40 },  // smog
    { 124, "Sludge",  3,  65, 100, 20,  0, EFF_STATUS_PSN,  30 },  // sludge
    { 125, "Bone Club",  4,  65,  85, 20,  0, EFF_NONE,  10 },  // boneclub
    { 126, "Fire Blast",  9, 110,  85,  5,  0, EFF_STATUS_BRN,  10 },  // fireblast
    { 127, "Waterfall", 10,  80, 100, 15,  0, EFF_NONE,  20 },  // waterfall
    { 128, "Clamp", 10,  35,  85, 15,  0, EFF_TRAPPING,   0 },  // clamp
    { 129, "Swift",  0,  60,   0, 20,  0, EFF_SWIFT_NEVERMISS,   0 },  // swift
    { 130, "Skull Bash",  0, 130, 100, 10,  0, EFF_CHARGE_TURN,   0 },  // skullbash
    { 131, "Spike Cannon",  0,  20, 100, 15,  0, EFF_MULTI_HIT,   0 },  // spikecannon
    { 132, "Constrict",  0,  10, 100, 35,  0, EFF_NONE,  10 },  // constrict
    { 133, "Amnesia", 13,   0,   0, 20,  0, EFF_BOOST_SPC,   0 },  // amnesia
    { 134, "Kinesis", 13,   0,  80, 15,  0, EFF_DROP_ACC,   0 },  // kinesis
    { 135, "Soft-Boiled",  0,   0,   0,  5,  0, EFF_HEAL_HALF,   0 },  // softboiled
    { 136, "High Jump Kick",  1, 130,  90, 10,  0, EFF_NONE,   0 },  // highjumpkick
    { 137, "Glare",  0,   0, 100, 30,  0, EFF_STATUS_PAR,   0 },  // glare
    { 138, "Dream Eater", 13, 100, 100, 15,  0, EFF_DREAM_EATER,   0 },  // dreameater
    { 139, "Poison Gas",  3,   0,  90, 40,  0, EFF_STATUS_PSN,   0 },  // poisongas
    { 140, "Barrage",  0,  15,  85, 20,  0, EFF_MULTI_HIT,   0 },  // barrage
    { 141, "Leech Life",  7,  80, 100, 10,  0, EFF_DRAIN_HP,   0 },  // leechlife
    { 142, "Lovely Kiss",  0,   0,  75, 10,  0, EFF_STATUS_SLP,   0 },  // lovelykiss
    { 143, "Sky Attack",  2, 140,  90,  5,  0, EFF_CHARGE_TURN,  30 },  // skyattack
    { 144, "Transform",  0,   0,   0, 10,  0, EFF_TRANSFORM,   0 },  // transform
    { 145, "Bubble", 10,  40, 100, 30,  0, EFF_NONE,  10 },  // bubble
    { 146, "Dizzy Punch",  0,  70, 100, 10,  0, EFF_NONE,  20 },  // dizzypunch
    { 147, "Spore", 11,   0, 100, 15,  0, EFF_STATUS_SLP,   0 },  // spore
    { 148, "Flash",  0,   0, 100, 20,  0, EFF_DROP_ACC,   0 },  // flash
    { 149, "Psywave", 13,   0, 100, 15,  0, EFF_PSYWAVE,   0 },  // psywave
    { 150, "Splash",  0,   0,   0, 40,  0, EFF_NONE,   0 },  // splash
    { 151, "Acid Armor",  3,   0,   0, 20,  0, EFF_BOOST_DEF,   0 },  // acidarmor
    { 152, "Crabhammer", 10, 100,  90, 10,  0, EFF_NONE,   0 },  // crabhammer
    { 153, "Explosion",  0, 250, 100,  5,  0, EFF_EXPLODE,   0 },  // explosion
    { 154, "Fury Swipes",  0,  18,  80, 15,  0, EFF_MULTI_HIT,   0 },  // furyswipes
    { 155, "Bonemerang",  4,  50,  90, 10,  0, EFF_DOUBLE_HIT,   0 },  // bonemerang
    { 156, "Rest", 13,   0,   0,  5,  0, EFF_REST,   0 },  // rest
    { 157, "Rock Slide",  5,  75,  90, 10,  0, EFF_NONE,  30 },  // rockslide
    { 158, "Hyper Fang",  0,  80,  90, 15,  0, EFF_FLINCH,  10 },  // hyperfang
    { 159, "Sharpen",  0,   0,   0, 30,  0, EFF_BOOST_ATK,   0 },  // sharpen
    { 160, "Conversion",  0,   0,   0, 30,  0, EFF_CONVERSION,   0 },  // conversion
    { 161, "Tri Attack",  0,  80, 100, 10,  0, EFF_NONE,  20 },  // triattack
    { 162, "Super Fang",  0,   0,  90, 10,  0, EFF_SUPER_FANG,   0 },  // superfang
    { 163, "Slash",  0,  70, 100, 20,  0, EFF_NONE,   0 },  // slash
    { 164, "Substitute",  0,   0,   0, 10,  0, EFF_SUBSTITUTE,   0 },  // substitute
    { 165, "Struggle",  0,  50,   0,  1,  0, EFF_RECOIL,   0 },  // struggle
    { 166, "Sketch",  0,   0,   0,  1,  0, EFF_NONE,   0 },  // sketch
    { 167, "Triple Kick",  1,  10,  90, 10,  0, EFF_NONE,   0 },  // triplekick
    { 168, "Thief", 16,  60, 100, 25,  0, EFF_NONE,   0 },  // thief
    { 169, "Spider Web",  7,   0,   0, 10,  0, EFF_NONE,   0 },  // spiderweb
    { 170, "Mind Reader",  0,   0,   0,  5,  0, EFF_NONE,   0 },  // mindreader
    { 171, "Nightmare",  8,   0, 100, 15,  0, EFF_NONE,   0 },  // nightmare
    { 172, "Flame Wheel",  9,  60, 100, 25,  0, EFF_NONE,   0 },  // flamewheel
    { 173, "Snore",  0,  50, 100, 15,  0, EFF_NONE,   0 },  // snore
    { 174, "Curse",  8,   0,   0, 10,  0, EFF_NONE,   0 },  // curse
    { 175, "Flail",  0,   0, 100, 15,  0, EFF_NONE,   0 },  // flail
    { 176, "Conversion 2",  0,   0,   0, 30,  0, EFF_NONE,   0 },  // conversion2
    { 177, "Aeroblast",  2, 100,  95,  5,  0, EFF_NONE,   0 },  // aeroblast
    { 178, "Cotton Spore", 11,   0, 100, 40,  0, EFF_NONE,   0 },  // cottonspore
    { 179, "Reversal",  1,   0, 100, 15,  0, EFF_NONE,   0 },  // reversal
    { 180, "Spite",  8,   0, 100, 10,  0, EFF_NONE,   0 },  // spite
    { 181, "Powder Snow", 14,  40, 100, 25,  0, EFF_NONE,   0 },  // powdersnow
    { 182, "Protect",  0,   0,   0, 10,  4, EFF_NONE,   0 },  // protect
    { 183, "Mach Punch",  1,  40, 100, 30,  1, EFF_NONE,   0 },  // machpunch
    { 184, "Scary Face",  0,   0, 100, 10,  0, EFF_NONE,   0 },  // scaryface
    { 185, "Feint Attack", 16,  60,   0, 20,  0, EFF_NONE,   0 },  // feintattack
    { 186, "Sweet Kiss",  0,   0,  75, 10,  0, EFF_NONE,   0 },  // sweetkiss
    { 187, "Belly Drum",  0,   0,   0, 10,  0, EFF_NONE,   0 },  // bellydrum
    { 188, "Sludge Bomb",  3,  90, 100, 10,  0, EFF_NONE,   0 },  // sludgebomb
    { 189, "Mud-Slap",  4,  20, 100, 10,  0, EFF_NONE,   0 },  // mudslap
    { 190, "Octazooka", 10,  65,  85, 10,  0, EFF_NONE,   0 },  // octazooka
    { 191, "Spikes",  4,   0,   0, 20,  0, EFF_NONE,   0 },  // spikes
    { 192, "Zap Cannon", 12, 120,  50,  5,  0, EFF_NONE,   0 },  // zapcannon
    { 193, "Foresight",  0,   0,   0, 40,  0, EFF_NONE,   0 },  // foresight
    { 194, "Destiny Bond",  8,   0,   0,  5,  0, EFF_NONE,   0 },  // destinybond
    { 195, "Perish Song",  0,   0,   0,  5,  0, EFF_NONE,   0 },  // perishsong
    { 196, "Icy Wind", 14,  55,  95, 15,  0, EFF_NONE,   0 },  // icywind
    { 197, "Detect",  1,   0,   0,  5,  4, EFF_NONE,   0 },  // detect
    { 198, "Bone Rush",  4,  25,  90, 10,  0, EFF_NONE,   0 },  // bonerush
    { 199, "Lock-On",  0,   0,   0,  5,  0, EFF_NONE,   0 },  // lockon
    { 200, "Outrage", 15, 120, 100, 10,  0, EFF_NONE,   0 },  // outrage
    { 201, "Sandstorm",  5,   0,   0, 10,  0, EFF_NONE,   0 },  // sandstorm
    { 202, "Giga Drain", 11,  75, 100, 10,  0, EFF_NONE,   0 },  // gigadrain
    { 203, "Endure",  0,   0,   0, 10,  4, EFF_NONE,   0 },  // endure
    { 204, "Charm",  0,   0, 100, 20,  0, EFF_NONE,   0 },  // charm
    { 205, "Rollout",  5,  30,  90, 20,  0, EFF_NONE,   0 },  // rollout
    { 206, "False Swipe",  0,  40, 100, 40,  0, EFF_NONE,   0 },  // falseswipe
    { 207, "Swagger",  0,   0,  85, 15,  0, EFF_NONE,   0 },  // swagger
    { 208, "Milk Drink",  0,   0,   0,  5,  0, EFF_NONE,   0 },  // milkdrink
    { 209, "Spark", 12,  65, 100, 20,  0, EFF_NONE,   0 },  // spark
    { 210, "Fury Cutter",  7,  40,  95, 20,  0, EFF_NONE,   0 },  // furycutter
    { 211, "Steel Wing", 17,  70,  90, 25,  0, EFF_NONE,   0 },  // steelwing
    { 212, "Mean Look",  0,   0,   0,  5,  0, EFF_NONE,   0 },  // meanlook
    { 213, "Attract",  0,   0, 100, 15,  0, EFF_NONE,   0 },  // attract
    { 214, "Sleep Talk",  0,   0,   0, 10,  0, EFF_NONE,   0 },  // sleeptalk
    { 215, "Heal Bell",  0,   0,   0,  5,  0, EFF_NONE,   0 },  // healbell
    { 216, "Return",  0,   0, 100, 20,  0, EFF_NONE,   0 },  // return
    { 217, "Present",  0,   0,  90, 15,  0, EFF_NONE,   0 },  // present
    { 218, "Frustration",  0,   0, 100, 20,  0, EFF_NONE,   0 },  // frustration
    { 219, "Safeguard",  0,   0,   0, 25,  0, EFF_NONE,   0 },  // safeguard
    { 220, "Pain Split",  0,   0,   0, 20,  0, EFF_NONE,   0 },  // painsplit
    { 221, "Sacred Fire",  9, 100,  95,  5,  0, EFF_NONE,   0 },  // sacredfire
    { 222, "Magnitude",  4,   0, 100, 30,  0, EFF_NONE,   0 },  // magnitude
    { 223, "Dynamic Punch",  1, 100,  50,  5,  0, EFF_NONE,   0 },  // dynamicpunch
    { 224, "Megahorn",  7, 120,  85, 10,  0, EFF_NONE,   0 },  // megahorn
    { 225, "Dragon Breath", 15,  60, 100, 20,  0, EFF_NONE,   0 },  // dragonbreath
    { 226, "Baton Pass",  0,   0,   0, 40,  0, EFF_NONE,   0 },  // batonpass
    { 227, "Encore",  0,   0, 100,  5,  0, EFF_NONE,   0 },  // encore
    { 228, "Pursuit", 16,  40, 100, 20,  0, EFF_NONE,   0 },  // pursuit
    { 229, "Rapid Spin",  0,  50, 100, 40,  0, EFF_NONE,   0 },  // rapidspin
    { 230, "Sweet Scent",  0,   0, 100, 20,  0, EFF_NONE,   0 },  // sweetscent
    { 231, "Iron Tail", 17, 100,  75, 15,  0, EFF_NONE,   0 },  // irontail
    { 232, "Metal Claw", 17,  50,  95, 35,  0, EFF_NONE,   0 },  // metalclaw
    { 233, "Vital Throw",  1,  70,   0, 10, -1, EFF_NONE,   0 },  // vitalthrow
    { 234, "Morning Sun",  0,   0,   0,  5,  0, EFF_NONE,   0 },  // morningsun
    { 235, "Synthesis", 11,   0,   0,  5,  0, EFF_NONE,   0 },  // synthesis
    { 236, "Moonlight",  0,   0,   0,  5,  0, EFF_NONE,   0 },  // moonlight
    { 237, "Hidden Power",  0,  60, 100, 15,  0, EFF_NONE,   0 },  // hiddenpower
    { 238, "Cross Chop",  1, 100,  80,  5,  0, EFF_NONE,   0 },  // crosschop
    { 239, "Twister", 15,  40, 100, 20,  0, EFF_NONE,   0 },  // twister
    { 240, "Rain Dance", 10,   0,   0,  5,  0, EFF_NONE,   0 },  // raindance
    { 241, "Sunny Day",  9,   0,   0,  5,  0, EFF_NONE,   0 },  // sunnyday
    { 242, "Crunch", 16,  80, 100, 15,  0, EFF_NONE,   0 },  // crunch
    { 243, "Mirror Coat", 13,   0, 100, 20, -5, EFF_NONE,   0 },  // mirrorcoat
    { 244, "Psych Up",  0,   0,   0, 10,  0, EFF_NONE,   0 },  // psychup
    { 245, "Extreme Speed",  0,  80, 100,  5,  2, EFF_NONE,   0 },  // extremespeed
    { 246, "Ancient Power",  5,  60, 100,  5,  0, EFF_NONE,   0 },  // ancientpower
    { 247, "Shadow Ball",  8,  80, 100, 15,  0, EFF_NONE,   0 },  // shadowball
    { 248, "Future Sight", 13, 120, 100, 10,  0, EFF_NONE,   0 },  // futuresight
    { 249, "Rock Smash",  1,  40, 100, 15,  0, EFF_NONE,   0 },  // rocksmash
    { 250, "Whirlpool", 10,  35,  85, 15,  0, EFF_NONE,   0 },  // whirlpool
    { 251, "Beat Up", 16,   0, 100, 10,  0, EFF_NONE,   0 },  // beatup
    { 252, "Fake Out",  0,  40, 100, 10,  3, EFF_NONE,   0 },  // fakeout
    { 253, "Uproar",  0,  90, 100, 10,  0, EFF_NONE,   0 },  // uproar
    { 254, "Stockpile",  0,   0,   0, 20,  0, EFF_NONE,   0 },  // stockpile
    { 255, "Spit Up",  0,   0, 100, 10,  0, EFF_NONE,   0 },  // spitup
    { 256, "Swallow",  0,   0,   0, 10,  0, EFF_NONE,   0 },  // swallow
    { 257, "Heat Wave",  9,  95,  90, 10,  0, EFF_NONE,   0 },  // heatwave
    { 258, "Hail", 14,   0,   0, 10,  0, EFF_NONE,   0 },  // hail
    { 259, "Torment", 16,   0, 100, 15,  0, EFF_NONE,   0 },  // torment
    { 260, "Flatter", 16,   0, 100, 15,  0, EFF_NONE,   0 },  // flatter
    { 261, "Will-O-Wisp",  9,   0,  85, 15,  0, EFF_NONE,   0 },  // willowisp
    { 262, "Memento", 16,   0, 100, 10,  0, EFF_NONE,   0 },  // memento
    { 263, "Facade",  0,  70, 100, 20,  0, EFF_NONE,   0 },  // facade
    { 264, "Focus Punch",  1, 150, 100, 20, -3, EFF_NONE,   0 },  // focuspunch
    { 265, "Smelling Salts",  0,  70, 100, 10,  0, EFF_NONE,   0 },  // smellingsalts
    { 266, "Follow Me",  0,   0,   0, 20,  2, EFF_NONE,   0 },  // followme
    { 267, "Nature Power",  0,   0,   0, 20,  0, EFF_NONE,   0 },  // naturepower
    { 268, "Charge", 12,   0,   0, 20,  0, EFF_NONE,   0 },  // charge
    { 269, "Taunt", 16,   0, 100, 20,  0, EFF_NONE,   0 },  // taunt
    { 270, "Helping Hand",  0,   0,   0, 20,  5, EFF_NONE,   0 },  // helpinghand
    { 271, "Trick", 13,   0, 100, 10,  0, EFF_NONE,   0 },  // trick
    { 272, "Role Play", 13,   0,   0, 10,  0, EFF_NONE,   0 },  // roleplay
    { 273, "Wish",  0,   0,   0, 10,  0, EFF_NONE,   0 },  // wish
    { 274, "Assist",  0,   0,   0, 20,  0, EFF_NONE,   0 },  // assist
    { 275, "Ingrain", 11,   0,   0, 20,  0, EFF_NONE,   0 },  // ingrain
    { 276, "Superpower",  1, 120, 100,  5,  0, EFF_NONE,   0 },  // superpower
    { 277, "Magic Coat", 13,   0,   0, 15,  4, EFF_NONE,   0 },  // magiccoat
    { 278, "Recycle",  0,   0,   0, 10,  0, EFF_NONE,   0 },  // recycle
    { 279, "Revenge",  1,  60, 100, 10, -4, EFF_NONE,   0 },  // revenge
    { 280, "Brick Break",  1,  75, 100, 15,  0, EFF_NONE,   0 },  // brickbreak
    { 281, "Yawn",  0,   0,   0, 10,  0, EFF_NONE,   0 },  // yawn
    { 282, "Knock Off", 16,  65, 100, 20,  0, EFF_NONE,   0 },  // knockoff
    { 283, "Endeavor",  0,   0, 100,  5,  0, EFF_NONE,   0 },  // endeavor
    { 284, "Eruption",  9, 150, 100,  5,  0, EFF_NONE,   0 },  // eruption
    { 285, "Skill Swap", 13,   0,   0, 10,  0, EFF_NONE,   0 },  // skillswap
    { 286, "Imprison", 13,   0,   0, 10,  0, EFF_NONE,   0 },  // imprison
    { 287, "Refresh",  0,   0,   0, 20,  0, EFF_NONE,   0 },  // refresh
    { 288, "Grudge",  8,   0,   0,  5,  0, EFF_NONE,   0 },  // grudge
    { 289, "Snatch", 16,   0,   0, 10,  4, EFF_NONE,   0 },  // snatch
    { 290, "Secret Power",  0,  70, 100, 20,  0, EFF_NONE,   0 },  // secretpower
    { 291, "Dive", 10,  80, 100, 10,  0, EFF_NONE,   0 },  // dive
    { 292, "Arm Thrust",  1,  15, 100, 20,  0, EFF_NONE,   0 },  // armthrust
    { 293, "Camouflage",  0,   0,   0, 20,  0, EFF_NONE,   0 },  // camouflage
    { 294, "Tail Glow",  7,   0,   0, 20,  0, EFF_NONE,   0 },  // tailglow
    { 295, "Luster Purge", 13,  95, 100,  5,  0, EFF_NONE,   0 },  // lusterpurge
    { 296, "Mist Ball", 13,  95, 100,  5,  0, EFF_NONE,   0 },  // mistball
    { 297, "Feather Dance",  2,   0, 100, 15,  0, EFF_NONE,   0 },  // featherdance
    { 298, "Teeter Dance",  0,   0, 100, 20,  0, EFF_NONE,   0 },  // teeterdance
    { 299, "Blaze Kick",  9,  85,  90, 10,  0, EFF_NONE,   0 },  // blazekick
    { 300, "Mud Sport",  4,   0,   0, 15,  0, EFF_NONE,   0 },  // mudsport
    { 301, "Ice Ball", 14,  30,  90, 20,  0, EFF_NONE,   0 },  // iceball
    { 302, "Needle Arm", 11,  60, 100, 15,  0, EFF_NONE,   0 },  // needlearm
    { 303, "Slack Off",  0,   0,   0,  5,  0, EFF_NONE,   0 },  // slackoff
    { 304, "Hyper Voice",  0,  90, 100, 10,  0, EFF_NONE,   0 },  // hypervoice
    { 305, "Poison Fang",  3,  50, 100, 15,  0, EFF_NONE,   0 },  // poisonfang
    { 306, "Crush Claw",  0,  75,  95, 10,  0, EFF_NONE,   0 },  // crushclaw
    { 307, "Blast Burn",  9, 150,  90,  5,  0, EFF_NONE,   0 },  // blastburn
    { 308, "Hydro Cannon", 10, 150,  90,  5,  0, EFF_NONE,   0 },  // hydrocannon
    { 309, "Meteor Mash", 17,  90,  90, 10,  0, EFF_NONE,   0 },  // meteormash
    { 310, "Astonish",  8,  30, 100, 15,  0, EFF_NONE,   0 },  // astonish
    { 311, "Weather Ball",  0,  50, 100, 10,  0, EFF_NONE,   0 },  // weatherball
    { 312, "Aromatherapy", 11,   0,   0,  5,  0, EFF_NONE,   0 },  // aromatherapy
    { 313, "Fake Tears", 16,   0, 100, 20,  0, EFF_NONE,   0 },  // faketears
    { 314, "Air Cutter",  2,  60,  95, 25,  0, EFF_NONE,   0 },  // aircutter
    { 315, "Overheat",  9, 130,  90,  5,  0, EFF_NONE,   0 },  // overheat
    { 316, "Odor Sleuth",  0,   0,   0, 40,  0, EFF_NONE,   0 },  // odorsleuth
    { 317, "Rock Tomb",  5,  60,  95, 15,  0, EFF_NONE,   0 },  // rocktomb
    { 318, "Silver Wind",  7,  60, 100,  5,  0, EFF_NONE,   0 },  // silverwind
    { 319, "Metal Sound", 17,   0,  85, 40,  0, EFF_NONE,   0 },  // metalsound
    { 320, "Grass Whistle", 11,   0,  55, 15,  0, EFF_NONE,   0 },  // grasswhistle
    { 321, "Tickle",  0,   0, 100, 20,  0, EFF_NONE,   0 },  // tickle
    { 322, "Cosmic Power", 13,   0,   0, 20,  0, EFF_NONE,   0 },  // cosmicpower
    { 323, "Water Spout", 10, 150, 100,  5,  0, EFF_NONE,   0 },  // waterspout
    { 324, "Signal Beam",  7,  75, 100, 15,  0, EFF_NONE,   0 },  // signalbeam
    { 325, "Shadow Punch",  8,  60,   0, 20,  0, EFF_NONE,   0 },  // shadowpunch
    { 326, "Extrasensory", 13,  80, 100, 20,  0, EFF_NONE,   0 },  // extrasensory
    { 327, "Sky Uppercut",  1,  85,  90, 15,  0, EFF_NONE,   0 },  // skyuppercut
    { 328, "Sand Tomb",  4,  35,  85, 15,  0, EFF_NONE,   0 },  // sandtomb
    { 329, "Sheer Cold", 14,   0,  30,  5,  0, EFF_NONE,   0 },  // sheercold
    { 330, "Muddy Water", 10,  90,  85, 10,  0, EFF_NONE,   0 },  // muddywater
    { 331, "Bullet Seed", 11,  25, 100, 30,  0, EFF_NONE,   0 },  // bulletseed
    { 332, "Aerial Ace",  2,  60,   0, 20,  0, EFF_NONE,   0 },  // aerialace
    { 333, "Icicle Spear", 14,  25, 100, 30,  0, EFF_NONE,   0 },  // iciclespear
    { 334, "Iron Defense", 17,   0,   0, 15,  0, EFF_NONE,   0 },  // irondefense
    { 335, "Block",  0,   0,   0,  5,  0, EFF_NONE,   0 },  // block
    { 336, "Howl",  0,   0,   0, 40,  0, EFF_NONE,   0 },  // howl
    { 337, "Dragon Claw", 15,  80, 100, 15,  0, EFF_NONE,   0 },  // dragonclaw
    { 338, "Frenzy Plant", 11, 150,  90,  5,  0, EFF_NONE,   0 },  // frenzyplant
    { 339, "Bulk Up",  1,   0,   0, 20,  0, EFF_NONE,   0 },  // bulkup
    { 340, "Bounce",  2,  85,  85,  5,  0, EFF_NONE,   0 },  // bounce
    { 341, "Mud Shot",  4,  55,  95, 15,  0, EFF_NONE,   0 },  // mudshot
    { 342, "Poison Tail",  3,  50, 100, 25,  0, EFF_NONE,   0 },  // poisontail
    { 343, "Covet",  0,  60, 100, 25,  0, EFF_NONE,   0 },  // covet
    { 344, "Volt Tackle", 12, 120, 100, 15,  0, EFF_NONE,   0 },  // volttackle
    { 345, "Magical Leaf", 11,  60,   0, 20,  0, EFF_NONE,   0 },  // magicalleaf
    { 346, "Water Sport", 10,   0,   0, 15,  0, EFF_NONE,   0 },  // watersport
    { 347, "Calm Mind", 13,   0,   0, 20,  0, EFF_NONE,   0 },  // calmmind
    { 348, "Leaf Blade", 11,  90, 100, 15,  0, EFF_NONE,   0 },  // leafblade
    { 349, "Dragon Dance", 15,   0,   0, 20,  0, EFF_NONE,   0 },  // dragondance
    { 350, "Rock Blast",  5,  25,  90, 10,  0, EFF_NONE,   0 },  // rockblast
    { 351, "Shock Wave", 12,  60,   0, 20,  0, EFF_NONE,   0 },  // shockwave
    { 352, "Water Pulse", 10,  60, 100, 20,  0, EFF_NONE,   0 },  // waterpulse
    { 353, "Doom Desire", 17, 140, 100,  5,  0, EFF_NONE,   0 },  // doomdesire
    { 354, "Psycho Boost", 13, 140,  90,  5,  0, EFF_NONE,   0 },  // psychoboost
};
static constexpr uint16_t GEN3_MOVE_COUNT = 354;

inline const Gen1MoveData *gen3Move(uint16_t num) {
    for (uint16_t i = 0; i < GEN3_MOVE_COUNT; ++i)
        if (GEN3_MOVES[i].num == num) return &GEN3_MOVES[i];
    return nullptr;
}
