#pragma once
#include <Arduino.h>

// ── PokeMesh BattleLink wire protocol ────────────────────────────────────────
// Hard budget: 200 bytes per LoRa packet (empirical SX1262 reliability limit).
// All multi-byte integers are big-endian.
//
// Every packet:  [ type:1 | sessionHi:1 | sessionLo:1 | seq:1 | payload:0-196 ]
//
// session_id is a 16-bit value generated by the MASTER device at connection
// time (XOR of both chip IDs, lower 16 bits).
// seq wraps at 255 — used to detect duplicates / out-of-order packets.

static constexpr uint8_t BATTLELINK_PROTOCOL_VERSION = 1;
static constexpr uint8_t BATTLELINK_MAX_PKT           = 200;
static constexpr uint8_t BATTLELINK_HDR_SIZE          = 4;    // type+sessionHi+sessionLo+seq
static constexpr uint8_t BATTLELINK_MAX_PAYLOAD       = BATTLELINK_MAX_PKT - BATTLELINK_HDR_SIZE; // 196

// ── Packet type codes ─────────────────────────────────────────────────────────
enum class PktType : uint8_t {
    // ── Connection management (session_id = 0 until established) ──────────
    BATTLE_REQUEST  = 0x10,   // broadcast: "I want to battle; chipId[4]"
    BATTLE_ACCEPT   = 0x11,   // unicast: "Accepted; chipId[4]"
    BATTLE_REJECT   = 0x12,   // unicast: "Declined"
    BATTLE_CANCEL   = 0x13,   // either side: disconnect / abort

    // ── Serial byte relay ─────────────────────────────────────────────────
    // Payload: count:1 then count bytes of raw GB serial data.
    // Batched at SERIAL_BATCH_MS intervals; both sides relay symmetrically.
    SERIAL_DATA     = 0x20,

    // ── Keepalive ─────────────────────────────────────────────────────────
    PING            = 0x30,
    PONG            = 0x31,

    // ── Lobby (peer-to-peer matchmaking) ─────────────────────────────────
    LOBBY_BEACON    = 0x40,   // broadcast: name + party + ELO
    LOBBY_CHALLENGE = 0x41,   // unicast: "I challenge you"
    LOBBY_ACCEPT    = 0x42,   // unicast: "Challenge accepted"
    LOBBY_REJECT    = 0x43,   // unicast: "Challenge declined"

    // ── Tournament (coordinator + client) ───────────────────────────────
    TOURNAMENT_ANNOUNCE      = 0x50,  // coordinator → broadcast: tournament info
    TOURNAMENT_REGISTER      = 0x51,  // player → coordinator: join request
    TOURNAMENT_REGISTER_ACK  = 0x52,  // coordinator → player: registration result
    TOURNAMENT_BRACKET       = 0x53,  // coordinator → broadcast: bracket state
    TOURNAMENT_MATCH_ASSIGN  = 0x54,  // coordinator → both players: your match
    TOURNAMENT_RESULT        = 0x55,  // player → coordinator: match result
    TOURNAMENT_RESULT_ACK    = 0x56,  // coordinator → player: result confirmed
    TOURNAMENT_STATUS        = 0x57,  // coordinator → broadcast: round/phase info
    TOURNAMENT_COMPLETE      = 0x58,  // coordinator → broadcast: winner announcement
};

// ── BATTLE_REQUEST / BATTLE_ACCEPT payload layout ────────────────────────────
// Bytes 0-3: sender's ESP32 chip ID (uint32_t big-endian)
// The device with the HIGHER chip ID becomes the battle MASTER (drives serial
// clock; feeds 0x01 handshake byte to the game).
static constexpr uint8_t BPKT_CHIPID_OFFSET = 0;
static constexpr uint8_t BPKT_CHIPID_LEN    = 4;

// ── SERIAL_DATA payload layout ────────────────────────────────────────────────
// Byte 0:   count (1–195, number of serial bytes in this packet)
// Bytes 1+: serial bytes (raw GB link cable byte stream)
static constexpr uint8_t SERIAL_DATA_MAX    = BATTLELINK_MAX_PAYLOAD - 1; // 195

// ── PING/PONG payload ─────────────────────────────────────────────────────────
// Byte 0: timestamp echo (low byte of millis()) — for rough RTT estimate

// ── Generic packet structure ──────────────────────────────────────────────────
// Use build / parse helpers below rather than constructing directly.
#pragma pack(push, 1)
struct BattlePacket {
    uint8_t  type;          // PktType
    uint8_t  sessionHi;     // session_id high byte
    uint8_t  sessionLo;     // session_id low byte
    uint8_t  seq;           // wrapping 0-255 sequence counter
    uint8_t  payload[BATTLELINK_MAX_PAYLOAD];

    uint16_t sessionId() const {
        return ((uint16_t)sessionHi << 8) | sessionLo;
    }
    void setSessionId(uint16_t id) {
        sessionHi = (id >> 8) & 0xFF;
        sessionLo = id & 0xFF;
    }
};
#pragma pack(pop)
static_assert(sizeof(BattlePacket) == BATTLELINK_MAX_PKT,
              "BattlePacket must be exactly 200 bytes");

// ── Serial batch budget ───────────────────────────────────────────────────────
// Collect serialTx bytes for this long, then send as one SERIAL_DATA packet.
// 50ms ≈ 3 emulated frames; a full Gen-1 turn exchange (~60 bytes) fits easily.
static constexpr uint32_t SERIAL_BATCH_MS = 50;

// How often to (re-)broadcast BATTLE_REQUEST while advertising
static constexpr uint32_t BATTLE_REQUEST_INTERVAL_MS = 3000;

// Session timeout: cancel if no packet received in this long
static constexpr uint32_t BATTLE_TIMEOUT_MS = 30000;
