#!/usr/bin/env python3
"""Generate src/shared/Gen1Learnsets.h from pret/pokered learnset data.

Sources (vendored in scripts/data/pokered/, from github.com/pret/pokered):
  - move_constants.asm : move name -> move ID (sequential const_def)
  - evos_moves.asm     : per-species level-up learnsets, in Gen 1
                         internal-index order (pointer table order)

The internal-index -> Pokedex mapping is parsed out of
src/shared/DaycareSavPatcher.h (internalToDex) so there is a single
source of truth in the repo.

Usage: python3 scripts/gen_learnsets.py
Writes: src/shared/Gen1Learnsets.h
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "scripts" / "data" / "pokered"
OUT = ROOT / "src" / "shared" / "Gen1Learnsets.h"
PATCHER = ROOT / "src" / "shared" / "DaycareSavPatcher.h"


def parse_move_ids():
    ids, next_id = {}, None
    for line in (DATA / "move_constants.asm").read_text().splitlines():
        line = line.split(";")[0].strip()
        if line == "const_def":
            next_id = 0
        elif line.startswith("const ") and next_id is not None:
            ids[line.split()[1]] = next_id
            next_id += 1
        elif line.startswith("const_def "):
            next_id = int(line.split()[1])
    return ids


def parse_internal_to_dex():
    src = PATCHER.read_text()
    m = re.search(r"internalToDex\[256\] = \{(.*?)\};", src, re.S)
    nums = [int(x) for x in re.findall(r"\d+", re.sub(r"//.*", "", m.group(1)))]
    assert len(nums) == 256, f"expected 256 entries, got {len(nums)}"
    return nums


def parse_learnsets(move_ids):
    """Return {internal_index: [(level, move_id), ...]} (level-up moves only)."""
    src = (DATA / "evos_moves.asm").read_text()

    # Pointer table gives internal-index order (1-based)
    table = re.search(r"EvosMovesPointerTable:(.*?)(?:\n\n|\Z)", src, re.S).group(1)
    labels = re.findall(r"dw (\w+)", table)

    learnsets = {}
    for idx, label in enumerate(labels, start=1):
        m = re.search(rf"^{label}:\n(.*?)(?=^\w+:|\Z)", src, re.S | re.M)
        if not m:
            continue
        body, in_learnset, moves = m.group(1), False, []
        for line in body.splitlines():
            line = line.split(";")[0].strip()
            if not line.startswith("db "):
                continue
            fields = [f.strip() for f in line[3:].split(",")]
            if fields == ["0"]:
                if in_learnset:
                    break  # end of learnset
                in_learnset = True  # end of evolutions
                continue
            if in_learnset:
                level, move = int(fields[0]), fields[1]
                moves.append((level, move_ids[move]))
        if moves:
            learnsets[idx] = moves
    return learnsets


def main():
    move_ids = parse_move_ids()
    internal_to_dex = parse_internal_to_dex()
    by_internal = parse_learnsets(move_ids)

    by_dex = {}
    for internal, moves in by_internal.items():
        dex = internal_to_dex[internal]
        if dex:
            by_dex[dex] = sorted(moves)

    flat, offsets, counts = [], [0] * 152, [0] * 152
    for dex in range(1, 152):
        moves = by_dex.get(dex, [])
        offsets[dex] = len(flat)
        counts[dex] = len(moves)
        flat.extend(moves)

    with open(OUT, "w") as f:
        f.write(
            "#pragma once\n"
            "// ── Gen 1 (Red/Blue) level-up learnsets ────────────────────────────────────\n"
            "// GENERATED by scripts/gen_learnsets.py from pret/pokered evos_moves.asm.\n"
            "// Do not edit by hand — rerun the script instead.\n"
            "//\n"
            "// Indexed by Pokedex number (1-151). Level-up moves only (no TM/HM),\n"
            "// sorted by level ascending. Move IDs match showdown_gen1_moves.h.\n"
            "\n"
            "#include \"platform.h\"\n"
            "\n"
            "struct Gen1LearnEntry {\n"
            "    uint8_t level;\n"
            "    uint8_t moveId;\n"
            "};\n"
            "\n"
            f"static const Gen1LearnEntry gen1LearnsetData[{len(flat)}] = {{\n"
        )
        i = 0
        for dex in range(1, 152):
            if counts[dex] == 0:
                continue
            entries = ", ".join(f"{{{l},{m}}}" for l, m in flat[offsets[dex]:offsets[dex] + counts[dex]])
            f.write(f"    {entries},  // {dex}\n")
            i += counts[dex]
        f.write(
            "};\n"
            "\n"
            "static const uint16_t gen1LearnsetOffset[152] = {\n    "
            + ", ".join(str(o) for o in offsets)
            + "\n};\n"
            "\n"
            "static const uint8_t gen1LearnsetCount[152] = {\n    "
            + ", ".join(str(c) for c in counts)
            + "\n};\n"
            "\n"
            "// Moves learned when growing from fromLevel (exclusive) to toLevel\n"
            "// (inclusive). Writes up to maxOut move IDs into out; returns count.\n"
            "static inline uint8_t gen1MovesLearnedBetween(uint8_t dexNum, uint8_t fromLevel,\n"
            "                                              uint8_t toLevel, uint8_t *out,\n"
            "                                              uint8_t maxOut) {\n"
            "    if (dexNum == 0 || dexNum > 151) return 0;\n"
            "    uint8_t n = 0;\n"
            "    const Gen1LearnEntry *e = &gen1LearnsetData[gen1LearnsetOffset[dexNum]];\n"
            "    for (uint8_t i = 0; i < gen1LearnsetCount[dexNum] && n < maxOut; i++) {\n"
            "        if (e[i].level > fromLevel && e[i].level <= toLevel) out[n++] = e[i].moveId;\n"
            "    }\n"
            "    return n;\n"
            "}\n"
        )
    total = sum(counts)
    print(f"wrote {OUT} ({total} learnset entries, {len(by_dex)} species)")


if __name__ == "__main__":
    main()
