#!/usr/bin/env python3
"""Merge the per-dex-range daycare event JSON (crafted from the Pokedex) into
DaycareSpeciesEvents.h for both the firmware and Pi trees.

Input : /tmp/daycare_events/events_*.json  (each: {"dex": [6 strings], ...})
Output: meshtastic-firmware/src/modules/monstermesh/DaycareSpeciesEvents.h
        monster_mesh_pi/src/shared/DaycareSpeciesEvents.h   (byte-identical)

Each event line is a present-tense day-care vignette authored from the species'
real Pokedex biology/behavior/habitat/moves/trivia, with a single %s for the
boarded Pokemon's display name. ASCII-only (the mesh drops invalid UTF-8).
"""
import json, os, glob, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
INDIR = "/tmp/daycare_events"
OUTS = [
    os.path.join(REPO, "meshtastic-firmware", "src", "modules", "monstermesh",
                 "DaycareSpeciesEvents.h"),
    os.path.join(REPO, "monster_mesh_pi", "src", "shared", "DaycareSpeciesEvents.h"),
]
MAXDEX = 386


def cesc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def load():
    merged = {}
    files = sorted(glob.glob(os.path.join(INDIR, "*.json")))
    if not files:
        sys.exit(f"ERROR: no events_*.json in {INDIR}")
    for f in files:
        d = json.load(open(f))
        for k, v in d.items():
            merged[int(k)] = v
    return merged


def main():
    ev = load()
    missing = [d for d in range(1, MAXDEX + 1) if d not in ev or not ev[d]]
    if missing:
        print(f"WARNING: {len(missing)} species missing events: {missing[:20]}...",
              file=sys.stderr)

    # Flat pool + per-species span.
    pool = []
    spans = [(0, 0)] * (MAXDEX + 1)  # index 0 unused
    for dex in range(1, MAXDEX + 1):
        lines = ev.get(dex, [])
        # sanity: enforce single %s and ASCII
        clean = []
        for ln in lines:
            ln = ln.encode("ascii", "ignore").decode("ascii")
            if ln.count("%s") != 1:      # skip malformed (no/too-many placeholders)
                if ln.count("%s") == 0:
                    continue
                # collapse extra %s to the first
                first = ln.find("%s")
                ln = ln[:first + 2] + ln[first + 2:].replace("%s", "it")
            if len(ln) > 160:
                ln = ln[:157].rsplit(" ", 1)[0] + "..."
            clean.append(ln)
        off = len(pool)
        spans[dex] = (off, len(clean))
        pool.extend(clean)

    L = []
    L.append("#pragma once")
    L.append("#include <stdint.h>")
    L.append("// AUTO-GENERATED by scripts/gen_daycare_events.py — DO NOT EDIT.")
    L.append("// Per-species day-care event vignettes, dex 1-386, authored from the")
    L.append("// Pokedex (biology/behavior/habitat/moves/trivia). %s = boarded Pokemon.")
    L.append("")
    L.append(f"static const char *const kDaycareEventPool[{len(pool)}] = {{")
    for i, s in enumerate(pool):
        L.append(f'    "{cesc(s)}",')
    L.append("};")
    L.append(f"static constexpr uint16_t DAYCARE_EVENT_POOL_COUNT = {len(pool)};")
    L.append("")
    L.append("struct DaycareEventSpan { uint16_t off; uint8_t cnt; };")
    L.append(f"static const DaycareEventSpan kDaycareEventSpan[{MAXDEX + 1}] = {{")
    for dex in range(0, MAXDEX + 1):
        off, cnt = spans[dex]
        tag = "unused" if dex == 0 else str(dex)
        L.append(f"    {{ {off}, {cnt} }},  // {tag}")
    L.append("};")
    L.append("")
    L.append("// Event `which` (0..cnt-1) for a species; nullptr if none/out of range.")
    L.append("static inline const char *daycareSpeciesEvent(uint16_t dex, uint8_t which) {")
    L.append("    if (dex < 1 || dex > 386) return nullptr;")
    L.append("    const DaycareEventSpan &s = kDaycareEventSpan[dex];")
    L.append("    if (s.cnt == 0 || which >= s.cnt) return nullptr;")
    L.append("    return kDaycareEventPool[s.off + which];")
    L.append("}")
    L.append("static inline uint8_t daycareSpeciesEventCount(uint16_t dex) {")
    L.append("    return (dex >= 1 && dex <= 386) ? kDaycareEventSpan[dex].cnt : 0;")
    L.append("}")
    L.append("")
    text = "\n".join(L)

    for path in OUTS:
        open(path, "w").write(text)
    print(f"pool={len(pool)} events across {sum(1 for d in range(1,MAXDEX+1) if spans[d][1])} species")
    print(f"header ~{len(text)//1024} KB -> both trees")


if __name__ == "__main__":
    main()
