#!/usr/bin/env python3
"""Merge per-dex-range SOCIAL event JSON into DaycareSocialEvents.h (both trees).

Social vignettes describe the local Pokemon interacting with ANOTHER Pokemon on
the mesh. Each line has EXACTLY two %s: first = local Pokemon name, second =
partner name. The on-device caller does snprintf(msg, fmt, localName, partner).

Input : /tmp/daycare_social/*.json   {"dex": [6 strings], ...}
Output: meshtastic-firmware/src/modules/monstermesh/DaycareSocialEvents.h
        monster_mesh_pi/src/shared/DaycareSocialEvents.h   (byte-identical)
"""
import json, os, glob, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
INDIR = "/tmp/daycare_social"
OUTS = [
    os.path.join(REPO, "meshtastic-firmware", "src", "modules", "monstermesh",
                 "DaycareSocialEvents.h"),
    os.path.join(REPO, "monster_mesh_pi", "src", "shared", "DaycareSocialEvents.h"),
]
MAXDEX = 386


def cesc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def load():
    merged = {}
    for f in sorted(glob.glob(os.path.join(INDIR, "*.json"))):
        try:
            d = json.load(open(f))
        except Exception as e:
            print(f"skip {f}: {e}", file=sys.stderr); continue
        for k, v in d.items():
            merged[int(k)] = v
    if not merged:
        sys.exit(f"ERROR: no social JSON in {INDIR}")
    return merged


def main():
    ev = load()
    pool, spans = [], [(0, 0)] * (MAXDEX + 1)
    dropped = 0
    for dex in range(1, MAXDEX + 1):
        clean = []
        for ln in ev.get(dex, []):
            ln = ln.encode("ascii", "ignore").decode("ascii")
            if ln.count("%s") != 2:      # social lines MUST have exactly 2 (local, partner)
                dropped += 1; continue
            if len(ln) > 160:
                ln = ln[:157].rsplit(" ", 1)[0] + "..."
            clean.append(ln)
        spans[dex] = (len(pool), len(clean))
        pool.extend(clean)
    if dropped:
        print(f"WARNING: dropped {dropped} social lines without exactly two %s", file=sys.stderr)

    L = ["#pragma once", "#include <stdint.h>",
         "// AUTO-GENERATED by scripts/gen_daycare_social.py -- DO NOT EDIT.",
         "// Per-species SOCIAL vignettes (dex 1-386): local Pokemon interacts with",
         "// another Pokemon on the mesh. Two %s: (1) local name, (2) partner name.",
         "",
         f"static const char *const kDaycareSocialPool[{len(pool)}] = {{"]
    L += [f'    "{cesc(s)}",' for s in pool]
    L += ["};",
          f"static constexpr uint16_t DAYCARE_SOCIAL_POOL_COUNT = {len(pool)};",
          "",
          "struct DaycareSocialSpan { uint16_t off; uint8_t cnt; };",
          f"static const DaycareSocialSpan kDaycareSocialSpan[{MAXDEX + 1}] = {{"]
    for dex in range(0, MAXDEX + 1):
        off, cnt = spans[dex]
        L.append(f"    {{ {off}, {cnt} }},  // {'unused' if dex == 0 else dex}")
    L += ["};",
          "",
          "// Social line `which` for a species; a format string with two %s",
          "// (local name, partner name). nullptr if none/out of range.",
          "static inline const char *daycareSocialEvent(uint16_t dex, uint8_t which) {",
          "    if (dex < 1 || dex > 386) return nullptr;",
          "    const DaycareSocialSpan &s = kDaycareSocialSpan[dex];",
          "    if (s.cnt == 0 || which >= s.cnt) return nullptr;",
          "    return kDaycareSocialPool[s.off + which];",
          "}",
          "static inline uint8_t daycareSocialEventCount(uint16_t dex) {",
          "    return (dex >= 1 && dex <= 386) ? kDaycareSocialSpan[dex].cnt : 0;",
          "}",
          ""]
    text = "\n".join(L)
    for p in OUTS:
        open(p, "w").write(text)
    have = sum(1 for d in range(1, MAXDEX + 1) if spans[d][1])
    print(f"social pool={len(pool)} across {have} species; header ~{len(text)//1024} KB -> both trees")


if __name__ == "__main__":
    main()
