#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""
gen_gauntlet.py — pack the gauntlet's tunable data (E4 teams, type-default
movesets) from a JSON spec into a C++ header that the gauntlet module
includes.

Usage:
    python3 scripts/gen_gauntlet.py data/gauntlet.json \
        > src/modules/monstermesh/gauntlet/GauntletDataPacked.h

Falls back to the hardcoded constants in GauntletBattle.cpp if you don't
include the packed header (no #include = use built-in defaults).

JSON shape:
{
  "elite_four": [
    { "name": "Lorelei",
      "party": [
        {"dex": 87,  "level": 52, "moves": [55, 58, 59, 145]},
        ...
      ]
    },
    ... 4 entries total
  ],
  "default_moves": {
    "fire":     [52, 53, 126, 7],
    "water":    [55, 57, 56, 145],
    ...
  }
}

Move IDs come from src/modules/monstermesh/showdown_gen1_moves.h
(GEN1_MOVES table). Dex numbers are 1..151 (Gen 1 only).

This script does NOT validate that the move IDs match the species' learnsets
— that's a runtime concern; the engine accepts any move on any mon and the
gauntlet stays balanced because both sides face the same auto-resolve rules.
"""

import argparse
import json
import sys
import textwrap
from datetime import datetime, timezone

GEN1_TYPES = [
    "normal", "fighting", "flying", "poison", "ground", "rock", "bird",
    "bug", "ghost", "fire", "water", "grass", "electric", "psychic",
    "ice", "dragon",
]


def fail(msg: str) -> None:
    print(f"gen_gauntlet: error: {msg}", file=sys.stderr)
    sys.exit(2)


def validate(spec: dict) -> None:
    e4 = spec.get("elite_four", [])
    if not isinstance(e4, list) or len(e4) != 4:
        fail("elite_four must be a list of exactly 4 trainers")
    for i, t in enumerate(e4):
        if "name" not in t:
            fail(f"elite_four[{i}] missing name")
        if not isinstance(t.get("party"), list):
            fail(f"elite_four[{i}] missing party list")
        if len(t["party"]) > 6:
            fail(f"elite_four[{i}] party has more than 6 mons")
        for j, m in enumerate(t["party"]):
            for k in ("dex", "level"):
                if k not in m:
                    fail(f"elite_four[{i}].party[{j}] missing {k}")
            if not (1 <= m["dex"] <= 151):
                fail(f"elite_four[{i}].party[{j}].dex out of range")
            if not (1 <= m["level"] <= 100):
                fail(f"elite_four[{i}].party[{j}].level out of range")
            mv = m.get("moves", [0, 0, 0, 0])
            if len(mv) != 4:
                fail(f"elite_four[{i}].party[{j}].moves must have 4 entries")
            for x in mv:
                if not (0 <= x <= 165):
                    fail(f"elite_four[{i}].party[{j}].moves: id {x} out of range")

    dm = spec.get("default_moves", {})
    if dm and not isinstance(dm, dict):
        fail("default_moves must be a dict keyed by Gen1 type name")
    for k, v in dm.items():
        if k.startswith("_"):
            continue   # comment key
        if k.lower() not in GEN1_TYPES:
            fail(f"default_moves: unknown type '{k}'")
        if not isinstance(v, list) or len(v) != 4:
            fail(f"default_moves.{k} must be a 4-element move-id array")


def emit(spec: dict, out=sys.stdout) -> None:
    when = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    out.write(textwrap.dedent(f"""\
        // SPDX-License-Identifier: MIT
        // Auto-generated by scripts/gen_gauntlet.py — DO NOT EDIT BY HAND.
        // Regenerate with: python3 scripts/gen_gauntlet.py data/gauntlet.json > this-file
        // Generated: {when}
        //
        // Drop-in override for the hardcoded E4 + default-move tables in
        // GauntletBattle.cpp. Include this header from GauntletBattle.cpp's
        // top to override the defaults.

        #pragma once
        #include <stdint.h>

        struct GauntletPackedMon {{
            uint8_t dex; uint8_t level; uint8_t moves[4];
        }};

        struct GauntletPackedE4 {{
            const char *name;
            GauntletPackedMon party[6];   // unused slots: dex==0
        }};

        """))

    # Emit E4 array
    e4 = spec["elite_four"]
    out.write("static const GauntletPackedE4 GAUNTLET_E4_PACKED[4] = {\n")
    for tr in e4:
        name = tr["name"].replace("\\", "\\\\").replace('"', '\\"')
        out.write(f'    {{ "{name}", {{\n')
        party = tr["party"][:6]
        # Pad to 6
        while len(party) < 6:
            party.append({"dex": 0, "level": 0, "moves": [0, 0, 0, 0]})
        for m in party:
            mv = m.get("moves", [0, 0, 0, 0])
            out.write(
                f"        {{ {m['dex']:3d}, {m['level']:3d}, "
                f"{{ {mv[0]:3d}, {mv[1]:3d}, {mv[2]:3d}, {mv[3]:3d} }} }},\n"
            )
        out.write("    }},\n")
    out.write("};\n\n")

    # Emit default-moves table (16 types)
    dm = spec.get("default_moves", {})
    out.write("static const uint8_t GAUNTLET_DEFAULT_MOVES_PACKED[16][4] = {\n")
    for ty in GEN1_TYPES:
        moves = dm.get(ty) or dm.get(ty.upper()) or [33, 33, 33, 33]  # Tackle×4 fallback
        out.write(
            f"    /* {ty:<8s} */ {{ {moves[0]:3d}, {moves[1]:3d}, "
            f"{moves[2]:3d}, {moves[3]:3d} }},\n"
        )
    out.write("};\n")


def main() -> int:
    ap = argparse.ArgumentParser(description="Pack gauntlet config into a header.")
    ap.add_argument("spec", help="Path to gauntlet JSON spec")
    ap.add_argument("-o", "--output", default=None,
                     help="Output header path (default: stdout)")
    args = ap.parse_args()

    try:
        with open(args.spec) as f:
            spec = json.load(f)
    except FileNotFoundError:
        fail(f"spec file not found: {args.spec}")
    except json.JSONDecodeError as e:
        fail(f"spec is not valid JSON: {e}")

    validate(spec)
    if args.output:
        with open(args.output, "w") as f:
            emit(spec, f)
    else:
        emit(spec)
    return 0


if __name__ == "__main__":
    sys.exit(main())
