#pragma once
// AUTO-GENERATED by scripts/gen_daycare_data.py — DO NOT EDIT
// Source: offline Gen 1-3 pokedex dump (Bulbapedia / PokeAPI)

#include <Arduino.h>

// ── Pokemon types ───────────────────────────────────────
enum PkmnType : uint8_t {
    TYPE_NORMAL = 0,
    TYPE_FIGHTING = 1,
    TYPE_FLYING = 2,
    TYPE_POISON = 3,
    TYPE_GROUND = 4,
    TYPE_ROCK = 5,
    TYPE_BUG = 6,
    TYPE_GHOST = 7,
    TYPE_FIRE = 8,
    TYPE_WATER = 9,
    TYPE_GRASS = 10,
    TYPE_ELECTRIC = 11,
    TYPE_PSYCHIC = 12,
    TYPE_ICE = 13,
    TYPE_DRAGON = 14,
    TYPE_DARK = 15,
    TYPE_STEEL = 16,
    TYPE_COUNT = 17
};

enum PkmnHabitat : uint8_t {
    HABITAT_CAVE = 0,
    HABITAT_FOREST = 1,
    HABITAT_GRASSLAND = 2,
    HABITAT_MOUNTAIN = 3,
    HABITAT_RARE = 4,
    HABITAT_ROUGH_TERRAIN = 5,
    HABITAT_SEA = 6,
    HABITAT_URBAN = 7,
    HABITAT_WATERS_EDGE = 8,
    HABITAT_COUNT = 9
};

enum PkmnPersonality : uint8_t {
    PERS_PROUD = 0,
    PERS_CLUMSY = 1,
    PERS_AGGRESSIVE = 2,
    PERS_GENTLE = 3,
    PERS_SNEAKY = 4,
    PERS_LAZY = 5,
    PERS_ANXIOUS = 6,
    PERS_COUNT = 7
};

enum StatBias : uint8_t {
    BIAS_HP = 0, BIAS_ATK = 1, BIAS_DEF = 2, BIAS_SPA = 3, BIAS_SPD = 4
};

// ── Species profile ─────────────────────────────────────
struct DaycareSpecies {
    uint16_t dexNum;
    uint8_t type1;
    uint8_t type2;
    uint8_t habitat;
    uint8_t statBias;
    uint8_t personality;
    uint8_t evoStage;
    uint8_t moveCount;
    uint16_t moves[15];
    uint16_t flavorIdx;     // index into daycareFlavorFragments (0-385)     // index into daycareFlavorFragments[]
};

// ── Move names (Gen 1-3, 354 moves) ────────────────────
static const char *const daycareMoveNames[] = {
    "???",  // 0 (unused)
    "Pound",  // 1
    "Karate Chop",  // 2
    "Double Slap",  // 3
    "Comet Punch",  // 4
    "Mega Punch",  // 5
    "Pay Day",  // 6
    "Fire Punch",  // 7
    "Ice Punch",  // 8
    "Thunder Punch",  // 9
    "Scratch",  // 10
    "Vice Grip",  // 11
    "Guillotine",  // 12
    "Razor Wind",  // 13
    "Swords Dance",  // 14
    "Cut",  // 15
    "Gust",  // 16
    "Wing Attack",  // 17
    "Whirlwind",  // 18
    "Fly",  // 19
    "Bind",  // 20
    "Slam",  // 21
    "Vine Whip",  // 22
    "Stomp",  // 23
    "Double Kick",  // 24
    "Mega Kick",  // 25
    "Jump Kick",  // 26
    "Rolling Kick",  // 27
    "Sand Attack",  // 28
    "Headbutt",  // 29
    "Horn Attack",  // 30
    "Fury Attack",  // 31
    "Horn Drill",  // 32
    "Tackle",  // 33
    "Body Slam",  // 34
    "Wrap",  // 35
    "Take Down",  // 36
    "Thrash",  // 37
    "Double Edge",  // 38
    "Tail Whip",  // 39
    "Poison Sting",  // 40
    "Twineedle",  // 41
    "Pin Missile",  // 42
    "Leer",  // 43
    "Bite",  // 44
    "Growl",  // 45
    "Roar",  // 46
    "Sing",  // 47
    "Supersonic",  // 48
    "Sonic Boom",  // 49
    "Disable",  // 50
    "Acid",  // 51
    "Ember",  // 52
    "Flamethrower",  // 53
    "Mist",  // 54
    "Water Gun",  // 55
    "Hydro Pump",  // 56
    "Surf",  // 57
    "Ice Beam",  // 58
    "Blizzard",  // 59
    "Psybeam",  // 60
    "Bubble Beam",  // 61
    "Aurora Beam",  // 62
    "Hyper Beam",  // 63
    "Peck",  // 64
    "Drill Peck",  // 65
    "Submission",  // 66
    "Low Kick",  // 67
    "Counter",  // 68
    "Seismic Toss",  // 69
    "Strength",  // 70
    "Absorb",  // 71
    "Mega Drain",  // 72
    "Leech Seed",  // 73
    "Growth",  // 74
    "Razor Leaf",  // 75
    "Solar Beam",  // 76
    "Poison Powder",  // 77
    "Stun Spore",  // 78
    "Sleep Powder",  // 79
    "Petal Dance",  // 80
    "String Shot",  // 81
    "Dragon Rage",  // 82
    "Fire Spin",  // 83
    "Thunder Shock",  // 84
    "Thunderbolt",  // 85
    "Thunder Wave",  // 86
    "Thunder",  // 87
    "Rock Throw",  // 88
    "Earthquake",  // 89
    "Fissure",  // 90
    "Dig",  // 91
    "Toxic",  // 92
    "Confusion",  // 93
    "Psychic",  // 94
    "Hypnosis",  // 95
    "Meditate",  // 96
    "Agility",  // 97
    "Quick Attack",  // 98
    "Rage",  // 99
    "Teleport",  // 100
    "Night Shade",  // 101
    "Mimic",  // 102
    "Screech",  // 103
    "Double Team",  // 104
    "Recover",  // 105
    "Harden",  // 106
    "Minimize",  // 107
    "Smokescreen",  // 108
    "Confuse Ray",  // 109
    "Withdraw",  // 110
    "Defense Curl",  // 111
    "Barrier",  // 112
    "Light Screen",  // 113
    "Haze",  // 114
    "Reflect",  // 115
    "Focus Energy",  // 116
    "Bide",  // 117
    "Metronome",  // 118
    "Mirror Move",  // 119
    "Self Destruct",  // 120
    "Egg Bomb",  // 121
    "Lick",  // 122
    "Smog",  // 123
    "Sludge",  // 124
    "Bone Club",  // 125
    "Fire Blast",  // 126
    "Waterfall",  // 127
    "Clamp",  // 128
    "Swift",  // 129
    "Skull Bash",  // 130
    "Spike Cannon",  // 131
    "Constrict",  // 132
    "Amnesia",  // 133
    "Kinesis",  // 134
    "Soft Boiled",  // 135
    "High Jump Kick",  // 136
    "Glare",  // 137
    "Dream Eater",  // 138
    "Poison Gas",  // 139
    "Barrage",  // 140
    "Leech Life",  // 141
    "Lovely Kiss",  // 142
    "Sky Attack",  // 143
    "Transform",  // 144
    "Bubble",  // 145
    "Dizzy Punch",  // 146
    "Spore",  // 147
    "Flash",  // 148
    "Psywave",  // 149
    "Splash",  // 150
    "Acid Armor",  // 151
    "Crabhammer",  // 152
    "Explosion",  // 153
    "Fury Swipes",  // 154
    "Bonemerang",  // 155
    "Rest",  // 156
    "Rock Slide",  // 157
    "Hyper Fang",  // 158
    "Sharpen",  // 159
    "Conversion",  // 160
    "Tri Attack",  // 161
    "Super Fang",  // 162
    "Slash",  // 163
    "Substitute",  // 164
    "Struggle",  // 165
    "Sketch",  // 166
    "Triple Kick",  // 167
    "Thief",  // 168
    "Spider Web",  // 169
    "Mind Reader",  // 170
    "Nightmare",  // 171
    "Flame Wheel",  // 172
    "Snore",  // 173
    "Curse",  // 174
    "Flail",  // 175
    "Conversion 2",  // 176
    "Aeroblast",  // 177
    "Cotton Spore",  // 178
    "Reversal",  // 179
    "Spite",  // 180
    "Powder Snow",  // 181
    "Protect",  // 182
    "Mach Punch",  // 183
    "Scary Face",  // 184
    "Feint Attack",  // 185
    "Sweet Kiss",  // 186
    "Belly Drum",  // 187
    "Sludge Bomb",  // 188
    "Mud Slap",  // 189
    "Octazooka",  // 190
    "Spikes",  // 191
    "Zap Cannon",  // 192
    "Foresight",  // 193
    "Destiny Bond",  // 194
    "Perish Song",  // 195
    "Icy Wind",  // 196
    "Detect",  // 197
    "Bone Rush",  // 198
    "Lock On",  // 199
    "Outrage",  // 200
    "Sandstorm",  // 201
    "Giga Drain",  // 202
    "Endure",  // 203
    "Charm",  // 204
    "Rollout",  // 205
    "False Swipe",  // 206
    "Swagger",  // 207
    "Milk Drink",  // 208
    "Spark",  // 209
    "Fury Cutter",  // 210
    "Steel Wing",  // 211
    "Mean Look",  // 212
    "Attract",  // 213
    "Sleep Talk",  // 214
    "Heal Bell",  // 215
    "Return",  // 216
    "Present",  // 217
    "Frustration",  // 218
    "Safeguard",  // 219
    "Pain Split",  // 220
    "Sacred Fire",  // 221
    "Magnitude",  // 222
    "Dynamic Punch",  // 223
    "Megahorn",  // 224
    "Dragon Breath",  // 225
    "Baton Pass",  // 226
    "Encore",  // 227
    "Pursuit",  // 228
    "Rapid Spin",  // 229
    "Sweet Scent",  // 230
    "Iron Tail",  // 231
    "Metal Claw",  // 232
    "Vital Throw",  // 233
    "Morning Sun",  // 234
    "Synthesis",  // 235
    "Moonlight",  // 236
    "Hidden Power",  // 237
    "Cross Chop",  // 238
    "Twister",  // 239
    "Rain Dance",  // 240
    "Sunny Day",  // 241
    "Crunch",  // 242
    "Mirror Coat",  // 243
    "Psych Up",  // 244
    "Extreme Speed",  // 245
    "Ancient Power",  // 246
    "Shadow Ball",  // 247
    "Future Sight",  // 248
    "Rock Smash",  // 249
    "Whirlpool",  // 250
    "Beat Up",  // 251
    "Fake Out",  // 252
    "Uproar",  // 253
    "Stockpile",  // 254
    "Spit Up",  // 255
    "Swallow",  // 256
    "Heat Wave",  // 257
    "Hail",  // 258
    "Torment",  // 259
    "Flatter",  // 260
    "Will O Wisp",  // 261
    "Memento",  // 262
    "Facade",  // 263
    "Focus Punch",  // 264
    "Smelling Salts",  // 265
    "Follow Me",  // 266
    "Nature Power",  // 267
    "Charge",  // 268
    "Taunt",  // 269
    "Helping Hand",  // 270
    "Trick",  // 271
    "Role Play",  // 272
    "Wish",  // 273
    "Assist",  // 274
    "Ingrain",  // 275
    "Superpower",  // 276
    "Magic Coat",  // 277
    "Recycle",  // 278
    "Revenge",  // 279
    "Brick Break",  // 280
    "Yawn",  // 281
    "Knock Off",  // 282
    "Endeavor",  // 283
    "Eruption",  // 284
    "Skill Swap",  // 285
    "Imprison",  // 286
    "Refresh",  // 287
    "Grudge",  // 288
    "Snatch",  // 289
    "Secret Power",  // 290
    "Dive",  // 291
    "Arm Thrust",  // 292
    "Camouflage",  // 293
    "Tail Glow",  // 294
    "Luster Purge",  // 295
    "Mist Ball",  // 296
    "Feather Dance",  // 297
    "Teeter Dance",  // 298
    "Blaze Kick",  // 299
    "Mud Sport",  // 300
    "Ice Ball",  // 301
    "Needle Arm",  // 302
    "Slack Off",  // 303
    "Hyper Voice",  // 304
    "Poison Fang",  // 305
    "Crush Claw",  // 306
    "Blast Burn",  // 307
    "Hydro Cannon",  // 308
    "Meteor Mash",  // 309
    "Astonish",  // 310
    "Weather Ball",  // 311
    "Aromatherapy",  // 312
    "Fake Tears",  // 313
    "Air Cutter",  // 314
    "Overheat",  // 315
    "Odor Sleuth",  // 316
    "Rock Tomb",  // 317
    "Silver Wind",  // 318
    "Metal Sound",  // 319
    "Grass Whistle",  // 320
    "Tickle",  // 321
    "Cosmic Power",  // 322
    "Water Spout",  // 323
    "Signal Beam",  // 324
    "Shadow Punch",  // 325
    "Extrasensory",  // 326
    "Sky Uppercut",  // 327
    "Sand Tomb",  // 328
    "Sheer Cold",  // 329
    "Muddy Water",  // 330
    "Bullet Seed",  // 331
    "Aerial Ace",  // 332
    "Icicle Spear",  // 333
    "Iron Defense",  // 334
    "Block",  // 335
    "Howl",  // 336
    "Dragon Claw",  // 337
    "Frenzy Plant",  // 338
    "Bulk Up",  // 339
    "Bounce",  // 340
    "Mud Shot",  // 341
    "Poison Tail",  // 342
    "Covet",  // 343
    "Volt Tackle",  // 344
    "Magical Leaf",  // 345
    "Water Sport",  // 346
    "Calm Mind",  // 347
    "Leaf Blade",  // 348
    "Dragon Dance",  // 349
    "Rock Blast",  // 350
    "Shock Wave",  // 351
    "Water Pulse",  // 352
    "Doom Desire",  // 353
    "Psycho Boost",  // 354
};
static constexpr uint16_t DAYCARE_MOVE_COUNT = 354;

// ── Species display names (Pokedex order 1-386) ─────────
static const char *const daycareSpeciesNames[] = {
    "???",  // 0 (unused)
    "Bulbasaur",  // 1
    "Ivysaur",  // 2
    "Venusaur",  // 3
    "Charmander",  // 4
    "Charmeleon",  // 5
    "Charizard",  // 6
    "Squirtle",  // 7
    "Wartortle",  // 8
    "Blastoise",  // 9
    "Caterpie",  // 10
    "Metapod",  // 11
    "Butterfree",  // 12
    "Weedle",  // 13
    "Kakuna",  // 14
    "Beedrill",  // 15
    "Pidgey",  // 16
    "Pidgeotto",  // 17
    "Pidgeot",  // 18
    "Rattata",  // 19
    "Raticate",  // 20
    "Spearow",  // 21
    "Fearow",  // 22
    "Ekans",  // 23
    "Arbok",  // 24
    "Pikachu",  // 25
    "Raichu",  // 26
    "Sandshrew",  // 27
    "Sandslash",  // 28
    "Nidoran F",  // 29
    "Nidorina",  // 30
    "Nidoqueen",  // 31
    "Nidoran M",  // 32
    "Nidorino",  // 33
    "Nidoking",  // 34
    "Clefairy",  // 35
    "Clefable",  // 36
    "Vulpix",  // 37
    "Ninetales",  // 38
    "Jigglypuff",  // 39
    "Wigglytuff",  // 40
    "Zubat",  // 41
    "Golbat",  // 42
    "Oddish",  // 43
    "Gloom",  // 44
    "Vileplume",  // 45
    "Paras",  // 46
    "Parasect",  // 47
    "Venonat",  // 48
    "Venomoth",  // 49
    "Diglett",  // 50
    "Dugtrio",  // 51
    "Meowth",  // 52
    "Persian",  // 53
    "Psyduck",  // 54
    "Golduck",  // 55
    "Mankey",  // 56
    "Primeape",  // 57
    "Growlithe",  // 58
    "Arcanine",  // 59
    "Poliwag",  // 60
    "Poliwhirl",  // 61
    "Poliwrath",  // 62
    "Abra",  // 63
    "Kadabra",  // 64
    "Alakazam",  // 65
    "Machop",  // 66
    "Machoke",  // 67
    "Machamp",  // 68
    "Bellsprout",  // 69
    "Weepinbell",  // 70
    "Victreebel",  // 71
    "Tentacool",  // 72
    "Tentacruel",  // 73
    "Geodude",  // 74
    "Graveler",  // 75
    "Golem",  // 76
    "Ponyta",  // 77
    "Rapidash",  // 78
    "Slowpoke",  // 79
    "Slowbro",  // 80
    "Magnemite",  // 81
    "Magneton",  // 82
    "Farfetch'd",  // 83
    "Doduo",  // 84
    "Dodrio",  // 85
    "Seel",  // 86
    "Dewgong",  // 87
    "Grimer",  // 88
    "Muk",  // 89
    "Shellder",  // 90
    "Cloyster",  // 91
    "Gastly",  // 92
    "Haunter",  // 93
    "Gengar",  // 94
    "Onix",  // 95
    "Drowzee",  // 96
    "Hypno",  // 97
    "Krabby",  // 98
    "Kingler",  // 99
    "Voltorb",  // 100
    "Electrode",  // 101
    "Exeggcute",  // 102
    "Exeggutor",  // 103
    "Cubone",  // 104
    "Marowak",  // 105
    "Hitmonlee",  // 106
    "Hitmonchan",  // 107
    "Lickitung",  // 108
    "Koffing",  // 109
    "Weezing",  // 110
    "Rhyhorn",  // 111
    "Rhydon",  // 112
    "Chansey",  // 113
    "Tangela",  // 114
    "Kangaskhan",  // 115
    "Horsea",  // 116
    "Seadra",  // 117
    "Goldeen",  // 118
    "Seaking",  // 119
    "Staryu",  // 120
    "Starmie",  // 121
    "Mr. Mime",  // 122
    "Scyther",  // 123
    "Jynx",  // 124
    "Electabuzz",  // 125
    "Magmar",  // 126
    "Pinsir",  // 127
    "Tauros",  // 128
    "Magikarp",  // 129
    "Gyarados",  // 130
    "Lapras",  // 131
    "Ditto",  // 132
    "Eevee",  // 133
    "Vaporeon",  // 134
    "Jolteon",  // 135
    "Flareon",  // 136
    "Porygon",  // 137
    "Omanyte",  // 138
    "Omastar",  // 139
    "Kabuto",  // 140
    "Kabutops",  // 141
    "Aerodactyl",  // 142
    "Snorlax",  // 143
    "Articuno",  // 144
    "Zapdos",  // 145
    "Moltres",  // 146
    "Dratini",  // 147
    "Dragonair",  // 148
    "Dragonite",  // 149
    "Mewtwo",  // 150
    "Mew",  // 151
    "Chikorita",  // 152
    "Bayleef",  // 153
    "Meganium",  // 154
    "Cyndaquil",  // 155
    "Quilava",  // 156
    "Typhlosion",  // 157
    "Totodile",  // 158
    "Croconaw",  // 159
    "Feraligatr",  // 160
    "Sentret",  // 161
    "Furret",  // 162
    "Hoothoot",  // 163
    "Noctowl",  // 164
    "Ledyba",  // 165
    "Ledian",  // 166
    "Spinarak",  // 167
    "Ariados",  // 168
    "Crobat",  // 169
    "Chinchou",  // 170
    "Lanturn",  // 171
    "Pichu",  // 172
    "Cleffa",  // 173
    "Igglybuff",  // 174
    "Togepi",  // 175
    "Togetic",  // 176
    "Natu",  // 177
    "Xatu",  // 178
    "Mareep",  // 179
    "Flaaffy",  // 180
    "Ampharos",  // 181
    "Bellossom",  // 182
    "Marill",  // 183
    "Azumarill",  // 184
    "Sudowoodo",  // 185
    "Politoed",  // 186
    "Hoppip",  // 187
    "Skiploom",  // 188
    "Jumpluff",  // 189
    "Aipom",  // 190
    "Sunkern",  // 191
    "Sunflora",  // 192
    "Yanma",  // 193
    "Wooper",  // 194
    "Quagsire",  // 195
    "Espeon",  // 196
    "Umbreon",  // 197
    "Murkrow",  // 198
    "Slowking",  // 199
    "Misdreavus",  // 200
    "Unown",  // 201
    "Wobbuffet",  // 202
    "Girafarig",  // 203
    "Pineco",  // 204
    "Forretress",  // 205
    "Dunsparce",  // 206
    "Gligar",  // 207
    "Steelix",  // 208
    "Snubbull",  // 209
    "Granbull",  // 210
    "Qwilfish",  // 211
    "Scizor",  // 212
    "Shuckle",  // 213
    "Heracross",  // 214
    "Sneasel",  // 215
    "Teddiursa",  // 216
    "Ursaring",  // 217
    "Slugma",  // 218
    "Magcargo",  // 219
    "Swinub",  // 220
    "Piloswine",  // 221
    "Corsola",  // 222
    "Remoraid",  // 223
    "Octillery",  // 224
    "Delibird",  // 225
    "Mantine",  // 226
    "Skarmory",  // 227
    "Houndour",  // 228
    "Houndoom",  // 229
    "Kingdra",  // 230
    "Phanpy",  // 231
    "Donphan",  // 232
    "Porygon2",  // 233
    "Stantler",  // 234
    "Smeargle",  // 235
    "Tyrogue",  // 236
    "Hitmontop",  // 237
    "Smoochum",  // 238
    "Elekid",  // 239
    "Magby",  // 240
    "Miltank",  // 241
    "Blissey",  // 242
    "Raikou",  // 243
    "Entei",  // 244
    "Suicune",  // 245
    "Larvitar",  // 246
    "Pupitar",  // 247
    "Tyranitar",  // 248
    "Lugia",  // 249
    "Ho-Oh",  // 250
    "Celebi",  // 251
    "Treecko",  // 252
    "Grovyle",  // 253
    "Sceptile",  // 254
    "Torchic",  // 255
    "Combusken",  // 256
    "Blaziken",  // 257
    "Mudkip",  // 258
    "Marshtomp",  // 259
    "Swampert",  // 260
    "Poochyena",  // 261
    "Mightyena",  // 262
    "Zigzagoon",  // 263
    "Linoone",  // 264
    "Wurmple",  // 265
    "Silcoon",  // 266
    "Beautifly",  // 267
    "Cascoon",  // 268
    "Dustox",  // 269
    "Lotad",  // 270
    "Lombre",  // 271
    "Ludicolo",  // 272
    "Seedot",  // 273
    "Nuzleaf",  // 274
    "Shiftry",  // 275
    "Taillow",  // 276
    "Swellow",  // 277
    "Wingull",  // 278
    "Pelipper",  // 279
    "Ralts",  // 280
    "Kirlia",  // 281
    "Gardevoir",  // 282
    "Surskit",  // 283
    "Masquerain",  // 284
    "Shroomish",  // 285
    "Breloom",  // 286
    "Slakoth",  // 287
    "Vigoroth",  // 288
    "Slaking",  // 289
    "Nincada",  // 290
    "Ninjask",  // 291
    "Shedinja",  // 292
    "Whismur",  // 293
    "Loudred",  // 294
    "Exploud",  // 295
    "Makuhita",  // 296
    "Hariyama",  // 297
    "Azurill",  // 298
    "Nosepass",  // 299
    "Skitty",  // 300
    "Delcatty",  // 301
    "Sableye",  // 302
    "Mawile",  // 303
    "Aron",  // 304
    "Lairon",  // 305
    "Aggron",  // 306
    "Meditite",  // 307
    "Medicham",  // 308
    "Electrike",  // 309
    "Manectric",  // 310
    "Plusle",  // 311
    "Minun",  // 312
    "Volbeat",  // 313
    "Illumise",  // 314
    "Roselia",  // 315
    "Gulpin",  // 316
    "Swalot",  // 317
    "Carvanha",  // 318
    "Sharpedo",  // 319
    "Wailmer",  // 320
    "Wailord",  // 321
    "Numel",  // 322
    "Camerupt",  // 323
    "Torkoal",  // 324
    "Spoink",  // 325
    "Grumpig",  // 326
    "Spinda",  // 327
    "Trapinch",  // 328
    "Vibrava",  // 329
    "Flygon",  // 330
    "Cacnea",  // 331
    "Cacturne",  // 332
    "Swablu",  // 333
    "Altaria",  // 334
    "Zangoose",  // 335
    "Seviper",  // 336
    "Lunatone",  // 337
    "Solrock",  // 338
    "Barboach",  // 339
    "Whiscash",  // 340
    "Corphish",  // 341
    "Crawdaunt",  // 342
    "Baltoy",  // 343
    "Claydol",  // 344
    "Lileep",  // 345
    "Cradily",  // 346
    "Anorith",  // 347
    "Armaldo",  // 348
    "Feebas",  // 349
    "Milotic",  // 350
    "Castform",  // 351
    "Kecleon",  // 352
    "Shuppet",  // 353
    "Banette",  // 354
    "Duskull",  // 355
    "Dusclops",  // 356
    "Tropius",  // 357
    "Chimecho",  // 358
    "Absol",  // 359
    "Wynaut",  // 360
    "Snorunt",  // 361
    "Glalie",  // 362
    "Spheal",  // 363
    "Sealeo",  // 364
    "Walrein",  // 365
    "Clamperl",  // 366
    "Huntail",  // 367
    "Gorebyss",  // 368
    "Relicanth",  // 369
    "Luvdisc",  // 370
    "Bagon",  // 371
    "Shelgon",  // 372
    "Salamence",  // 373
    "Beldum",  // 374
    "Metang",  // 375
    "Metagross",  // 376
    "Regirock",  // 377
    "Regice",  // 378
    "Registeel",  // 379
    "Latias",  // 380
    "Latios",  // 381
    "Kyogre",  // 382
    "Groudon",  // 383
    "Rayquaza",  // 384
    "Jirachi",  // 385
    "Deoxys",  // 386
};

// ── Flavor fragments (keywords from Pokedex entries) ────────
static const char *const daycareFlavorFragments[] = {
    "strange|seed|planted|birth|plant",  // 0: Bulbasaur
    "bulb|grows|large|appears|lose",  // 1: Ivysaur
    "plant|blooms|absorbing|solar|energy",  // 2: Venusaur
    "obviously|prefers|hot|places|rains",  // 3: Charmander
    "swings|burning|tail|elevates|temperature",  // 4: Charmeleon
    "spits|fire|hot|enough|melt",  // 5: Charizard
    "after|birth|swells|hardens|shell",  // 6: Squirtle
    "often|hides|water|stalk|unwary",  // 7: Wartortle
    "brutal|pressurized|water|jets|shell",  // 8: Blastoise
    "short|feet|tipped|suction|pads",  // 9: Caterpie
    "vulnerable|attack|shell|soft|exposing",  // 10: Metapod
    "battle|flaps|wings|high|speed",  // 11: Butterfree
    "often|found|forests|eating|leaves",  // 12: Weedle
    "almost|incapable|moving|only|harden",  // 13: Kakuna
    "flies|high|speed|attacks|large",  // 14: Beedrill
    "common|sight|forests|woods|flaps",  // 15: Pidgey
    "protective|sprawling|territorial|area|fiercely",  // 16: Pidgeotto
    "hunting|skims|surface|water|high",  // 17: Pidgeot
    "living|wherever|food|available|ceaselessly",  // 18: Rattata
    "whiskers|maintain|balance|apparently|slows",  // 19: Raticate
    "eats|bugs|grassy|areas|flap",  // 20: Spearow
    "huge|magnificent|wings|keep|aloft",  // 21: Fearow
    "moves|silently|stealthily|eats|eggs",  // 22: Ekans
    "rumored|ferocious|warning|markings|belly",  // 23: Arbok
    "several|gather|electricity|build|cause",  // 24: Pikachu
    "long|tail|serves|ground|protect",  // 25: Raichu
    "burrows|deep|underground|arid|locations",  // 26: Sandshrew
    "curls|spiny|ball|threatened|roll",  // 27: Sandslash
    "although|small|venomous|barbs|render",  // 28: Nidoran F
    "female|horn|develops|slowly|prefers",  // 29: Nidorina
    "hard|scales|provide|strong|protection",  // 30: Nidoqueen
    "stiffens|ears|sense|danger|larger",  // 31: Nidoran M
    "aggressive|quick|attack|horn|head",  // 32: Nidorino
    "powerful|tail|battle|smash|constrict",  // 33: Nidoking
    "magical|cute|appeal|admirers|rare",  // 34: Clefairy
    "timid|fairy|rarely|seen|run",  // 35: Clefable
    "time|birth|tail|splits|tip",  // 36: Vulpix
    "smart|vengeful|grabbing|tails|result",  // 37: Ninetales
    "huge|eyes|light|sings|mysteriously",  // 38: Jigglypuff
    "body|soft|rubbery|angered|suck",  // 39: Wigglytuff
    "forms|colonies|perpetually|dark|places",  // 40: Zubat
    "once|strikes|stop|draining|energy",  // 41: Golbat
    "during|day|keeps|face|buried",  // 42: Oddish
    "fluid|oozes|mouth|isn|drool",  // 43: Gloom
    "larger|petals|toxic|pollen|contains",  // 44: Vileplume
    "burrows|suck|tree|roots|mushrooms",  // 45: Paras
    "stays|mostly|dark|damp|places",  // 46: Parasect
    "lives|shadows|tall|trees|eats",  // 47: Venonat
    "dust|scales|covering|wings|color",  // 48: Venomoth
    "lives|yard|underground|feeds|plant",  // 49: Diglett
    "team|diglett|triplets|triggers|huge",  // 50: Dugtrio
    "adores|circular|objects|wanders|streets",  // 51: Meowth
    "although|fur|admirers|tough|raise",  // 52: Persian
    "lulling|enemies|vacant|look|wily",  // 53: Psyduck
    "often|seen|swimming|elegantly|lake",  // 54: Golduck
    "extremely|quick|anger|docile|moment",  // 55: Mankey
    "always|furious|tenacious|boot|abandon",  // 56: Primeape
    "protective|territory|bark|bite|repel",  // 57: Growlithe
    "admired|since|past|beauty|runs",  // 58: Arcanine
    "newly|grown|legs|prevent|running",  // 59: Poliwag
    "capable|living|water|sweats|keep",  // 60: Poliwhirl
    "adept|swimmer|both|front|crawl",  // 61: Poliwrath
    "ability|read|minds|identify|impending",  // 62: Abra
    "emits|special|alpha|waves|body",  // 63: Kadabra
    "brain|outperform|supercomputer|intelligence|quotient",  // 64: Alakazam
    "loves|build|muscles|trains|styles",  // 65: Machop
    "muscular|body|powerful|wear|power",  // 66: Machoke
    "heavy|muscles|throws|powerful|punches",  // 67: Machamp
    "carnivorous|traps|eats|bugs|root",  // 68: Bellsprout
    "spits|poisonpowder|immobilize|enemy|finishes",  // 69: Weepinbell
    "said|live|huge|colonies|deep",  // 70: Victreebel
    "drifts|shallow|seas|anglers|hook",  // 71: Tentacool
    "tentacles|normally|kept|short|hunts",  // 72: Tentacruel
    "found|fields|mountains|mistaking|boulders",  // 73: Geodude
    "rolls|slopes|move|obstacle|without",  // 74: Graveler
    "boulder|body|extremely|hard|easily",  // 75: Golem
    "hooves|times|harder|diamonds|trample",  // 76: Ponyta
    "competitive|chase|anything|moves|fast",  // 77: Rapidash
    "always|absent|minded|won|react",  // 78: Slowpoke
    "shellder|latched|onto|slowpoke|tail",  // 79: Slowbro
    "anti|gravity|stay|suspended|appears",  // 80: Magnemite
    "formed|several|magnemites|linked|together",  // 81: Magneton
    "sprig|green|onions|holds|weapon",  // 82: Farfetch'd
    "bird|poor|flying|fast|foot",  // 83: Doduo
    "brains|execute|complex|plans|heads",  // 84: Dodrio
    "protruding|horn|head|hard|bashing",  // 85: Seel
    "stores|thermal|energy|body|swims",  // 86: Dewgong
    "appears|filthy|areas|thrives|sucking",  // 87: Grimer
    "thickly|covered|filthy|vile|sludge",  // 88: Muk
    "hard|shell|repels|attack|vulnerable",  // 89: Shellder
    "attacked|launches|horns|quick|volleys",  // 90: Cloyster
    "almost|invisible|gaseous|cloaks|target",  // 91: Gastly
    "because|ability|slip|block|walls",  // 92: Haunter
    "full|moon|mimic|shadows|people",  // 93: Gengar
    "grows|stone|portions|body|harden",  // 94: Onix
    "puts|enemies|sleep|eats|dreams",  // 95: Drowzee
    "locks|eyes|enemy|mix|psi",  // 96: Hypno
    "pincers|only|powerful|weapons|balance",  // 97: Krabby
    "large|pincer|crushing|power|however",  // 98: Kingler
    "usually|found|power|plants|easily",  // 99: Voltorb
    "stores|electric|energy|high|pressure",  // 100: Electrode
    "telepathy|only|receive|always|form",  // 101: Exeggcute
    "legend|rare|occasions|heads|drop",  // 102: Exeggutor
    "because|never|removes|skull|helmet",  // 103: Cubone
    "bone|holds|key|weapon|throws",  // 104: Marowak
    "hurry|legs|lengthen|progressively|runs",  // 105: Hitmonlee
    "apparently|doing|nothing|fires|punches",  // 106: Hitmonchan
    "tongue|extended|chameleon|leaves|tingling",  // 107: Lickitung
    "because|stores|several|toxic|gases",  // 108: Koffing
    "poison|gases|meet|koffings|fuse",  // 109: Weezing
    "massive|bones|times|harder|human",  // 110: Rhyhorn
    "protected|armor|hide|capable|living",  // 111: Rhydon
    "rare|elusive|said|bring|happiness",  // 112: Chansey
    "whole|body|swathed|wide|vines",  // 113: Tangela
    "infant|rarely|ventures|mother|protective",  // 114: Kangaskhan
    "known|shoot|flying|bugs|precision",  // 115: Horsea
    "capable|swimming|backwards|rapidly|flapping",  // 116: Seadra
    "tail|fin|billows|elegant|ballroom",  // 117: Goldeen
    "autumn|spawning|season|seen|swimming",  // 118: Seaking
    "enigmatic|effortlessly|regenerate|appendage|loses",  // 119: Staryu
    "central|core|glows|seven|colors",  // 120: Starmie
    "interrupted|miming|slap|offender|broad",  // 121: Mr. Mime
    "ninja|agility|speed|create|illusion",  // 122: Scyther
    "seductively|wiggles|hips|walks|cause",  // 123: Jynx
    "normally|found|power|plants|wander",  // 124: Electabuzz
    "body|always|burns|orange|glow",  // 125: Magmar
    "fails|crush|victim|pincers|swing",  // 126: Pinsir
    "targets|enemy|charges|furiously|whipping",  // 127: Tauros
    "distant|past|somewhat|stronger|horribly",  // 128: Magikarp
    "rarely|seen|wild|huge|vicious",  // 129: Gyarados
    "overhunted|almost|extinction|ferry|people",  // 130: Lapras
    "capable|copying|enemy|genetic|code",  // 131: Ditto
    "genetic|code|irregular|mutate|exposed",  // 132: Eevee
    "lives|close|water|long|tail",  // 133: Vaporeon
    "accumulates|negative|ions|atmosphere|blast",  // 134: Jolteon
    "storing|thermal|energy|body|temperature",  // 135: Flareon
    "consists|entirely|programming|code|capable",  // 136: Porygon
    "although|long|extinct|rare|cases",  // 137: Omanyte
    "prehistoric|died|heavy|shell|impossible",  // 138: Omastar
    "resurrected|fossil|found|once|ocean",  // 139: Kabuto
    "sleek|shape|perfect|swimming|slashes",  // 140: Kabutops
    "ferocious|prehistoric|goes|enemy|throat",  // 141: Aerodactyl
    "lazy|eats|sleeps|rotund|bulk",  // 142: Snorlax
    "legendary|bird|said|appear|doomed",  // 143: Articuno
    "legendary|bird|said|appear|clouds",  // 144: Zapdos
    "known|legendary|bird|fire|every",  // 145: Moltres
    "long|considered|mythical|until|recently",  // 146: Dratini
    "mystical|exudes|gentle|aura|ability",  // 147: Dragonair
    "extremely|rarely|seen|marine|intelligence",  // 148: Dragonite
    "created|scientist|after|years|horrific",  // 149: Mewtwo
    "rare|still|said|mirage|experts",  // 150: Mew
    "sweet|aroma|gently|wafts|leaf",  // 151: Chikorita
    "scent|spices|comes|neck|somehow",  // 152: Bayleef
    "aroma|rises|petals|contains|substance",  // 153: Meganium
    "timid|always|curls|itself|ball",  // 154: Cyndaquil
    "careful|turns|during|battle|means",  // 155: Quilava
    "rage|peaks|becomes|hot|anything",  // 156: Typhlosion
    "well|developed|jaws|powerful|capable",  // 157: Totodile
    "loses|fang|new|grows|place",  // 158: Croconaw
    "bites|massive|powerful|jaws|shakes",  // 159: Feraligatr
    "cautious|raises|itself|tail|better",  // 160: Sentret
    "nest|suit|long|skinny|body",  // 161: Furret
    "always|stands|foot|changes|feet",  // 162: Hoothoot
    "eyes|specially|adapted|concentrate|even",  // 163: Noctowl
    "timid|afraid|move|alone|active",  // 164: Ledyba
    "stars|flicker|night|sky|flutters",  // 165: Ledian
    "lies|still|same|pose|days",  // 166: Spinarak
    "spins|string|only|rear|mouth",  // 167: Ariados
    "flies|silently|dark|four|wings",  // 168: Crobat
    "shoots|positive|negative|electricity|between",  // 169: Chinchou
    "light|emits|bright|illuminate|sea",  // 170: Lanturn
    "yet|skilled|storing|electricity|send",  // 171: Pichu
    "because|unusual|star|silhouette|people",  // 172: Cleffa
    "soft|body|starts|roll|bounce",  // 173: Igglybuff
    "shell|seems|filled|joy|said",  // 174: Togepi
    "say|appear|before|kindhearted|caring",  // 175: Togetic
    "because|wings|aren|yet|fully",  // 176: Natu
    "say|stays|still|quiet|because",  // 177: Xatu
    "static|electricity|builds|body|fleece",  // 178: Mareep
    "result|storing|too|electricity|developed",  // 179: Flaaffy
    "tail|tip|shines|brightly|seen",  // 180: Ampharos
    "gather|times|appear|dance|say",  // 181: Bellossom
    "tip|tail|contains|oil|lighter",  // 182: Marill
    "keeping|still|listening|intently|tell",  // 183: Azumarill
    "although|always|pretends|tree|composition",  // 184: Sudowoodo
    "poliwag|poliwhirl|hear|echoing|cry",  // 185: Politoed
    "keep|blown|wind|gather|clusters",  // 186: Hoppip
    "bloom|top|head|opens|closes",  // 187: Skiploom
    "once|catches|wind|deftly|controls",  // 188: Jumpluff
    "tail|powerful|grab|tree|branch",  // 189: Aipom
    "drop|sky|suddenly|attacked|spearow",  // 190: Sunkern
    "converts|sunlight|energy|darkness|after",  // 191: Sunflora
    "flaps|wings|really|fast|generate",  // 192: Yanma
    "lives|cold|water|leave|search",  // 193: Wooper
    "carefree|easy|going|nature|swimming",  // 194: Quagsire
    "fine|hair|covers|body|sense",  // 195: Espeon
    "agitated|protects|itself|spraying|poisonous",  // 196: Umbreon
    "feared|loathed|believed|bring|misfortune",  // 197: Murkrow
    "incredible|intellect|intuition|whatever|situation",  // 198: Slowking
    "playing|mischievous|tricks|screaming|wailing",  // 199: Misdreavus
    "shapes|look|hieroglyphs|ancient|tablets",  // 200: Unown
    "hates|light|shock|attacked|inflates",  // 201: Wobbuffet
    "tail|small|brain|own|beware",  // 202: Girafarig
    "shell|thicker|adding|layers|tree",  // 203: Pineco
    "entire|body|shielded|steel|hard",  // 204: Forretress
    "spotted|escapes|backward|furiously|boring",  // 205: Dunsparce
    "flies|straight|target|face|clamps",  // 206: Gligar
    "body|compressed|deep|ground|result",  // 207: Steelix
    "although|looks|frightening|actually|affectionate",  // 208: Snubbull
    "actually|timid|easily|spooked|attacked",  // 209: Granbull
    "fire|poison|spikes|inflate|body",  // 210: Qwilfish
    "swings|eye|patterned|pincers|scare",  // 211: Scizor
    "berries|stores|vase|shell|decompose",  // 212: Shuckle
    "powerful|thrusts|prized|horn|enemies",  // 213: Heracross
    "paws|conceal|sharp|claws|attacked",  // 214: Sneasel
    "finds|honey|crescent|mark|glows",  // 215: Teddiursa
    "although|good|climber|prefers|snap",  // 216: Ursaring
    "never|sleeps|keep|moving|because",  // 217: Slugma
    "shell|skin|cooled|hardened|breaks",  // 218: Magcargo
    "rubs|snout|ground|find|dig",  // 219: Swinub
    "although|legs|short|rugged|hooves",  // 220: Piloswine
    "continuously|sheds|grows|tip|head",  // 221: Corsola
    "superb|accuracy|water|shoots|strike",  // 222: Remoraid
    "traps|enemies|suction|cupped|tentacles",  // 223: Octillery
    "carries|food|day|long|tales",  // 224: Delibird
    "majestically|swims|doesn|care|remoraid",  // 225: Mantine
    "sturdy|wings|look|heavy|actually",  // 226: Skarmory
    "different|cries|communicating|pursuing|prey",  // 227: Houndour
    "you|burned|flames|shoots|mouth",  // 228: Houndoom
    "said|usually|hides|underwater|caves",  // 229: Kingdra
    "swings|long|snout|playfully|because",  // 230: Phanpy
    "sharp|hard|tusks|rugged|hide",  // 231: Donphan
    "upgraded|version|designed|space|exploration",  // 232: Porygon2
    "curved|antlers|subtly|change|flow",  // 233: Stantler
    "special|fluid|oozes|tip|tail",  // 234: Smeargle
    "always|bursting|energy|itself|stronger",  // 235: Tyrogue
    "you|become|enchanted|smooth|elegant",  // 236: Hitmontop
    "lips|sensitive|parts|body|always",  // 237: Smoochum
    "rotates|arms|generate|electricity|tires",  // 238: Elekid
    "every|time|inhales|exhales|hot",  // 239: Magby
    "milk|packed|nutrition|making|ultimate",  // 240: Miltank
    "anyone|takes|even|bite|egg",  // 241: Blissey
    "rain|clouds|carries|let|fire",  // 242: Raikou
    "volcanoes|erupt|barks|unable|restrain",  // 243: Entei
    "said|reincarnation|north|winds|instantly",  // 244: Suicune
    "feeds|soil|after|eaten|large",  // 245: Larvitar
    "shell|hard|sheet|rock|strong",  // 246: Pupitar
    "body|harmed|sort|attack|eager",  // 247: Tyranitar
    "said|quietly|spends|time|deep",  // 248: Lugia
    "legends|claim|flies|world|skies",  // 249: Ho-Oh
    "wanders|across|time|grass|trees",  // 250: Celebi
    "small|hooks|bottom|feet|enable",  // 251: Treecko
    "leaves|growing|grovyles|body|convenient",  // 252: Grovyle
    "leaves|growing|sceptiles|body|sharp",  // 253: Sceptile
    "sticks|trainer|following|behind|unsteady",  // 254: Torchic
    "toughens|legs|thighs|running|fields",  // 255: Combusken
    "battle|blows|intense|flames|wrists",  // 256: Blaziken
    "fin|mudkips|head|acts|highly",  // 257: Mudkip
    "surface|marshtomps|body|enveloped|thin",  // 258: Marshtomp
    "strong|enough|power|easily|drag",  // 259: Swampert
    "first|sight|takes|bite|anything",  // 260: Poochyena
    "gives|obvious|signals|preparing|attack",  // 261: Mightyena
    "restlessly|wanders|everywhere|times|because",  // 262: Zigzagoon
    "always|runs|full|speed|only",  // 263: Linoone
    "spikes|rear|end|peels|bark",  // 264: Wurmple
    "tethers|itself|tree|branch|silk",  // 265: Silcoon
    "beautiflys|favorite|food|sweet|pollen",  // 266: Beautifly
    "protective|cocoon|wrapping|body|entirely",  // 267: Cascoon
    "instinctively|drawn|light|swarms|attracted",  // 268: Dustox
    "live|ponds|lakes|float|surface",  // 269: Lotad
    "nocturnal|active|after|dusk|mischief",  // 270: Lombre
    "begins|dancing|soon|hears|cheerful",  // 271: Ludicolo
    "attaches|itself|tree|branch|top",  // 272: Seedot
    "live|densely|overgrown|forests|occasionally",  // 273: Nuzleaf
    "mysterious|said|live|atop|towering",  // 274: Shiftry
    "courageously|stands|ground|against|foes",  // 275: Taillow
    "flies|high|above|our|heads",  // 276: Swellow
    "habit|carrying|prey|valuables|beak",  // 277: Wingull
    "flying|transporter|carries|small|eggs",  // 278: Pelipper
    "senses|emotions|people|horns|head",  // 279: Ralts
    "said|exposed|positive|emotions|trainer",  // 280: Kirlia
    "ability|read|future|senses|impending",  // 281: Gardevoir
    "tips|feet|secretes|oil|enables",  // 282: Surskit
    "intimidates|enemies|eyelike|patterns|antennas",  // 283: Masquerain
    "live|damp|soil|dark|depths",  // 284: Shroomish
    "closes|foe|light|sprightly|footwork",  // 285: Breloom
    "lolls|twenty|hours|every|day",  // 286: Slakoth
    "always|itching|agitated|wild|rampage",  // 287: Vigoroth
    "spends|day|lying|lolling|eats",  // 288: Slaking
    "lives|underground|years|complete|darkness",  // 289: Nincada
    "moves|high|speed|cannot|seen",  // 290: Ninjask
    "shedinjas|hard|body|doesnt|move",  // 291: Shedinja
    "normally|whismurs|voice|quiet|barely",  // 292: Whismur
    "loudreds|bellowing|completely|decimate|wood",  // 293: Loudred
    "triggers|earthquakes|tremors|creates|bellowing",  // 294: Exploud
    "tenacious|keep|getting|attacking|foe",  // 295: Makuhita
    "practices|straight|arm|slaps|number",  // 296: Hariyama
    "spins|tail|lasso|hurls|momentum",  // 297: Azurill
    "nosepasss|magnetic|nose|always|pointed",  // 298: Nosepass
    "habit|becoming|fascinated|moving|objects",  // 299: Skitty
    "prefers|live|unfettered|existence|pleases",  // 300: Delcatty
    "lead|quiet|lives|deep|inside",  // 301: Sableye
    "mawhiles|huge|jaws|actually|steel",  // 302: Mawile
    "body|steel|feeds|iron|ore",  // 303: Aron
    "tempers|steel|body|drinking|highly",  // 304: Lairon
    "claims|entire|mountain|own|territory",  // 305: Aggron
    "undertakes|rigorous|mental|training|deep",  // 306: Meditite
    "said|meditation|heightens|energy|inside",  // 307: Medicham
    "stores|electricity|long|body|hair",  // 308: Electrike
    "constantly|discharging|electricity|mane|sparks",  // 309: Manectric
    "always|acts|cheerleader|partners|whenever",  // 310: Plusle
    "concerned|cheering|partners|own|safety",  // 311: Minun
    "arrival|night|emits|light|tail",  // 312: Volbeat
    "attracts|swarm|volbeat|sweet|fragrance",  // 313: Illumise
    "shoots|sharp|thorns|projectiles|opponent",  // 314: Roselia
    "virtually|gulpins|body|stomach|result",  // 315: Gulpin
    "spots|prey|spurts|hideously|toxic",  // 316: Swalot
    "carvanhas|strongly|developed|jaws|sharply",  // 317: Carvanha
    "nicknamed|bully|sea|widely|feared",  // 318: Sharpedo
    "wailmers|nostrils|located|above|eyes",  // 319: Wailmer
    "largest|identified|now|giant|swims",  // 320: Wailord
    "extremely|dull|witted|doesnt|notice",  // 321: Numel
    "volcano|inside|body|magma|degrees",  // 322: Camerupt
    "digs|mountains|search|coal|finds",  // 323: Torkoal
    "bounces|tail|shock|bouncing|heart",  // 324: Spoink
    "black|pearls|body|amplify|psychic",  // 325: Grumpig
    "exist|world|said|utterly|unique",  // 326: Spinda
    "trapinchs|nest|sloped|bowl|pit",  // 327: Trapinch
    "prey|faint|generates|ultrasonic|waves",  // 328: Vibrava
    "nicknamed|elemental|spirit|desert|because",  // 329: Flygon
    "lives|arid|locations|deserts|releases",  // 330: Cacnea
    "during|daytime|remains|unmoving|lose",  // 331: Cacturne
    "light|fluffy|wings|cottony|clouds",  // 332: Swablu
    "dances|wheels|sky|among|billowing",  // 333: Altaria
    "memories|battling|arch|rival|seviper",  // 334: Zangoose
    "shares|generations|long|feud|zangoose",  // 335: Seviper
    "discovered|location|meteorite|fell|result",  // 336: Lunatone
    "new|species|said|fallen|space",  // 337: Solrock
    "barboachs|sensitive|whiskers|serve|superb",  // 338: Barboach
    "extremely|territorial|claim|large|pond",  // 339: Whiscash
    "originally|foreign|imported|pets|eventually",  // 340: Corphish
    "extremely|violent|nature|compels|challenge",  // 341: Crawdaunt
    "moves|spinning|foot|primitive|wall",  // 342: Baltoy
    "said|dolls|mud|primitive|humans",  // 343: Claydol
    "became|extinct|approximately|hundred|million",  // 344: Lileep
    "roams|ocean|floor|search|food",  // 345: Cradily
    "regenerated|prehistoric|fossil|primitive|once",  // 346: Anorith
    "armaldos|tough|armor|attacks|bounce",  // 347: Armaldo
    "feebass|fins|ragged|tattered|start",  // 348: Feebas
    "breathtakingly|beautiful|see|said|forget",  // 349: Milotic
    "castforms|appearance|changes|weather|gained",  // 350: Castform
    "capable|changing|body|colors|blend",  // 351: Kecleon
    "attracted|feelings|jealousy|vindictiveness|someone",  // 352: Shuppet
    "generates|energy|laying|strong|curses",  // 353: Banette
    "pass|wall|matter|how|thick",  // 354: Duskull
    "dusclopss|body|completely|hollow|nothing",  // 355: Dusclops
    "lives|tropical|jungles|bunch|fruit",  // 356: Tropius
    "cries|echo|inside|hollow|body",  // 357: Chimecho
    "every|time|appears|before|people",  // 358: Absol
    "always|seen|big|happy|smile",  // 359: Wynaut
    "live|regions|heavy|snowfall|seasons",  // 360: Snorunt
    "body|rock|hardens|armor|ice",  // 361: Glalie
    "faster|rolling|walking|groups|eat",  // 362: Spheal
    "habit|always|juggling|tip|nose",  // 363: Sealeo
    "walreins|massively|developed|tusks|totally",  // 364: Walrein
    "clamperls|sturdy|shell|only|good",  // 365: Clamperl
    "huntails|presence|went|unnoticed|people",  // 366: Huntail
    "lives|southern|seas|extreme|depths",  // 367: Gorebyss
    "species|existed|hundred|million|years",  // 368: Relicanth
    "live|shallow|seas|tropics|heart",  // 369: Luvdisc
    "dream|day|soaring|sky|doomed",  // 370: Bagon
    "inside|shelgons|armor|shell|cells",  // 371: Shelgon
    "came|result|strong|long|held",  // 372: Salamence
    "instead|blood|powerful|magnetic|force",  // 373: Beldum
    "beldum|fuse|together|formed|brains",  // 374: Metang
    "four|brains|total|combined|breeze",  // 375: Metagross
    "sealed|people|long|ago|pokemons",  // 376: Regirock
    "regices|body|during|ice|age",  // 377: Regice
    "body|harder|metal|apparently|hollow",  // 378: Registeel
    "highly|sensitive|emotions|people|senses",  // 379: Latias
    "ability|foe|see|image|seen",  // 380: Latios
    "power|create|massive|rain|clouds",  // 381: Kyogre
    "long|described|mythology|raised|lands",  // 382: Groudon
    "lived|hundreds|millions|years|earths",  // 383: Rayquaza
    "legend|states|true|wish|written",  // 384: Jirachi
    "dna|space|virus|underwent|sudden",  // 385: Deoxys
};

// ── Species profiles (Pokedex order 1-386) ─────────────
static const DaycareSpecies daycareSpecies[] = {
    // [  1] Bulbasaur
    {1, 10, 3, 1, 3, PERS_AGGRESSIVE, 0, 11, {33, 45, 73, 22, 77, 79, 75, 230, 74, 235, 76, 0, 0, 0, 0}, 0},
    // [  2] Ivysaur
    {2, 10, 3, 1, 3, PERS_PROUD, 1, 11, {45, 73, 33, 22, 77, 79, 75, 230, 74, 235, 76, 0, 0, 0, 0}, 1},
    // [  3] Venusaur
    {3, 10, 3, 1, 3, PERS_PROUD, 2, 11, {45, 73, 33, 22, 77, 79, 75, 230, 74, 235, 76, 0, 0, 0, 0}, 2},
    // [  4] Charmander
    {4, 8, 8, 2, 3, PERS_LAZY, 0, 10, {45, 10, 52, 108, 99, 184, 53, 163, 82, 83, 0, 0, 0, 0, 0}, 3},
    // [  5] Charmeleon
    {5, 8, 8, 2, 3, PERS_AGGRESSIVE, 1, 10, {52, 45, 10, 108, 99, 184, 53, 163, 82, 83, 0, 0, 0, 0, 0}, 4},
    // [  6] Charizard
    {6, 8, 2, 2, 3, PERS_SNEAKY, 2, 11, {52, 45, 10, 108, 99, 184, 53, 17, 163, 82, 83, 0, 0, 0, 0}, 5},
    // [  7] Squirtle
    {7, 9, 9, 6, 2, PERS_PROUD, 0, 11, {33, 39, 145, 110, 55, 44, 229, 182, 240, 130, 56, 0, 0, 0, 0}, 6},
    // [  8] Wartortle
    {8, 9, 9, 6, 2, PERS_PROUD, 1, 11, {145, 33, 39, 110, 55, 44, 229, 182, 240, 130, 56, 0, 0, 0, 0}, 7},
    // [  9] Blastoise
    {9, 9, 9, 6, 4, PERS_AGGRESSIVE, 2, 11, {145, 33, 39, 110, 55, 44, 229, 182, 240, 130, 56, 0, 0, 0, 0}, 8},
    // [ 10] Caterpie
    {10, 6, 6, 1, 0, PERS_CLUMSY, 0, 2, {81, 33, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 9},
    // [ 11] Metapod
    {11, 6, 6, 1, 2, PERS_CLUMSY, 1, 1, {106, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 10},
    // [ 12] Butterfree
    {12, 6, 2, 1, 3, PERS_SNEAKY, 2, 10, {93, 77, 78, 79, 48, 18, 16, 60, 219, 318, 0, 0, 0, 0, 0}, 11},
    // [ 13] Weedle
    {13, 6, 3, 1, 0, PERS_GENTLE, 0, 2, {40, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 12},
    // [ 14] Kakuna
    {14, 6, 3, 1, 2, PERS_CLUMSY, 1, 1, {106, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 13},
    // [ 15] Beedrill
    {15, 6, 3, 1, 1, PERS_AGGRESSIVE, 2, 8, {31, 116, 41, 99, 228, 42, 97, 283, 0, 0, 0, 0, 0, 0, 0}, 14},
    // [ 16] Pidgey
    {16, 0, 2, 2, 1, PERS_CLUMSY, 0, 9, {33, 28, 16, 98, 18, 17, 297, 97, 119, 0, 0, 0, 0, 0, 0}, 15},
    // [ 17] Pidgeotto
    {17, 0, 2, 2, 0, PERS_AGGRESSIVE, 1, 9, {16, 28, 33, 98, 18, 17, 297, 97, 119, 0, 0, 0, 0, 0, 0}, 16},
    // [ 18] Pidgeot
    {18, 0, 2, 2, 0, PERS_GENTLE, 2, 9, {16, 98, 28, 33, 18, 17, 297, 97, 119, 0, 0, 0, 0, 0, 0}, 17},
    // [ 19] Rattata
    {19, 0, 0, 2, 1, PERS_CLUMSY, 0, 8, {33, 39, 98, 158, 116, 228, 162, 283, 0, 0, 0, 0, 0, 0, 0}, 18},
    // [ 20] Raticate
    {20, 0, 0, 2, 1, PERS_GENTLE, 2, 8, {98, 33, 39, 158, 184, 228, 162, 283, 0, 0, 0, 0, 0, 0, 0}, 19},
    // [ 21] Spearow
    {21, 0, 2, 2, 1, PERS_GENTLE, 0, 9, {45, 64, 43, 31, 228, 332, 119, 65, 97, 0, 0, 0, 0, 0, 0}, 20},
    // [ 22] Fearow
    {22, 0, 2, 2, 1, PERS_SNEAKY, 2, 8, {31, 45, 43, 64, 228, 119, 65, 97, 0, 0, 0, 0, 0, 0, 0}, 21},
    // [ 23] Ekans
    {23, 3, 3, 2, 1, PERS_CLUMSY, 0, 11, {43, 35, 40, 44, 137, 103, 51, 255, 254, 256, 114, 0, 0, 0, 0}, 22},
    // [ 24] Arbok
    {24, 3, 3, 2, 1, PERS_AGGRESSIVE, 2, 11, {44, 43, 40, 35, 137, 103, 51, 255, 254, 256, 114, 0, 0, 0, 0}, 23},
    // [ 25] Pikachu
    {25, 11, 11, 2, 1, PERS_GENTLE, 1, 11, {45, 84, 39, 86, 98, 104, 21, 85, 97, 87, 113, 0, 0, 0, 0}, 24},
    // [ 26] Raichu
    {26, 11, 11, 2, 1, PERS_AGGRESSIVE, 2, 4, {98, 39, 84, 85, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 25},
    // [ 27] Sandshrew
    {27, 4, 4, 0, 2, PERS_PROUD, 0, 9, {10, 111, 28, 40, 163, 129, 154, 328, 201, 0, 0, 0, 0, 0, 0}, 26},
    // [ 28] Sandslash
    {28, 4, 4, 3, 2, PERS_PROUD, 2, 9, {111, 28, 10, 40, 163, 129, 154, 328, 201, 0, 0, 0, 0, 0, 0}, 27},
    // [ 29] Nidoran F
    {29, 3, 3, 2, 0, PERS_CLUMSY, 0, 10, {45, 10, 39, 24, 40, 44, 270, 154, 260, 242, 0, 0, 0, 0, 0}, 28},
    // [ 30] Nidorina
    {30, 3, 3, 2, 0, PERS_GENTLE, 1, 10, {45, 10, 39, 24, 40, 44, 270, 154, 260, 242, 0, 0, 0, 0, 0}, 29},
    // [ 31] Nidoqueen
    {31, 3, 4, 3, 1, PERS_AGGRESSIVE, 2, 5, {24, 40, 10, 39, 34, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 30},
    // [ 32] Nidoran M
    {32, 3, 3, 2, 1, PERS_CLUMSY, 0, 10, {43, 64, 116, 24, 40, 30, 270, 31, 260, 32, 0, 0, 0, 0, 0}, 31},
    // [ 33] Nidorino
    {33, 3, 3, 2, 1, PERS_AGGRESSIVE, 1, 10, {43, 64, 116, 24, 40, 30, 270, 31, 260, 32, 0, 0, 0, 0, 0}, 32},
    // [ 34] Nidoking
    {34, 3, 4, 3, 1, PERS_PROUD, 2, 5, {24, 116, 64, 40, 37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 33},
    // [ 35] Clefairy
    {35, 0, 0, 2, 0, PERS_GENTLE, 1, 13, {45, 1, 227, 47, 3, 266, 107, 111, 118, 322, 236, 113, 309, 0, 0}, 34},
    // [ 36] Clefable
    {36, 0, 0, 2, 3, PERS_GENTLE, 2, 4, {3, 118, 107, 47, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 35},
    // [ 37] Vulpix
    {37, 8, 8, 2, 4, PERS_CLUMSY, 0, 11, {52, 39, 46, 98, 261, 109, 286, 53, 219, 288, 83, 0, 0, 0, 0}, 36},
    // [ 38] Ninetales
    {38, 8, 8, 2, 4, PERS_GENTLE, 2, 5, {109, 52, 98, 219, 83, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 37},
    // [ 39] Jigglypuff
    {39, 0, 0, 2, 0, PERS_CLUMSY, 1, 11, {47, 111, 1, 50, 205, 3, 156, 34, 102, 304, 38, 0, 0, 0, 0}, 38},
    // [ 40] Wigglytuff
    {40, 0, 0, 2, 0, PERS_PROUD, 2, 4, {111, 50, 3, 47, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 39},
    // [ 41] Zubat
    {41, 3, 2, 2, 1, PERS_GENTLE, 0, 10, {141, 48, 310, 44, 17, 109, 314, 212, 305, 114, 0, 0, 0, 0, 0}, 40},
    // [ 42] Golbat
    {42, 3, 2, 2, 1, PERS_GENTLE, 1, 11, {310, 141, 103, 48, 44, 17, 109, 314, 212, 305, 114, 0, 0, 0, 0}, 41},
    // [ 43] Oddish
    {43, 10, 3, 1, 3, PERS_PROUD, 0, 8, {71, 230, 77, 78, 79, 51, 236, 80, 0, 0, 0, 0, 0, 0, 0}, 42},
    // [ 44] Gloom
    {44, 10, 3, 1, 3, PERS_PROUD, 1, 8, {71, 77, 230, 78, 79, 51, 236, 80, 0, 0, 0, 0, 0, 0, 0}, 43},
    // [ 45] Vileplume
    {45, 10, 3, 1, 3, PERS_PROUD, 2, 5, {71, 312, 72, 78, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 44},
    // [ 46] Paras
    {46, 6, 10, 1, 1, PERS_CLUMSY, 0, 9, {10, 78, 77, 141, 147, 163, 74, 202, 312, 0, 0, 0, 0, 0, 0}, 45},
    // [ 47] Parasect
    {47, 6, 10, 1, 1, PERS_AGGRESSIVE, 2, 9, {77, 10, 78, 141, 147, 163, 74, 202, 312, 0, 0, 0, 0, 0, 0}, 46},
    // [ 48] Venonat
    {48, 6, 3, 1, 0, PERS_AGGRESSIVE, 0, 11, {50, 193, 33, 48, 93, 77, 141, 78, 60, 79, 94, 0, 0, 0, 0}, 47},
    // [ 49] Venomoth
    {49, 6, 3, 1, 3, PERS_SNEAKY, 2, 13, {50, 193, 318, 48, 33, 93, 77, 141, 78, 16, 60, 79, 94, 0, 0}, 48},
    // [ 50] Diglett
    {50, 4, 4, 0, 1, PERS_CLUMSY, 0, 9, {28, 10, 45, 222, 91, 189, 163, 89, 90, 0, 0, 0, 0, 0, 0}, 49},
    // [ 51] Dugtrio
    {51, 4, 4, 3, 1, PERS_SNEAKY, 2, 11, {45, 28, 10, 161, 222, 91, 189, 328, 163, 89, 90, 0, 0, 0, 0}, 50},
    // [ 52] Meowth
    {52, 0, 0, 2, 1, PERS_CLUMSY, 0, 9, {45, 10, 44, 6, 185, 103, 154, 163, 252, 0, 0, 0, 0, 0, 0}, 51},
    // [ 53] Persian
    {53, 0, 0, 2, 1, PERS_SNEAKY, 2, 9, {44, 45, 10, 6, 185, 103, 154, 163, 252, 0, 0, 0, 0, 0, 0}, 52},
    // [ 54] Psyduck
    {54, 9, 9, 6, 3, PERS_LAZY, 0, 9, {10, 346, 39, 50, 93, 103, 244, 154, 56, 0, 0, 0, 0, 0, 0}, 53},
    // [ 55] Golduck
    {55, 9, 9, 6, 3, PERS_SNEAKY, 2, 9, {50, 10, 39, 346, 93, 103, 244, 154, 56, 0, 0, 0, 0, 0, 0}, 54},
    // [ 56] Mankey
    {56, 1, 1, 2, 1, PERS_AGGRESSIVE, 0, 10, {43, 10, 67, 2, 154, 116, 69, 238, 103, 37, 0, 0, 0, 0, 0}, 55},
    // [ 57] Primeape
    {57, 1, 1, 2, 1, PERS_AGGRESSIVE, 1, 11, {43, 67, 99, 10, 2, 154, 116, 69, 238, 103, 37, 0, 0, 0, 0}, 56},
    // [ 58] Growlithe
    {58, 8, 8, 2, 1, PERS_AGGRESSIVE, 0, 10, {44, 46, 52, 43, 316, 36, 172, 270, 97, 53, 0, 0, 0, 0, 0}, 57},
    // [ 59] Arcanine
    {59, 8, 8, 2, 1, PERS_AGGRESSIVE, 2, 5, {44, 52, 316, 46, 245, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 58},
    // [ 60] Poliwag
    {60, 9, 9, 6, 1, PERS_SNEAKY, 0, 8, {145, 95, 55, 3, 240, 34, 187, 56, 0, 0, 0, 0, 0, 0, 0}, 59},
    // [ 61] Poliwhirl
    {61, 9, 9, 6, 1, PERS_SNEAKY, 1, 8, {145, 95, 55, 3, 240, 34, 187, 56, 0, 0, 0, 0, 0, 0, 0}, 60},
    // [ 62] Poliwrath
    {62, 9, 1, 6, 1, PERS_AGGRESSIVE, 2, 5, {3, 95, 66, 55, 170, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 61},
    // [ 63] Abra
    {63, 12, 12, 2, 3, PERS_LAZY, 0, 1, {100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 62},
    // [ 64] Kadabra
    {64, 12, 12, 2, 3, PERS_LAZY, 1, 11, {93, 134, 100, 50, 60, 115, 105, 248, 272, 94, 271, 0, 0, 0, 0}, 63},
    // [ 65] Alakazam
    {65, 12, 12, 2, 3, PERS_SNEAKY, 2, 11, {93, 134, 100, 50, 60, 115, 105, 248, 347, 94, 271, 0, 0, 0, 0}, 64},
    // [ 66] Machop
    {66, 1, 1, 2, 1, PERS_AGGRESSIVE, 0, 12, {43, 67, 116, 2, 69, 193, 279, 233, 66, 238, 184, 223, 0, 0, 0}, 65},
    // [ 67] Machoke
    {67, 1, 1, 2, 1, PERS_AGGRESSIVE, 1, 12, {116, 43, 67, 2, 69, 193, 279, 233, 66, 238, 184, 223, 0, 0, 0}, 66},
    // [ 68] Machamp
    {68, 1, 1, 2, 1, PERS_AGGRESSIVE, 2, 12, {116, 43, 67, 2, 69, 193, 279, 233, 66, 238, 184, 223, 0, 0, 0}, 67},
    // [ 69] Bellsprout
    {69, 10, 3, 1, 1, PERS_AGGRESSIVE, 0, 10, {22, 74, 35, 79, 77, 78, 51, 230, 75, 21, 0, 0, 0, 0, 0}, 68},
    // [ 70] Weepinbell
    {70, 10, 3, 1, 1, PERS_AGGRESSIVE, 1, 10, {74, 22, 35, 79, 77, 78, 51, 230, 75, 21, 0, 0, 0, 0, 0}, 69},
    // [ 71] Victreebel
    {71, 10, 3, 1, 1, PERS_AGGRESSIVE, 2, 4, {75, 79, 230, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 70},
    // [ 72] Tentacool
    {72, 9, 3, 6, 4, PERS_SNEAKY, 0, 9, {40, 48, 132, 51, 61, 35, 112, 103, 56, 0, 0, 0, 0, 0, 0}, 71},
    // [ 73] Tentacruel
    {73, 9, 3, 6, 4, PERS_GENTLE, 2, 9, {132, 40, 48, 51, 61, 35, 112, 103, 56, 0, 0, 0, 0, 0, 0}, 72},
    // [ 74] Geodude
    {74, 5, 4, 0, 2, PERS_GENTLE, 0, 11, {111, 33, 300, 88, 222, 120, 205, 350, 89, 153, 38, 0, 0, 0, 0}, 73},
    // [ 75] Graveler
    {75, 5, 4, 0, 2, PERS_PROUD, 1, 11, {111, 300, 88, 33, 222, 120, 205, 350, 89, 153, 38, 0, 0, 0, 0}, 74},
    // [ 76] Golem
    {76, 5, 4, 3, 2, PERS_LAZY, 2, 11, {111, 300, 88, 33, 222, 120, 205, 350, 89, 153, 38, 0, 0, 0, 0}, 75},
    // [ 77] Ponyta
    {77, 8, 8, 2, 1, PERS_SNEAKY, 0, 10, {33, 45, 39, 52, 23, 83, 36, 97, 340, 126, 0, 0, 0, 0, 0}, 76},
    // [ 78] Rapidash
    {78, 8, 8, 2, 1, PERS_SNEAKY, 2, 11, {52, 45, 33, 39, 23, 83, 36, 97, 31, 340, 126, 0, 0, 0, 0}, 77},
    // [ 79] Slowpoke
    {79, 9, 12, 6, 0, PERS_AGGRESSIVE, 0, 10, {174, 33, 281, 45, 55, 93, 50, 29, 133, 94, 0, 0, 0, 0, 0}, 78},
    // [ 80] Slowbro
    {80, 9, 12, 6, 2, PERS_LAZY, 2, 11, {174, 45, 33, 281, 55, 93, 50, 29, 110, 133, 94, 0, 0, 0, 0}, 79},
    // [ 81] Magnemite
    {81, 11, 16, 2, 3, PERS_AGGRESSIVE, 0, 11, {319, 33, 84, 48, 49, 86, 209, 199, 129, 103, 192, 0, 0, 0, 0}, 80},
    // [ 82] Magneton
    {82, 11, 16, 2, 3, PERS_LAZY, 1, 11, {319, 48, 33, 84, 49, 86, 209, 199, 161, 103, 192, 0, 0, 0, 0}, 81},
    // [ 83] Farfetch'd
    {83, 0, 2, 2, 1, PERS_LAZY, 0, 10, {64, 28, 43, 31, 282, 210, 14, 97, 163, 206, 0, 0, 0, 0, 0}, 82},
    // [ 84] Doduo
    {84, 0, 2, 2, 1, PERS_AGGRESSIVE, 0, 9, {45, 64, 228, 31, 161, 99, 253, 65, 97, 0, 0, 0, 0, 0, 0}, 83},
    // [ 85] Dodrio
    {85, 0, 2, 2, 1, PERS_AGGRESSIVE, 2, 9, {31, 45, 64, 228, 161, 99, 253, 65, 97, 0, 0, 0, 0, 0, 0}, 84},
    // [ 86] Seel
    {86, 9, 9, 6, 4, PERS_CLUMSY, 0, 8, {29, 45, 196, 62, 156, 36, 58, 219, 0, 0, 0, 0, 0, 0, 0}, 85},
    // [ 87] Dewgong
    {87, 9, 13, 6, 4, PERS_LAZY, 2, 9, {62, 45, 29, 196, 156, 329, 36, 58, 219, 0, 0, 0, 0, 0, 0}, 86},
    // [ 88] Grimer
    {88, 3, 3, 2, 1, PERS_AGGRESSIVE, 0, 10, {139, 1, 106, 50, 124, 107, 103, 151, 188, 262, 0, 0, 0, 0, 0}, 87},
    // [ 89] Muk
    {89, 3, 3, 2, 1, PERS_GENTLE, 2, 10, {106, 139, 1, 50, 124, 107, 103, 151, 188, 262, 0, 0, 0, 0, 0}, 88},
    // [ 90] Shellder
    {90, 9, 9, 6, 2, PERS_LAZY, 0, 8, {33, 110, 48, 62, 182, 43, 128, 58, 0, 0, 0, 0, 0, 0, 0}, 89},
    // [ 91] Cloyster
    {91, 9, 13, 6, 2, PERS_PROUD, 2, 6, {62, 182, 48, 110, 191, 131, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 90},
    // [ 92] Gastly
    {92, 7, 3, 0, 3, PERS_SNEAKY, 0, 9, {95, 122, 180, 212, 174, 101, 109, 138, 194, 0, 0, 0, 0, 0, 0}, 91},
    // [ 93] Haunter
    {93, 7, 3, 0, 3, PERS_SNEAKY, 1, 10, {95, 122, 180, 212, 174, 101, 325, 109, 138, 194, 0, 0, 0, 0, 0}, 92},
    // [ 94] Gengar
    {94, 7, 3, 0, 3, PERS_SNEAKY, 2, 10, {95, 122, 180, 212, 174, 101, 325, 109, 138, 194, 0, 0, 0, 0, 0}, 93},
    // [ 95] Onix
    {95, 5, 4, 0, 2, PERS_AGGRESSIVE, 0, 11, {103, 33, 20, 88, 106, 99, 201, 21, 231, 328, 38, 0, 0, 0, 0}, 94},
    // [ 96] Drowzee
    {96, 12, 12, 2, 4, PERS_GENTLE, 0, 10, {95, 1, 50, 93, 29, 139, 96, 94, 244, 248, 0, 0, 0, 0, 0}, 95},
    // [ 97] Hypno
    {97, 12, 12, 2, 4, PERS_AGGRESSIVE, 2, 10, {93, 50, 95, 1, 29, 139, 96, 94, 244, 248, 0, 0, 0, 0, 0}, 96},
    // [ 98] Krabby
    {98, 9, 9, 6, 1, PERS_AGGRESSIVE, 0, 9, {145, 43, 11, 106, 341, 23, 12, 182, 152, 0, 0, 0, 0, 0, 0}, 97},
    // [ 99] Kingler
    {99, 9, 9, 6, 1, PERS_AGGRESSIVE, 2, 9, {145, 43, 11, 106, 341, 23, 12, 182, 152, 0, 0, 0, 0, 0, 0}, 98},
    // [100] Voltorb
    {100, 11, 11, 2, 3, PERS_PROUD, 0, 11, {268, 33, 103, 49, 209, 120, 205, 113, 129, 153, 243, 0, 0, 0, 0}, 99},
    // [101] Electrode
    {101, 11, 11, 2, 3, PERS_PROUD, 2, 11, {268, 103, 49, 33, 209, 120, 205, 113, 129, 153, 243, 0, 0, 0, 0}, 100},
    // [102] Exeggcute
    {102, 10, 12, 1, 2, PERS_ANXIOUS, 0, 10, {140, 95, 253, 115, 73, 93, 78, 77, 79, 76, 0, 0, 0, 0, 0}, 101},
    // [103] Exeggutor
    {103, 10, 12, 1, 3, PERS_GENTLE, 2, 5, {140, 93, 95, 23, 121, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 102},
    // [104] Cubone
    {104, 4, 4, 0, 2, PERS_PROUD, 0, 12, {45, 39, 125, 29, 43, 116, 155, 99, 206, 37, 198, 38, 0, 0, 0}, 103},
    // [105] Marowak
    {105, 4, 4, 3, 2, PERS_AGGRESSIVE, 2, 12, {125, 45, 29, 39, 43, 116, 155, 99, 206, 37, 198, 38, 0, 0, 0}, 104},
    // [106] Hitmonlee
    {106, 1, 1, 2, 1, PERS_AGGRESSIVE, 2, 13, {24, 279, 96, 27, 26, 280, 116, 136, 170, 193, 203, 25, 179, 0, 0}, 105},
    // [107] Hitmonchan
    {107, 1, 1, 2, 4, PERS_AGGRESSIVE, 2, 12, {4, 279, 97, 228, 183, 7, 8, 9, 327, 5, 197, 68, 0, 0, 0}, 106},
    // [108] Lickitung
    {108, 0, 0, 2, 0, PERS_PROUD, 0, 10, {122, 48, 111, 282, 23, 35, 50, 21, 103, 287, 0, 0, 0, 0, 0}, 107},
    // [109] Koffing
    {109, 3, 3, 2, 2, PERS_PROUD, 0, 10, {139, 33, 123, 120, 124, 108, 114, 153, 194, 262, 0, 0, 0, 0, 0}, 108},
    // [110] Weezing
    {110, 3, 3, 2, 2, PERS_PROUD, 2, 10, {139, 120, 123, 33, 124, 108, 114, 153, 194, 262, 0, 0, 0, 0, 0}, 109},
    // [111] Rhyhorn
    {111, 4, 5, 0, 2, PERS_PROUD, 0, 10, {30, 39, 23, 31, 184, 350, 32, 36, 89, 224, 0, 0, 0, 0, 0}, 110},
    // [112] Rhydon
    {112, 4, 5, 0, 1, PERS_AGGRESSIVE, 1, 10, {31, 30, 23, 39, 184, 350, 32, 36, 89, 224, 0, 0, 0, 0, 0}, 111},
    // [113] Chansey
    {113, 0, 0, 2, 0, PERS_GENTLE, 1, 12, {45, 1, 39, 287, 135, 3, 107, 47, 121, 111, 113, 38, 0, 0, 0}, 112},
    // [114] Tangela
    {114, 10, 10, 1, 2, PERS_PROUD, 0, 12, {132, 275, 79, 71, 74, 77, 22, 20, 72, 78, 21, 321, 0, 0, 0}, 113},
    // [115] Kangaskhan
    {115, 0, 0, 2, 0, PERS_AGGRESSIVE, 0, 10, {4, 43, 44, 39, 252, 5, 99, 203, 146, 179, 0, 0, 0, 0, 0}, 114},
    // [116] Horsea
    {116, 9, 9, 6, 3, PERS_GENTLE, 0, 8, {145, 108, 43, 55, 239, 97, 56, 349, 0, 0, 0, 0, 0, 0, 0}, 115},
    // [117] Seadra
    {117, 9, 9, 6, 3, PERS_PROUD, 1, 8, {145, 43, 108, 55, 239, 97, 56, 349, 0, 0, 0, 0, 0, 0, 0}, 116},
    // [118] Goldeen
    {118, 9, 9, 6, 1, PERS_GENTLE, 0, 10, {64, 39, 346, 48, 30, 175, 31, 127, 32, 97, 0, 0, 0, 0, 0}, 117},
    // [119] Seaking
    {119, 9, 9, 6, 1, PERS_AGGRESSIVE, 2, 10, {64, 48, 39, 346, 30, 175, 31, 127, 32, 97, 0, 0, 0, 0, 0}, 118},
    // [120] Staryu
    {120, 9, 9, 6, 3, PERS_SNEAKY, 0, 12, {106, 33, 55, 229, 105, 293, 129, 61, 107, 113, 322, 56, 0, 0, 0}, 119},
    // [121] Starmie
    {121, 9, 12, 6, 3, PERS_SNEAKY, 2, 5, {229, 105, 129, 55, 109, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 120},
    // [122] Mr. Mime
    {122, 12, 12, 2, 4, PERS_SNEAKY, 1, 15, {112, 93, 164, 96, 3, 113, 115, 227, 60, 278, 271, 272, 94, 226, 219}, 121},
    // [123] Scyther
    {123, 6, 2, 1, 1, PERS_AGGRESSIVE, 0, 11, {43, 98, 116, 228, 206, 97, 17, 163, 14, 104, 210, 0, 0, 0, 0}, 122},
    // [124] Jynx
    {124, 13, 12, 3, 3, PERS_SNEAKY, 2, 11, {122, 142, 1, 181, 3, 8, 212, 313, 34, 195, 59, 0, 0, 0, 0}, 123},
    // [125] Electabuzz
    {125, 11, 11, 2, 3, PERS_SNEAKY, 1, 8, {43, 98, 9, 113, 129, 103, 85, 87, 0, 0, 0, 0, 0, 0, 0}, 124},
    // [126] Magmar
    {126, 8, 8, 2, 3, PERS_GENTLE, 1, 9, {52, 7, 43, 123, 108, 241, 53, 109, 126, 0, 0, 0, 0, 0, 0}, 125},
    // [127] Pinsir
    {127, 6, 6, 1, 1, PERS_AGGRESSIVE, 0, 10, {116, 11, 20, 69, 106, 279, 280, 12, 66, 14, 0, 0, 0, 0, 0}, 126},
    // [128] Tauros
    {128, 0, 0, 2, 1, PERS_AGGRESSIVE, 0, 9, {33, 39, 99, 30, 184, 228, 156, 37, 36, 0, 0, 0, 0, 0, 0}, 127},
    // [129] Magikarp
    {129, 9, 9, 6, 2, PERS_CLUMSY, 0, 3, {150, 33, 175, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 128},
    // [130] Gyarados
    {130, 9, 2, 6, 1, PERS_AGGRESSIVE, 2, 9, {37, 44, 82, 43, 239, 56, 240, 349, 63, 0, 0, 0, 0, 0, 0}, 129},
    // [131] Lapras
    {131, 9, 13, 6, 0, PERS_GENTLE, 0, 12, {45, 47, 55, 54, 34, 109, 195, 58, 240, 219, 56, 329, 0, 0, 0}, 130},
    // [132] Ditto
    {132, 0, 0, 2, 1, PERS_GENTLE, 0, 1, {144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 131},
    // [133] Eevee
    {133, 0, 0, 2, 4, PERS_GENTLE, 0, 9, {270, 33, 39, 28, 45, 98, 44, 226, 36, 0, 0, 0, 0, 0, 0}, 132},
    // [134] Vaporeon
    {134, 9, 9, 6, 0, PERS_AGGRESSIVE, 2, 11, {270, 33, 39, 28, 55, 98, 44, 62, 114, 151, 56, 0, 0, 0, 0}, 133},
    // [135] Jolteon
    {135, 11, 11, 2, 3, PERS_SNEAKY, 2, 11, {270, 33, 39, 28, 84, 98, 24, 42, 86, 97, 87, 0, 0, 0, 0}, 134},
    // [136] Flareon
    {136, 8, 8, 2, 1, PERS_GENTLE, 2, 11, {270, 33, 39, 28, 52, 98, 44, 83, 123, 43, 53, 0, 0, 0, 0}, 135},
    // [137] Porygon
    {137, 0, 0, 2, 3, PERS_PROUD, 0, 11, {160, 176, 33, 97, 60, 105, 159, 199, 161, 278, 192, 0, 0, 0, 0}, 136},
    // [138] Omanyte
    {138, 5, 9, 6, 2, PERS_PROUD, 0, 10, {132, 110, 44, 55, 341, 43, 182, 321, 246, 56, 0, 0, 0, 0, 0}, 137},
    // [139] Omastar
    {139, 5, 9, 6, 2, PERS_PROUD, 2, 11, {44, 132, 110, 55, 341, 43, 182, 131, 321, 246, 56, 0, 0, 0, 0}, 138},
    // [140] Kabuto
    {140, 5, 9, 6, 2, PERS_PROUD, 0, 10, {106, 10, 71, 43, 341, 28, 203, 319, 72, 246, 0, 0, 0, 0, 0}, 139},
    // [141] Kabutops
    {141, 5, 9, 6, 1, PERS_AGGRESSIVE, 2, 11, {71, 106, 10, 43, 341, 28, 203, 163, 319, 72, 246, 0, 0, 0, 0}, 140},
    // [142] Aerodactyl
    {142, 5, 2, 0, 1, PERS_AGGRESSIVE, 0, 8, {17, 97, 44, 48, 246, 184, 36, 63, 0, 0, 0, 0, 0, 0, 0}, 141},
    // [143] Snorlax
    {143, 0, 0, 2, 0, PERS_GENTLE, 2, 13, {33, 133, 111, 187, 29, 281, 156, 173, 34, 335, 343, 205, 63, 0, 0}, 142},
    // [144] Articuno
    {144, 13, 2, 4, 4, PERS_PROUD, 0, 9, {16, 181, 54, 97, 170, 58, 115, 59, 329, 0, 0, 0, 0, 0, 0}, 143},
    // [145] Zapdos
    {145, 11, 2, 4, 3, PERS_SNEAKY, 0, 9, {64, 84, 86, 97, 197, 65, 268, 113, 87, 0, 0, 0, 0, 0, 0}, 144},
    // [146] Moltres
    {146, 8, 2, 4, 3, PERS_AGGRESSIVE, 0, 9, {52, 17, 83, 97, 203, 53, 219, 257, 143, 0, 0, 0, 0, 0, 0}, 145},
    // [147] Dratini
    {147, 14, 14, 2, 1, PERS_AGGRESSIVE, 0, 10, {43, 35, 86, 239, 82, 21, 97, 219, 200, 63, 0, 0, 0, 0, 0}, 146},
    // [148] Dragonair
    {148, 14, 14, 2, 1, PERS_GENTLE, 1, 10, {43, 86, 239, 35, 82, 21, 97, 219, 200, 63, 0, 0, 0, 0, 0}, 147},
    // [149] Dragonite
    {149, 14, 2, 2, 1, PERS_AGGRESSIVE, 2, 11, {43, 86, 239, 35, 82, 21, 97, 219, 17, 200, 63, 0, 0, 0, 0}, 148},
    // [150] Mewtwo
    {150, 12, 12, 4, 3, PERS_SNEAKY, 0, 11, {93, 50, 112, 129, 244, 248, 54, 94, 133, 105, 219, 0, 0, 0, 0}, 149},
    // [151] Mew
    {151, 12, 12, 4, 1, PERS_GENTLE, 0, 6, {1, 144, 5, 118, 94, 246, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 150},
    // [152] Chikorita
    {152, 10, 10, 1, 2, PERS_GENTLE, 0, 10, {45, 33, 75, 115, 77, 235, 34, 113, 219, 76, 0, 0, 0, 0, 0}, 151},
    // [153] Bayleef
    {153, 10, 10, 1, 2, PERS_PROUD, 1, 10, {45, 75, 115, 33, 77, 235, 34, 113, 219, 76, 0, 0, 0, 0, 0}, 152},
    // [154] Meganium
    {154, 10, 10, 1, 2, PERS_PROUD, 2, 10, {45, 75, 115, 33, 77, 235, 34, 113, 219, 76, 0, 0, 0, 0, 0}, 153},
    // [155] Cyndaquil
    {155, 8, 8, 2, 3, PERS_GENTLE, 0, 8, {43, 33, 108, 52, 98, 172, 129, 53, 0, 0, 0, 0, 0, 0, 0}, 154},
    // [156] Quilava
    {156, 8, 8, 2, 3, PERS_LAZY, 1, 8, {43, 108, 33, 52, 98, 172, 129, 53, 0, 0, 0, 0, 0, 0, 0}, 155},
    // [157] Typhlosion
    {157, 8, 8, 2, 3, PERS_AGGRESSIVE, 2, 8, {52, 43, 108, 33, 98, 172, 129, 53, 0, 0, 0, 0, 0, 0, 0}, 156},
    // [158] Totodile
    {158, 9, 9, 6, 1, PERS_AGGRESSIVE, 0, 9, {43, 10, 99, 55, 44, 184, 163, 103, 56, 0, 0, 0, 0, 0, 0}, 157},
    // [159] Croconaw
    {159, 9, 9, 6, 1, PERS_LAZY, 1, 9, {43, 99, 10, 55, 44, 184, 163, 103, 56, 0, 0, 0, 0, 0, 0}, 158},
    // [160] Feraligatr
    {160, 9, 9, 6, 1, PERS_GENTLE, 2, 9, {43, 99, 10, 55, 44, 184, 163, 103, 56, 0, 0, 0, 0, 0, 0}, 159},
    // [161] Sentret
    {161, 0, 0, 2, 1, PERS_GENTLE, 0, 9, {10, 111, 98, 154, 270, 21, 266, 156, 133, 0, 0, 0, 0, 0, 0}, 160},
    // [162] Furret
    {162, 0, 0, 2, 0, PERS_SNEAKY, 2, 9, {111, 98, 10, 154, 270, 21, 266, 156, 133, 0, 0, 0, 0, 0, 0}, 161},
    // [163] Hoothoot
    {163, 0, 2, 2, 0, PERS_LAZY, 0, 9, {45, 33, 193, 64, 95, 115, 36, 93, 138, 0, 0, 0, 0, 0, 0}, 162},
    // [164] Noctowl
    {164, 0, 2, 2, 0, PERS_GENTLE, 2, 9, {193, 45, 64, 33, 95, 115, 36, 93, 138, 0, 0, 0, 0, 0, 0}, 163},
    // [165] Ledyba
    {165, 6, 2, 1, 4, PERS_GENTLE, 0, 10, {33, 48, 4, 113, 115, 219, 226, 129, 97, 38, 0, 0, 0, 0, 0}, 164},
    // [166] Ledian
    {166, 6, 2, 1, 4, PERS_LAZY, 2, 10, {48, 33, 4, 113, 115, 219, 226, 129, 97, 38, 0, 0, 0, 0, 0}, 165},
    // [167] Spinarak
    {167, 6, 3, 1, 1, PERS_GENTLE, 0, 10, {40, 81, 184, 132, 101, 141, 154, 169, 97, 94, 0, 0, 0, 0, 0}, 166},
    // [168] Ariados
    {168, 6, 3, 1, 1, PERS_AGGRESSIVE, 2, 10, {132, 40, 184, 81, 101, 141, 154, 169, 97, 94, 0, 0, 0, 0, 0}, 167},
    // [169] Crobat
    {169, 3, 2, 2, 1, PERS_CLUMSY, 2, 11, {310, 141, 103, 48, 44, 17, 109, 314, 212, 305, 114, 0, 0, 0, 0}, 168},
    // [170] Chinchou
    {170, 9, 11, 6, 0, PERS_GENTLE, 0, 10, {145, 86, 48, 175, 55, 209, 109, 36, 56, 268, 0, 0, 0, 0, 0}, 169},
    // [171] Lanturn
    {171, 9, 11, 6, 0, PERS_SNEAKY, 2, 10, {145, 48, 86, 175, 55, 209, 109, 36, 56, 268, 0, 0, 0, 0, 0}, 170},
    // [172] Pichu
    {172, 11, 11, 2, 1, PERS_GENTLE, 0, 5, {204, 84, 39, 86, 186, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 171},
    // [173] Cleffa
    {173, 0, 0, 2, 4, PERS_CLUMSY, 0, 5, {204, 1, 227, 47, 186, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 172},
    // [174] Igglybuff
    {174, 0, 0, 2, 0, PERS_CLUMSY, 0, 5, {204, 47, 111, 1, 186, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 173},
    // [175] Togepi
    {175, 0, 0, 2, 2, PERS_GENTLE, 0, 10, {204, 45, 118, 186, 281, 227, 266, 273, 219, 38, 0, 0, 0, 0, 0}, 174},
    // [176] Togetic
    {176, 2, 2, 2, 4, PERS_GENTLE, 1, 10, {204, 45, 118, 186, 281, 227, 266, 273, 219, 38, 0, 0, 0, 0, 0}, 175},
    // [177] Natu
    {177, 12, 2, 2, 3, PERS_SNEAKY, 0, 8, {43, 64, 101, 100, 248, 273, 109, 94, 0, 0, 0, 0, 0, 0, 0}, 176},
    // [178] Xatu
    {178, 12, 2, 2, 3, PERS_SNEAKY, 2, 8, {43, 64, 101, 100, 248, 273, 109, 94, 0, 0, 0, 0, 0, 0, 0}, 177},
    // [179] Mareep
    {179, 11, 11, 2, 3, PERS_CLUMSY, 0, 7, {45, 33, 84, 86, 178, 113, 87, 0, 0, 0, 0, 0, 0, 0, 0}, 178},
    // [180] Flaaffy
    {180, 11, 11, 2, 3, PERS_AGGRESSIVE, 1, 7, {45, 33, 84, 86, 178, 113, 87, 0, 0, 0, 0, 0, 0, 0, 0}, 179},
    // [181] Ampharos
    {181, 11, 11, 2, 3, PERS_PROUD, 2, 8, {45, 33, 84, 86, 178, 9, 113, 87, 0, 0, 0, 0, 0, 0, 0}, 180},
    // [182] Bellossom
    {182, 10, 10, 1, 4, PERS_PROUD, 2, 6, {71, 345, 78, 230, 80, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 181},
    // [183] Marill
    {183, 9, 9, 6, 0, PERS_CLUMSY, 1, 9, {33, 111, 39, 55, 205, 61, 38, 240, 56, 0, 0, 0, 0, 0, 0}, 182},
    // [184] Azumarill
    {184, 9, 9, 6, 0, PERS_PROUD, 2, 9, {111, 33, 39, 55, 205, 61, 38, 240, 56, 0, 0, 0, 0, 0, 0}, 183},
    // [185] Sudowoodo
    {185, 5, 5, 3, 2, PERS_PROUD, 2, 9, {102, 88, 175, 67, 157, 335, 185, 21, 38, 0, 0, 0, 0, 0, 0}, 184},
    // [186] Politoed
    {186, 9, 9, 6, 4, PERS_AGGRESSIVE, 2, 5, {3, 95, 195, 55, 207, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 185},
    // [187] Hoppip
    {187, 10, 2, 1, 4, PERS_GENTLE, 0, 10, {150, 235, 39, 33, 77, 78, 79, 73, 178, 72, 0, 0, 0, 0, 0}, 186},
    // [188] Skiploom
    {188, 10, 2, 1, 4, PERS_SNEAKY, 1, 10, {150, 235, 33, 39, 77, 78, 79, 73, 178, 72, 0, 0, 0, 0, 0}, 187},
    // [189] Jumpluff
    {189, 10, 2, 1, 4, PERS_SNEAKY, 2, 10, {150, 235, 33, 39, 77, 78, 79, 73, 178, 72, 0, 0, 0, 0, 0}, 188},
    // [190] Aipom
    {190, 0, 0, 2, 1, PERS_LAZY, 0, 10, {10, 39, 28, 310, 226, 321, 154, 129, 103, 97, 0, 0, 0, 0, 0}, 189},
    // [191] Sunkern
    {191, 10, 10, 1, 1, PERS_CLUMSY, 0, 8, {71, 74, 72, 275, 283, 241, 235, 202, 0, 0, 0, 0, 0, 0, 0}, 190},
    // [192] Sunflora
    {192, 10, 10, 1, 3, PERS_AGGRESSIVE, 2, 9, {71, 1, 74, 75, 275, 331, 241, 80, 76, 0, 0, 0, 0, 0, 0}, 191},
    // [193] Yanma
    {193, 6, 2, 1, 3, PERS_SNEAKY, 0, 10, {193, 33, 98, 104, 49, 197, 48, 253, 17, 103, 0, 0, 0, 0, 0}, 192},
    // [194] Wooper
    {194, 9, 4, 6, 0, PERS_GENTLE, 0, 10, {39, 55, 21, 341, 133, 281, 89, 240, 114, 54, 0, 0, 0, 0, 0}, 193},
    // [195] Quagsire
    {195, 9, 4, 6, 0, PERS_LAZY, 2, 10, {39, 55, 21, 341, 133, 281, 89, 240, 114, 54, 0, 0, 0, 0, 0}, 194},
    // [196] Espeon
    {196, 12, 12, 2, 3, PERS_SNEAKY, 2, 11, {270, 33, 39, 28, 93, 98, 129, 60, 244, 94, 234, 0, 0, 0, 0}, 195},
    // [197] Umbreon
    {197, 15, 15, 2, 4, PERS_GENTLE, 2, 11, {270, 33, 39, 28, 228, 98, 109, 185, 212, 103, 236, 0, 0, 0, 0}, 196},
    // [198] Murkrow
    {198, 15, 2, 2, 1, PERS_LAZY, 0, 8, {64, 310, 228, 114, 101, 185, 269, 212, 0, 0, 0, 0, 0, 0, 0}, 197},
    // [199] Slowking
    {199, 9, 12, 6, 4, PERS_LAZY, 2, 10, {174, 33, 281, 45, 55, 93, 50, 29, 207, 94, 0, 0, 0, 0, 0}, 198},
    // [200] Misdreavus
    {200, 7, 7, 0, 3, PERS_SNEAKY, 0, 10, {45, 149, 180, 310, 109, 212, 60, 220, 195, 288, 0, 0, 0, 0, 0}, 199},
    // [201] Unown
    {201, 12, 12, 2, 1, PERS_AGGRESSIVE, 0, 1, {237, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 200},
    // [202] Wobbuffet
    {202, 12, 12, 2, 0, PERS_AGGRESSIVE, 2, 4, {68, 194, 243, 219, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 201},
    // [203] Girafarig
    {203, 0, 12, 2, 3, PERS_SNEAKY, 0, 10, {45, 33, 310, 93, 23, 316, 97, 226, 60, 242, 0, 0, 0, 0, 0}, 202},
    // [204] Pineco
    {204, 6, 6, 1, 2, PERS_CLUMSY, 0, 9, {182, 33, 120, 36, 229, 117, 153, 191, 38, 0, 0, 0, 0, 0, 0}, 203},
    // [205] Forretress
    {205, 6, 16, 1, 2, PERS_PROUD, 2, 9, {182, 120, 33, 36, 229, 117, 153, 191, 38, 0, 0, 0, 0, 0, 0}, 204},
    // [206] Dunsparce
    {206, 0, 0, 2, 0, PERS_AGGRESSIVE, 0, 9, {99, 111, 281, 137, 180, 228, 103, 36, 283, 0, 0, 0, 0, 0, 0}, 205},
    // [207] Gligar
    {207, 4, 2, 0, 2, PERS_PROUD, 0, 8, {40, 28, 106, 98, 185, 163, 103, 12, 0, 0, 0, 0, 0, 0, 0}, 206},
    // [208] Steelix
    {208, 16, 4, 3, 2, PERS_PROUD, 2, 11, {103, 33, 20, 88, 106, 99, 201, 21, 231, 242, 38, 0, 0, 0, 0}, 207},
    // [209] Snubbull
    {209, 0, 0, 2, 1, PERS_AGGRESSIVE, 0, 10, {184, 33, 39, 204, 44, 122, 46, 99, 36, 242, 0, 0, 0, 0, 0}, 208},
    // [210] Granbull
    {210, 0, 0, 2, 1, PERS_AGGRESSIVE, 2, 10, {184, 33, 39, 204, 44, 122, 46, 99, 36, 242, 0, 0, 0, 0, 0}, 209},
    // [211] Qwilfish
    {211, 9, 3, 6, 1, PERS_AGGRESSIVE, 0, 9, {40, 191, 33, 106, 107, 55, 42, 36, 56, 0, 0, 0, 0, 0, 0}, 210},
    // [212] Scizor
    {212, 6, 16, 1, 1, PERS_AGGRESSIVE, 2, 11, {43, 98, 116, 228, 206, 97, 232, 163, 14, 104, 210, 0, 0, 0, 0}, 211},
    // [213] Shuckle
    {213, 6, 5, 0, 2, PERS_PROUD, 0, 7, {132, 110, 35, 227, 219, 117, 156, 0, 0, 0, 0, 0, 0, 0, 0}, 212},
    // [214] Heracross
    {214, 6, 1, 1, 1, PERS_AGGRESSIVE, 0, 10, {43, 33, 30, 203, 31, 280, 68, 36, 179, 224, 0, 0, 0, 0, 0}, 213},
    // [215] Sneasel
    {215, 15, 13, 3, 1, PERS_SNEAKY, 0, 12, {43, 10, 269, 98, 103, 185, 154, 97, 196, 163, 251, 232, 0, 0, 0}, 214},
    // [216] Teddiursa
    {216, 0, 0, 2, 1, PERS_ANXIOUS, 0, 10, {43, 10, 122, 154, 313, 185, 156, 163, 173, 37, 0, 0, 0, 0, 0}, 215},
    // [217] Ursaring
    {217, 0, 0, 2, 1, PERS_AGGRESSIVE, 1, 10, {154, 43, 122, 10, 313, 185, 156, 163, 173, 37, 0, 0, 0, 0, 0}, 216},
    // [218] Slugma
    {218, 8, 8, 2, 3, PERS_LAZY, 0, 9, {123, 281, 52, 88, 106, 133, 53, 157, 34, 0, 0, 0, 0, 0, 0}, 217},
    // [219] Magcargo
    {219, 8, 5, 3, 2, PERS_PROUD, 2, 9, {52, 88, 123, 281, 106, 133, 53, 157, 34, 0, 0, 0, 0, 0, 0}, 218},
    // [220] Swinub
    {220, 13, 4, 0, 1, PERS_CLUMSY, 0, 8, {316, 33, 181, 203, 36, 54, 59, 133, 0, 0, 0, 0, 0, 0, 0}, 219},
    // [221] Piloswine
    {221, 13, 4, 0, 1, PERS_AGGRESSIVE, 1, 9, {203, 30, 316, 181, 36, 31, 54, 59, 133, 0, 0, 0, 0, 0, 0}, 220},
    // [222] Corsola
    {222, 9, 5, 6, 2, PERS_PROUD, 0, 10, {33, 106, 145, 105, 287, 61, 131, 350, 243, 246, 0, 0, 0, 0, 0}, 221},
    // [223] Remoraid
    {223, 9, 9, 6, 1, PERS_GENTLE, 0, 8, {55, 199, 62, 61, 60, 116, 58, 63, 0, 0, 0, 0, 0, 0, 0}, 222},
    // [224] Octillery
    {224, 9, 9, 6, 1, PERS_SNEAKY, 2, 9, {55, 132, 62, 61, 60, 190, 116, 58, 63, 0, 0, 0, 0, 0, 0}, 223},
    // [225] Delibird
    {225, 13, 2, 3, 3, PERS_SNEAKY, 0, 1, {217, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 224},
    // [226] Mantine
    {226, 9, 2, 6, 4, PERS_PROUD, 2, 9, {145, 33, 48, 61, 36, 97, 17, 352, 109, 0, 0, 0, 0, 0, 0}, 225},
    // [227] Skarmory
    {227, 16, 2, 2, 2, PERS_AGGRESSIVE, 0, 10, {43, 64, 28, 129, 97, 31, 314, 211, 191, 319, 0, 0, 0, 0, 0}, 226},
    // [228] Houndour
    {228, 15, 8, 2, 3, PERS_LAZY, 0, 10, {52, 43, 336, 123, 46, 44, 316, 185, 53, 242, 0, 0, 0, 0, 0}, 227},
    // [229] Houndoom
    {229, 15, 8, 2, 3, PERS_LAZY, 2, 10, {52, 336, 43, 123, 46, 44, 316, 185, 53, 242, 0, 0, 0, 0, 0}, 228},
    // [230] Kingdra
    {230, 9, 14, 6, 1, PERS_AGGRESSIVE, 2, 8, {145, 43, 108, 55, 239, 97, 56, 349, 0, 0, 0, 0, 0, 0, 0}, 229},
    // [231] Phanpy
    {231, 4, 4, 0, 0, PERS_AGGRESSIVE, 0, 9, {45, 316, 33, 111, 175, 36, 205, 203, 38, 0, 0, 0, 0, 0, 0}, 230},
    // [232] Donphan
    {232, 4, 4, 3, 1, PERS_AGGRESSIVE, 2, 9, {45, 30, 316, 111, 175, 31, 205, 229, 89, 0, 0, 0, 0, 0, 0}, 231},
    // [233] Porygon2
    {233, 0, 0, 2, 3, PERS_PROUD, 1, 11, {160, 176, 33, 97, 60, 105, 111, 199, 161, 278, 192, 0, 0, 0, 0}, 232},
    // [234] Stantler
    {234, 0, 0, 2, 1, PERS_AGGRESSIVE, 0, 9, {33, 43, 310, 95, 23, 28, 36, 109, 347, 0, 0, 0, 0, 0, 0}, 233},
    // [235] Smeargle
    {235, 0, 0, 2, 0, PERS_CLUMSY, 0, 1, {166, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 234},
    // [236] Tyrogue
    {236, 1, 1, 2, 1, PERS_CLUMSY, 0, 1, {33, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 235},
    // [237] Hitmontop
    {237, 1, 1, 2, 4, PERS_AGGRESSIVE, 2, 11, {279, 27, 116, 228, 98, 167, 229, 68, 97, 197, 283, 0, 0, 0, 0}, 236},
    // [238] Smoochum
    {238, 13, 12, 3, 3, PERS_SNEAKY, 0, 11, {122, 1, 186, 181, 93, 47, 212, 313, 94, 195, 59, 0, 0, 0, 0}, 237},
    // [239] Elekid
    {239, 11, 11, 2, 3, PERS_SNEAKY, 0, 8, {43, 98, 9, 113, 129, 103, 85, 87, 0, 0, 0, 0, 0, 0, 0}, 238},
    // [240] Magby
    {240, 8, 8, 2, 1, PERS_GENTLE, 0, 9, {52, 43, 123, 7, 108, 241, 53, 109, 126, 0, 0, 0, 0, 0, 0}, 239},
    // [241] Miltank
    {241, 0, 0, 2, 2, PERS_PROUD, 0, 9, {33, 45, 111, 23, 208, 117, 205, 34, 215, 0, 0, 0, 0, 0, 0}, 240},
    // [242] Blissey
    {242, 0, 0, 2, 0, PERS_AGGRESSIVE, 2, 12, {45, 1, 39, 287, 135, 3, 107, 47, 121, 111, 113, 38, 0, 0, 0}, 241},
    // [243] Raikou
    {243, 11, 11, 4, 3, PERS_LAZY, 0, 10, {44, 43, 84, 46, 98, 209, 115, 242, 87, 347, 0, 0, 0, 0, 0}, 242},
    // [244] Entei
    {244, 8, 8, 4, 1, PERS_LAZY, 0, 10, {44, 43, 52, 46, 83, 23, 53, 207, 126, 347, 0, 0, 0, 0, 0}, 243},
    // [245] Suicune
    {245, 9, 9, 4, 2, PERS_PROUD, 0, 10, {44, 43, 61, 240, 16, 62, 54, 243, 56, 347, 0, 0, 0, 0, 0}, 244},
    // [246] Larvitar
    {246, 5, 4, 0, 1, PERS_LAZY, 0, 10, {44, 43, 201, 103, 157, 37, 184, 242, 89, 63, 0, 0, 0, 0, 0}, 245},
    // [247] Pupitar
    {247, 5, 4, 0, 1, PERS_LAZY, 1, 10, {44, 43, 201, 103, 157, 37, 184, 242, 89, 63, 0, 0, 0, 0, 0}, 246},
    // [248] Tyranitar
    {248, 5, 15, 3, 1, PERS_AGGRESSIVE, 2, 10, {44, 43, 201, 103, 157, 37, 184, 242, 89, 63, 0, 0, 0, 0, 0}, 247},
    // [249] Lugia
    {249, 12, 2, 4, 4, PERS_AGGRESSIVE, 0, 10, {18, 219, 16, 105, 56, 240, 129, 177, 246, 248, 0, 0, 0, 0, 0}, 248},
    // [250] Ho-Oh
    {250, 8, 2, 4, 4, PERS_AGGRESSIVE, 0, 10, {18, 219, 16, 105, 126, 241, 129, 221, 246, 248, 0, 0, 0, 0, 0}, 249},
    // [251] Celebi
    {251, 12, 10, 4, 1, PERS_AGGRESSIVE, 0, 9, {93, 215, 73, 105, 219, 246, 248, 226, 195, 0, 0, 0, 0, 0, 0}, 250},
    // [252] Treecko
    {252, 10, 10, 1, 3, PERS_SNEAKY, 0, 11, {43, 1, 71, 98, 228, 103, 72, 97, 21, 197, 202, 0, 0, 0, 0}, 251},
    // [253] Grovyle
    {253, 10, 10, 1, 3, PERS_SNEAKY, 1, 12, {71, 43, 1, 98, 210, 228, 103, 348, 97, 21, 197, 206, 0, 0, 0}, 252},
    // [254] Sceptile
    {254, 10, 10, 1, 3, PERS_SNEAKY, 2, 12, {71, 43, 1, 98, 210, 228, 103, 348, 97, 21, 197, 206, 0, 0, 0}, 253},
    // [255] Torchic
    {255, 8, 8, 2, 3, PERS_AGGRESSIVE, 0, 11, {45, 10, 116, 52, 64, 28, 83, 98, 163, 119, 53, 0, 0, 0, 0}, 254},
    // [256] Combusken
    {256, 8, 1, 2, 1, PERS_GENTLE, 1, 12, {52, 116, 45, 10, 24, 64, 28, 339, 98, 163, 119, 327, 0, 0, 0}, 255},
    // [257] Blaziken
    {257, 8, 1, 2, 1, PERS_AGGRESSIVE, 2, 14, {52, 7, 116, 45, 10, 24, 64, 28, 339, 98, 299, 163, 119, 327, 0}, 256},
    // [258] Mudkip
    {258, 9, 9, 6, 1, PERS_LAZY, 0, 12, {45, 33, 189, 55, 117, 193, 300, 36, 250, 182, 56, 283, 0, 0, 0}, 257},
    // [259] Marshtomp
    {259, 9, 4, 6, 1, PERS_AGGRESSIVE, 1, 13, {45, 189, 33, 55, 117, 341, 193, 300, 36, 330, 182, 89, 283, 0, 0}, 258},
    // [260] Swampert
    {260, 9, 4, 6, 1, PERS_AGGRESSIVE, 2, 13, {45, 189, 33, 55, 117, 341, 193, 300, 36, 330, 182, 89, 283, 0, 0}, 259},
    // [261] Poochyena
    {261, 15, 15, 2, 1, PERS_GENTLE, 0, 12, {33, 336, 28, 44, 316, 46, 207, 184, 36, 269, 242, 168, 0, 0, 0}, 260},
    // [262] Mightyena
    {262, 15, 15, 2, 1, PERS_AGGRESSIVE, 2, 12, {44, 336, 28, 33, 316, 46, 207, 184, 36, 269, 242, 168, 0, 0, 0}, 261},
    // [263] Zigzagoon
    {263, 0, 0, 2, 2, PERS_CLUMSY, 0, 12, {45, 33, 39, 29, 28, 316, 300, 42, 343, 175, 156, 187, 0, 0, 0}, 262},
    // [264] Linoone
    {264, 0, 0, 2, 0, PERS_AGGRESSIVE, 1, 12, {45, 29, 33, 39, 28, 316, 300, 154, 343, 163, 156, 187, 0, 0, 0}, 263},
    // [265] Wurmple
    {265, 6, 6, 1, 1, PERS_CLUMSY, 0, 3, {81, 33, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 264},
    // [266] Silcoon
    {266, 6, 6, 1, 2, PERS_CLUMSY, 1, 1, {106, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 265},
    // [267] Beautifly
    {267, 6, 2, 1, 3, PERS_AGGRESSIVE, 2, 9, {71, 16, 78, 234, 72, 18, 213, 318, 202, 0, 0, 0, 0, 0, 0}, 266},
    // [268] Cascoon
    {268, 6, 6, 1, 2, PERS_CLUMSY, 1, 1, {106, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 267},
    // [269] Dustox
    {269, 6, 3, 1, 4, PERS_PROUD, 2, 9, {93, 16, 182, 236, 60, 18, 113, 318, 92, 0, 0, 0, 0, 0, 0}, 268},
    // [270] Lotad
    {270, 9, 10, 6, 4, PERS_CLUMSY, 0, 7, {310, 45, 71, 267, 54, 240, 72, 0, 0, 0, 0, 0, 0, 0, 0}, 269},
    // [271] Lombre
    {271, 9, 10, 6, 4, PERS_LAZY, 1, 10, {310, 45, 71, 267, 252, 154, 346, 168, 253, 56, 0, 0, 0, 0, 0}, 270},
    // [272] Ludicolo
    {272, 9, 10, 6, 4, PERS_AGGRESSIVE, 2, 4, {71, 310, 45, 267, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 271},
    // [273] Seedot
    {273, 10, 10, 1, 2, PERS_CLUMSY, 0, 7, {117, 106, 74, 267, 235, 241, 153, 0, 0, 0, 0, 0, 0, 0, 0}, 272},
    // [274] Nuzleaf
    {274, 10, 15, 1, 1, PERS_AGGRESSIVE, 1, 10, {1, 106, 74, 267, 252, 259, 185, 13, 207, 326, 0, 0, 0, 0, 0}, 273},
    // [275] Shiftry
    {275, 10, 15, 1, 1, PERS_AGGRESSIVE, 2, 4, {74, 106, 267, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 274},
    // [276] Taillow
    {276, 0, 2, 2, 1, PERS_CLUMSY, 0, 9, {45, 64, 116, 98, 17, 104, 283, 332, 97, 0, 0, 0, 0, 0, 0}, 275},
    // [277] Swellow
    {277, 0, 2, 2, 1, PERS_SNEAKY, 2, 9, {116, 45, 64, 98, 17, 104, 283, 332, 97, 0, 0, 0, 0, 0, 0}, 276},
    // [278] Wingull
    {278, 9, 2, 6, 3, PERS_CLUMSY, 0, 8, {45, 55, 48, 17, 54, 98, 228, 97, 0, 0, 0, 0, 0, 0, 0}, 277},
    // [279] Pelipper
    {279, 9, 2, 6, 2, PERS_PROUD, 2, 11, {45, 55, 346, 17, 48, 54, 182, 254, 256, 255, 56, 0, 0, 0, 0}, 278},
    // [280] Ralts
    {280, 12, 12, 2, 3, PERS_CLUMSY, 0, 10, {45, 93, 104, 100, 347, 94, 286, 248, 95, 138, 0, 0, 0, 0, 0}, 279},
    // [281] Kirlia
    {281, 12, 12, 2, 3, PERS_LAZY, 1, 10, {93, 104, 45, 100, 347, 94, 286, 248, 95, 138, 0, 0, 0, 0, 0}, 280},
    // [282] Gardevoir
    {282, 12, 12, 2, 3, PERS_LAZY, 2, 10, {93, 104, 45, 100, 347, 94, 286, 248, 95, 138, 0, 0, 0, 0, 0}, 281},
    // [283] Surskit
    {283, 6, 9, 6, 4, PERS_CLUMSY, 0, 8, {145, 98, 230, 346, 61, 97, 114, 54, 0, 0, 0, 0, 0, 0, 0}, 282},
    // [284] Masquerain
    {284, 6, 2, 1, 3, PERS_GENTLE, 2, 9, {145, 98, 230, 346, 16, 184, 78, 318, 18, 0, 0, 0, 0, 0, 0}, 283},
    // [285] Shroomish
    {285, 10, 10, 1, 2, PERS_CLUMSY, 0, 10, {71, 33, 78, 73, 72, 29, 77, 74, 202, 147, 0, 0, 0, 0, 0}, 284},
    // [286] Breloom
    {286, 10, 1, 1, 1, PERS_AGGRESSIVE, 2, 11, {71, 73, 78, 33, 72, 29, 183, 68, 327, 170, 223, 0, 0, 0, 0}, 285},
    // [287] Slakoth
    {287, 0, 0, 2, 1, PERS_LAZY, 0, 9, {10, 281, 227, 303, 185, 133, 343, 68, 175, 0, 0, 0, 0, 0, 0}, 286},
    // [288] Vigoroth
    {288, 0, 0, 2, 1, PERS_SNEAKY, 1, 10, {227, 116, 10, 253, 154, 203, 163, 68, 264, 179, 0, 0, 0, 0, 0}, 287},
    // [289] Slaking
    {289, 0, 0, 2, 1, PERS_LAZY, 2, 10, {227, 10, 303, 281, 185, 133, 343, 207, 68, 175, 0, 0, 0, 0, 0}, 288},
    // [290] Nincada
    {290, 6, 4, 0, 2, PERS_CLUMSY, 0, 10, {106, 10, 141, 28, 154, 170, 206, 189, 232, 91, 0, 0, 0, 0, 0}, 289},
    // [291] Ninjask
    {291, 6, 2, 1, 1, PERS_SNEAKY, 2, 13, {106, 141, 28, 10, 154, 170, 104, 210, 103, 14, 163, 97, 226, 0, 0}, 290},
    // [292] Shedinja
    {292, 6, 7, 1, 1, PERS_CLUMSY, 0, 10, {106, 10, 141, 28, 154, 170, 180, 109, 247, 288, 0, 0, 0, 0, 0}, 291},
    // [293] Whismur
    {293, 0, 0, 2, 0, PERS_GENTLE, 0, 11, {1, 253, 310, 336, 48, 23, 103, 46, 156, 214, 304, 0, 0, 0, 0}, 292},
    // [294] Loudred
    {294, 0, 0, 2, 0, PERS_AGGRESSIVE, 1, 11, {310, 336, 1, 253, 48, 23, 103, 46, 156, 214, 304, 0, 0, 0, 0}, 293},
    // [295] Exploud
    {295, 0, 0, 2, 0, PERS_AGGRESSIVE, 2, 12, {310, 336, 1, 253, 48, 23, 103, 63, 46, 156, 214, 304, 0, 0, 0}, 294},
    // [296] Makuhita
    {296, 1, 1, 2, 0, PERS_CLUMSY, 0, 13, {116, 33, 28, 292, 233, 252, 18, 282, 265, 187, 203, 69, 179, 0, 0}, 295},
    // [297] Hariyama
    {297, 1, 1, 2, 0, PERS_GENTLE, 2, 13, {292, 116, 28, 33, 233, 252, 18, 282, 265, 187, 203, 69, 179, 0, 0}, 296},
    // [298] Azurill
    {298, 0, 0, 2, 0, PERS_CLUMSY, 0, 6, {150, 204, 39, 145, 21, 55, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 297},
    // [299] Nosepass
    {299, 5, 5, 0, 2, PERS_PROUD, 0, 10, {33, 106, 88, 335, 86, 157, 201, 156, 192, 199, 0, 0, 0, 0, 0}, 298},
    // [300] Skitty
    {300, 0, 0, 2, 0, PERS_CLUMSY, 0, 12, {45, 33, 39, 213, 47, 3, 274, 204, 185, 343, 215, 38, 0, 0, 0}, 299},
    // [301] Delcatty
    {301, 0, 0, 2, 0, PERS_SNEAKY, 2, 4, {213, 3, 45, 47, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 300},
    // [302] Sableye
    {302, 15, 7, 0, 1, PERS_AGGRESSIVE, 0, 13, {43, 10, 193, 101, 310, 154, 252, 197, 185, 282, 109, 247, 212, 0, 0}, 301},
    // [303] Mawile
    {303, 16, 16, 2, 1, PERS_AGGRESSIVE, 0, 12, {310, 313, 44, 230, 11, 185, 226, 242, 334, 255, 254, 256, 0, 0, 0}, 302},
    // [304] Aron
    {304, 16, 5, 0, 2, PERS_PROUD, 0, 12, {33, 106, 189, 29, 232, 334, 46, 36, 231, 182, 319, 38, 0, 0, 0}, 303},
    // [305] Lairon
    {305, 16, 5, 0, 2, PERS_PROUD, 1, 12, {106, 29, 189, 33, 232, 334, 46, 36, 231, 182, 319, 38, 0, 0, 0}, 304},
    // [306] Aggron
    {306, 16, 5, 3, 2, PERS_AGGRESSIVE, 2, 12, {106, 29, 189, 33, 232, 334, 46, 36, 231, 182, 319, 38, 0, 0, 0}, 305},
    // [307] Meditite
    {307, 1, 12, 2, 2, PERS_CLUMSY, 0, 11, {117, 96, 93, 197, 237, 170, 347, 136, 244, 179, 105, 0, 0, 0, 0}, 306},
    // [308] Medicham
    {308, 1, 12, 2, 2, PERS_SNEAKY, 2, 14, {117, 93, 197, 7, 8, 96, 9, 237, 170, 347, 136, 244, 179, 105, 0}, 307},
    // [309] Electrike
    {309, 11, 11, 2, 3, PERS_CLUMSY, 0, 11, {33, 86, 43, 336, 98, 209, 316, 46, 44, 87, 268, 0, 0, 0, 0}, 308},
    // [310] Manectric
    {310, 11, 11, 2, 3, PERS_SNEAKY, 2, 11, {336, 43, 33, 86, 98, 209, 316, 46, 44, 87, 268, 0, 0, 0, 0}, 309},
    // [311] Plusle
    {311, 11, 11, 2, 3, PERS_SNEAKY, 0, 11, {45, 86, 98, 270, 209, 227, 313, 268, 87, 226, 97, 0, 0, 0, 0}, 310},
    // [312] Minun
    {312, 11, 11, 2, 4, PERS_LAZY, 0, 11, {45, 86, 98, 270, 209, 227, 204, 268, 87, 226, 97, 0, 0, 0, 0}, 311},
    // [313] Volbeat
    {313, 6, 6, 1, 4, PERS_SNEAKY, 0, 10, {33, 109, 104, 236, 98, 294, 324, 182, 270, 38, 0, 0, 0, 0, 0}, 312},
    // [314] Illumise
    {314, 6, 6, 1, 4, PERS_SNEAKY, 0, 10, {33, 230, 204, 236, 98, 273, 227, 260, 270, 343, 0, 0, 0, 0, 0}, 313},
    // [315] Roselia
    {315, 10, 3, 1, 3, PERS_SNEAKY, 1, 15, {71, 74, 40, 78, 72, 73, 345, 320, 202, 230, 275, 92, 80, 312, 235}, 314},
    // [316] Gulpin
    {316, 3, 3, 2, 0, PERS_PROUD, 0, 11, {1, 281, 139, 124, 133, 227, 92, 255, 254, 256, 188, 0, 0, 0, 0}, 315},
    // [317] Swalot
    {317, 3, 3, 2, 0, PERS_LAZY, 2, 12, {139, 1, 124, 281, 133, 227, 34, 92, 255, 254, 256, 188, 0, 0, 0}, 316},
    // [318] Carvanha
    {318, 9, 15, 6, 1, PERS_AGGRESSIVE, 0, 10, {44, 43, 99, 116, 184, 242, 103, 36, 207, 97, 0, 0, 0, 0, 0}, 317},
    // [319] Sharpedo
    {319, 9, 15, 6, 1, PERS_AGGRESSIVE, 2, 12, {44, 116, 43, 99, 184, 242, 103, 163, 269, 207, 130, 97, 0, 0, 0}, 318},
    // [320] Wailmer
    {320, 9, 9, 6, 0, PERS_AGGRESSIVE, 0, 12, {150, 45, 55, 205, 250, 310, 352, 54, 156, 323, 133, 56, 0, 0, 0}, 319},
    // [321] Wailord
    {321, 9, 9, 6, 0, PERS_AGGRESSIVE, 2, 12, {45, 205, 150, 55, 250, 310, 352, 54, 156, 323, 133, 56, 0, 0, 0}, 320},
    // [322] Numel
    {322, 8, 4, 0, 3, PERS_GENTLE, 0, 10, {45, 33, 52, 222, 116, 36, 133, 89, 53, 38, 0, 0, 0, 0, 0}, 321},
    // [323] Camerupt
    {323, 8, 4, 3, 3, PERS_GENTLE, 2, 11, {52, 45, 222, 33, 116, 36, 133, 157, 89, 284, 90, 0, 0, 0, 0}, 322},
    // [324] Torkoal
    {324, 8, 8, 2, 2, PERS_PROUD, 0, 12, {52, 123, 174, 108, 83, 34, 182, 53, 334, 133, 175, 257, 0, 0, 0}, 323},
    // [325] Spoink
    {325, 12, 12, 2, 4, PERS_SNEAKY, 0, 11, {150, 149, 316, 60, 244, 109, 277, 94, 156, 173, 340, 0, 0, 0, 0}, 324},
    // [326] Grumpig
    {326, 12, 12, 2, 4, PERS_SNEAKY, 2, 11, {316, 60, 149, 150, 244, 109, 277, 94, 156, 173, 340, 0, 0, 0, 0}, 325},
    // [327] Spinda
    {327, 0, 0, 2, 1, PERS_AGGRESSIVE, 0, 11, {33, 253, 185, 60, 95, 146, 298, 244, 38, 175, 37, 0, 0, 0, 0}, 326},
    // [328] Trapinch
    {328, 4, 4, 0, 1, PERS_CLUMSY, 0, 8, {44, 28, 185, 328, 242, 91, 201, 63, 0, 0, 0, 0, 0, 0, 0}, 327},
    // [329] Vibrava
    {329, 4, 14, 0, 1, PERS_LAZY, 1, 9, {44, 185, 28, 328, 242, 225, 103, 201, 63, 0, 0, 0, 0, 0, 0}, 328},
    // [330] Flygon
    {330, 4, 14, 3, 1, PERS_LAZY, 2, 9, {44, 185, 28, 328, 242, 225, 103, 201, 63, 0, 0, 0, 0, 0, 0}, 329},
    // [331] Cacnea
    {331, 10, 10, 1, 1, PERS_AGGRESSIVE, 0, 13, {43, 40, 71, 74, 73, 28, 42, 275, 185, 191, 302, 178, 201, 0, 0}, 330},
    // [332] Cacturne
    {332, 10, 15, 1, 1, PERS_AGGRESSIVE, 2, 13, {71, 74, 43, 40, 73, 28, 42, 275, 185, 191, 302, 178, 201, 0, 0}, 331},
    // [333] Swablu
    {333, 0, 2, 2, 4, PERS_PROUD, 0, 11, {45, 64, 310, 47, 31, 219, 54, 36, 119, 287, 195, 0, 0, 0, 0}, 332},
    // [334] Altaria
    {334, 14, 2, 2, 4, PERS_GENTLE, 2, 13, {310, 45, 64, 47, 31, 219, 54, 36, 225, 349, 287, 195, 143, 0, 0}, 333},
    // [335] Zangoose
    {335, 0, 0, 2, 1, PERS_AGGRESSIVE, 0, 11, {10, 43, 98, 14, 210, 163, 228, 306, 269, 197, 206, 0, 0, 0, 0}, 334},
    // [336] Seviper
    {336, 3, 3, 2, 1, PERS_AGGRESSIVE, 0, 10, {35, 122, 44, 342, 103, 137, 242, 305, 207, 114, 0, 0, 0, 0, 0}, 335},
    // [337] Lunatone
    {337, 5, 12, 0, 3, PERS_SNEAKY, 0, 10, {106, 33, 93, 88, 95, 149, 322, 94, 248, 153, 0, 0, 0, 0, 0}, 336},
    // [338] Solrock
    {338, 5, 12, 0, 1, PERS_AGGRESSIVE, 0, 10, {106, 33, 93, 88, 83, 149, 322, 157, 76, 153, 0, 0, 0, 0, 0}, 337},
    // [339] Barboach
    {339, 9, 4, 6, 0, PERS_CLUMSY, 0, 11, {189, 300, 346, 55, 222, 133, 156, 173, 89, 248, 90, 0, 0, 0, 0}, 338},
    // [340] Whiscash
    {340, 9, 4, 6, 0, PERS_AGGRESSIVE, 2, 12, {189, 300, 321, 346, 55, 222, 133, 156, 173, 89, 248, 90, 0, 0, 0}, 339},
    // [341] Corphish
    {341, 9, 9, 6, 1, PERS_AGGRESSIVE, 0, 11, {145, 106, 11, 43, 61, 182, 282, 269, 152, 14, 12, 0, 0, 0, 0}, 340},
    // [342] Crawdaunt
    {342, 9, 15, 6, 1, PERS_AGGRESSIVE, 2, 11, {145, 106, 43, 11, 61, 182, 282, 269, 152, 14, 12, 0, 0, 0, 0}, 341},
    // [343] Baltoy
    {343, 4, 12, 0, 4, PERS_GENTLE, 0, 11, {93, 106, 229, 189, 60, 317, 120, 246, 201, 322, 153, 0, 0, 0, 0}, 342},
    // [344] Claydol
    {344, 4, 12, 3, 4, PERS_PROUD, 2, 13, {93, 106, 229, 100, 189, 60, 317, 120, 246, 201, 63, 322, 153, 0, 0}, 343},
    // [345] Lileep
    {345, 5, 10, 0, 4, PERS_PROUD, 0, 10, {310, 132, 51, 275, 109, 133, 246, 255, 254, 256, 0, 0, 0, 0, 0}, 344},
    // [346] Cradily
    {346, 5, 10, 3, 4, PERS_PROUD, 2, 10, {51, 310, 132, 275, 109, 133, 246, 255, 254, 256, 0, 0, 0, 0, 0}, 345},
    // [347] Anorith
    {347, 5, 6, 0, 1, PERS_AGGRESSIVE, 0, 10, {10, 106, 300, 55, 232, 182, 246, 210, 163, 350, 0, 0, 0, 0, 0}, 346},
    // [348] Armaldo
    {348, 5, 6, 3, 1, PERS_AGGRESSIVE, 2, 10, {106, 300, 10, 55, 232, 182, 246, 210, 163, 350, 0, 0, 0, 0, 0}, 347},
    // [349] Feebas
    {349, 9, 9, 6, 4, PERS_CLUMSY, 0, 3, {150, 33, 175, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 348},
    // [350] Milotic
    {350, 9, 9, 6, 4, PERS_SNEAKY, 2, 11, {55, 35, 346, 287, 352, 239, 105, 240, 56, 213, 219, 0, 0, 0, 0}, 349},
    // [351] Castform
    {351, 0, 0, 2, 1, PERS_AGGRESSIVE, 0, 8, {33, 52, 181, 55, 258, 240, 241, 311, 0, 0, 0, 0, 0, 0, 0}, 350},
    // [352] Kecleon
    {352, 0, 0, 2, 4, PERS_GENTLE, 0, 13, {310, 122, 10, 39, 168, 20, 185, 154, 60, 103, 163, 164, 246, 0, 0}, 351},
    // [353] Shuppet
    {353, 7, 7, 0, 1, PERS_CLUMSY, 0, 10, {282, 103, 101, 174, 180, 261, 185, 247, 289, 288, 0, 0, 0, 0, 0}, 352},
    // [354] Banette
    {354, 7, 7, 0, 1, PERS_AGGRESSIVE, 2, 10, {174, 282, 101, 103, 180, 261, 185, 247, 289, 288, 0, 0, 0, 0, 0}, 353},
    // [355] Duskull
    {355, 7, 7, 0, 2, PERS_CLUMSY, 0, 11, {43, 101, 50, 193, 310, 109, 228, 174, 261, 212, 248, 0, 0, 0, 0}, 354},
    // [356] Dusclops
    {356, 7, 7, 0, 2, PERS_PROUD, 1, 13, {20, 50, 43, 101, 193, 310, 109, 228, 174, 325, 261, 212, 248, 0, 0}, 355},
    // [357] Tropius
    {357, 10, 2, 1, 0, PERS_GENTLE, 0, 11, {16, 43, 74, 75, 23, 230, 18, 345, 34, 76, 235, 0, 0, 0, 0}, 356},
    // [358] Chimecho
    {358, 12, 12, 2, 3, PERS_PROUD, 2, 12, {35, 45, 310, 93, 36, 253, 281, 149, 38, 215, 219, 94, 0, 0, 0}, 357},
    // [359] Absol
    {359, 15, 15, 2, 1, PERS_GENTLE, 0, 11, {10, 43, 269, 98, 13, 44, 14, 104, 163, 248, 195, 0, 0, 0, 0}, 358},
    // [360] Wynaut
    {360, 12, 12, 2, 0, PERS_CLUMSY, 0, 7, {204, 227, 150, 68, 194, 243, 219, 0, 0, 0, 0, 0, 0, 0, 0}, 359},
    // [361] Snorunt
    {361, 13, 13, 3, 1, PERS_AGGRESSIVE, 0, 11, {43, 181, 104, 44, 196, 29, 182, 242, 58, 258, 59, 0, 0, 0, 0}, 360},
    // [362] Glalie
    {362, 13, 13, 3, 1, PERS_AGGRESSIVE, 2, 12, {44, 104, 43, 181, 196, 29, 182, 242, 58, 258, 59, 329, 0, 0, 0}, 361},
    // [363] Spheal
    {363, 13, 9, 6, 0, PERS_GENTLE, 0, 12, {45, 181, 55, 227, 301, 34, 62, 258, 156, 173, 59, 329, 0, 0, 0}, 362},
    // [364] Sealeo
    {364, 13, 9, 6, 0, PERS_LAZY, 1, 12, {227, 45, 181, 55, 301, 34, 62, 258, 156, 173, 59, 329, 0, 0, 0}, 363},
    // [365] Walrein
    {365, 13, 9, 6, 0, PERS_AGGRESSIVE, 2, 12, {227, 45, 181, 55, 301, 34, 62, 258, 156, 173, 59, 329, 0, 0, 0}, 364},
    // [366] Clamperl
    {366, 9, 9, 6, 2, PERS_PROUD, 0, 4, {128, 334, 55, 250, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 365},
    // [367] Huntail
    {367, 9, 9, 6, 2, PERS_PROUD, 2, 8, {250, 44, 103, 352, 184, 242, 226, 56, 0, 0, 0, 0, 0, 0, 0}, 366},
    // [368] Gorebyss
    {368, 9, 9, 6, 3, PERS_PROUD, 2, 8, {250, 93, 97, 352, 133, 94, 226, 56, 0, 0, 0, 0, 0, 0, 0}, 367},
    // [369] Relicanth
    {369, 9, 5, 6, 2, PERS_PROUD, 0, 11, {106, 33, 55, 317, 281, 36, 300, 246, 156, 38, 56, 0, 0, 0, 0}, 368},
    // [370] Luvdisc
    {370, 9, 9, 6, 4, PERS_SNEAKY, 0, 9, {33, 204, 55, 97, 36, 213, 186, 175, 219, 0, 0, 0, 0, 0, 0}, 369},
    // [371] Bagon
    {371, 14, 14, 2, 1, PERS_AGGRESSIVE, 0, 11, {99, 44, 43, 29, 116, 52, 225, 184, 242, 337, 38, 0, 0, 0, 0}, 370},
    // [372] Shelgon
    {372, 14, 14, 2, 2, PERS_LAZY, 1, 12, {44, 29, 43, 99, 116, 52, 182, 225, 184, 242, 337, 38, 0, 0, 0}, 371},
    // [373] Salamence
    {373, 14, 2, 2, 1, PERS_LAZY, 2, 13, {44, 29, 43, 99, 116, 52, 182, 225, 184, 19, 242, 337, 38, 0, 0}, 372},
    // [374] Beldum
    {374, 16, 12, 2, 2, PERS_LAZY, 0, 1, {36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 373},
    // [375] Metang
    {375, 16, 12, 2, 2, PERS_ANXIOUS, 1, 10, {36, 93, 232, 184, 228, 94, 334, 309, 97, 63, 0, 0, 0, 0, 0}, 374},
    // [376] Metagross
    {376, 16, 12, 2, 1, PERS_AGGRESSIVE, 2, 10, {93, 232, 184, 36, 228, 94, 334, 309, 97, 63, 0, 0, 0, 0, 0}, 375},
    // [377] Regirock
    {377, 5, 5, 4, 2, PERS_PROUD, 0, 9, {153, 88, 174, 276, 246, 334, 192, 199, 63, 0, 0, 0, 0, 0, 0}, 376},
    // [378] Regice
    {378, 13, 13, 4, 4, PERS_PROUD, 0, 9, {153, 196, 174, 276, 246, 133, 192, 199, 63, 0, 0, 0, 0, 0, 0}, 377},
    // [379] Registeel
    {379, 16, 16, 4, 2, PERS_PROUD, 0, 10, {153, 232, 174, 276, 246, 133, 334, 192, 199, 63, 0, 0, 0, 0, 0}, 378},
    // [380] Latias
    {380, 14, 12, 4, 4, PERS_GENTLE, 0, 11, {149, 273, 270, 219, 225, 346, 287, 296, 94, 105, 204, 0, 0, 0, 0}, 379},
    // [381] Latios
    {381, 14, 12, 4, 3, PERS_GENTLE, 0, 11, {149, 262, 270, 219, 225, 182, 287, 295, 94, 105, 349, 0, 0, 0, 0}, 380},
    // [382] Kyogre
    {382, 9, 9, 4, 3, PERS_AGGRESSIVE, 0, 11, {352, 184, 246, 34, 347, 58, 56, 156, 329, 38, 323, 0, 0, 0, 0}, 381},
    // [383] Groudon
    {383, 4, 4, 4, 1, PERS_AGGRESSIVE, 0, 11, {341, 184, 246, 163, 339, 89, 126, 156, 90, 76, 284, 0, 0, 0, 0}, 382},
    // [384] Rayquaza
    {384, 14, 2, 4, 1, PERS_AGGRESSIVE, 0, 11, {239, 184, 246, 337, 349, 242, 19, 156, 245, 200, 63, 0, 0, 0, 0}, 383},
    // [385] Jirachi
    {385, 16, 12, 4, 1, PERS_LAZY, 0, 11, {93, 273, 156, 129, 270, 94, 287, 38, 248, 322, 353, 0, 0, 0, 0}, 384},
    // [386] Deoxys
    {386, 12, 12, 4, 1, PERS_AGGRESSIVE, 0, 12, {43, 35, 101, 100, 282, 228, 94, 289, 322, 105, 354, 63, 0, 0, 0}, 385},
};
static constexpr uint16_t DAYCARE_SPECIES_COUNT = 386;

// ── Type behavior weights ───────────────────────────────
// { social, combat, explore, rest, mischief }
struct TypeBehavior {
    uint8_t social, combat, explore, rest, mischief;
};

static const TypeBehavior daycareTypeBehaviors[TYPE_COUNT] = {
    {200,  80, 120, 180,  60},  // normal
    {120, 255,  80,  60,  40},  // fighting
    {140, 100, 200, 100,  80},  // flying
    { 60, 100, 100, 120, 200},  // poison
    { 80, 120, 180, 160,  40},  // ground
    { 60, 140, 120, 200,  20},  // rock
    {100, 100, 180, 120,  80},  // bug
    { 40, 100, 120,  80, 255},  // ghost
    {100, 200, 120, 140, 100},  // fire
    {160, 100, 180, 120,  80},  // water
    {160,  60, 140, 200,  40},  // grass
    {120, 140, 160,  60, 200},  // electric
    { 80, 100, 100, 160, 120},  // psychic
    {100,  80, 120, 180,  60},  // ice
    { 60, 200, 140, 100,  60},  // dragon
    { 70, 200, 150,  80, 220},  // dark
    { 80, 160, 100, 220,  20},  // steel
};

// ── Dex number -> species table entry (1-based, nullptr = invalid) ──
inline const DaycareSpecies *daycareGetSpecies(uint16_t dexNum) {
    if (dexNum < 1 || dexNum > DAYCARE_SPECIES_COUNT) return nullptr;
    return &daycareSpecies[dexNum - 1];
}
