#!/usr/bin/env python3
"""Bake FULL-COLOR Gen 3 sprites for the T-DECK firmware battle screen.

The T-Deck draws sprites into an RGB565 LVGL canvas (not SDL like the Pi), so
here each pixel is a little-endian RGB565 word; transparent source pixels get a
sentinel value (0xF81F magenta — never a real sprite colour) that the on-device
render maps to the battle-screen background. The RGB565 stream is RAW-DEFLATE
compressed (decoded with the vendored puff()). Reuses the Pi bake's fetch/scale.

Outputs into meshtastic-firmware/src/modules/monstermesh/:
  Gen3Front565.h  (front, 56x56)   Gen3Back565.h  (back, 48x48)
"""
import importlib.util, struct, sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
OUTDIR = os.path.join(REPO, "meshtastic-firmware", "src", "modules", "monstermesh")

# reuse the Pi bake's helpers (fetch_with_fallback, scale_rgba, raw_deflate, NAMES)
spec = importlib.util.spec_from_file_location("g3", os.path.join(HERE, "gen3_sprite_bake.py"))
g3 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(g3)

# Store NATIVE Gen-3 art (64x64) — bit-perfect, no fractional upscale. The
# T-Deck decodes straight into a fixed LVGL canvas, so stored size == on-screen
# size (64px). Covers the full national dex through Gen 3.
FRONT = 64
BACK = 64
MAXDEX = 386
SENTINEL = 0xF81F  # transparent marker (magenta) — mapped to bg on-device


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def rgb565_bytes(img):
    out = bytearray()
    for (r, g, b, a) in img.getdata():
        v = SENTINEL if a < 128 else rgb565(r, g, b)
        out += struct.pack("<H", v)  # little-endian, matches LVGL RGB565 canvas
    return bytes(out)


def process(dex, kind, w, h):
    img, label = g3.fetch_with_fallback(dex, kind)
    if img is None:
        return None, None
    img = g3.scale_rgba(img, w, h)
    return g3.raw_deflate(rgb565_bytes(img)), label


def write_header(path, sym, off_sym, macro_w, macro_h, w, h, blobs, title):
    flat = bytearray()
    offsets = [0] * (MAXDEX + 2)
    for dex in range(MAXDEX + 1):
        offsets[dex] = len(flat)
        flat.extend(blobs[dex])
    offsets[MAXDEX + 1] = len(flat)
    L = []
    L.append("// SPDX-License-Identifier: MIT")
    L.append(f"// {title}")
    L.append("// AUTO-GENERATED by tools/gen3_sprite_bake_tdeck.py — DO NOT EDIT.")
    L.append("//")
    L.append("// Full-color Gen 3 sprites for the T-Deck. Each pixel is a")
    L.append("// little-endian RGB565 word; 0xF81F marks a transparent pixel")
    L.append("// (mapped to the battle background on-device). RAW-DEFLATE")
    L.append("// compressed (wbits=-9); decode via puff() (../pentest/puff.h).")
    L.append("#pragma once")
    L.append("#include <stdint.h>")
    L.append("")
    L.append(f"static constexpr uint16_t {macro_w} = {w};")
    L.append(f"static constexpr uint16_t {macro_h} = {h};")
    L.append("")
    L.append(f"// Total deflated RGB565 data: {len(flat)} B")
    L.append(f"static const uint8_t {sym}[{len(flat)}] = {{")
    for i in range(0, len(flat), 16):
        L.append("    " + ", ".join(f"0x{b:02X}" for b in flat[i:i+16]) + ",")
    L.append("};")
    L.append("")
    L.append(f"static const uint32_t {off_sym}[{MAXDEX + 2}] = {{")
    for i in range(0, len(offsets), 8):
        L.append("    " + ", ".join(str(v) for v in offsets[i:i+8]) + ",")
    L.append("};")
    L.append("")
    open(path, "w").write("\n".join(L))
    return len(flat)


def main():
    front_blobs = [b""] * (MAXDEX + 1)
    back_blobs = [b""] * (MAXDEX + 1)
    for dex in range(1, MAXDEX + 1):
        b, lab = process(dex, "front", FRONT, FRONT)
        front_blobs[dex] = b or b""
        b2, lab2 = process(dex, "back", BACK, BACK)
        back_blobs[dex] = b2 or b""
        print(f"  {dex:3d} {g3.spname(dex):14s} front={len(front_blobs[dex]):5d}B "
              f"back={len(back_blobs[dex]):5d}B  ({lab})", file=sys.stderr)
    tf = write_header(os.path.join(OUTDIR, "Gen3Front565.h"),
                      "kGen3Front565Deflate", "kGen3Front565Offsets",
                      "GEN3_FRONT_565_W", "GEN3_FRONT_565_H", FRONT, FRONT, front_blobs,
                      f"Gen3Front565 — {FRONT}x{FRONT} full-color Gen-3 front sprites")
    tb = write_header(os.path.join(OUTDIR, "Gen3Back565.h"),
                      "kGen3Back565Deflate", "kGen3Back565Offsets",
                      "GEN3_BACK_565_W", "GEN3_BACK_565_H", BACK, BACK, back_blobs,
                      f"Gen3Back565 — {BACK}x{BACK} full-color Gen-3 back sprites")
    print(f"\nfront {tf} B, back {tb} B  -> {OUTDIR}", file=sys.stderr)


if __name__ == "__main__":
    main()
